-- Final, unpartitioned H2 schema for direct local ECL API and Batch execution.

CREATE TABLE cr_customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code VARCHAR(50) NOT NULL UNIQUE,
    customer_name VARCHAR(200) NOT NULL,
    customer_type VARCHAR(30) NOT NULL,
    internal_rating VARCHAR(10),
    external_rating VARCHAR(10),
    industry_code VARCHAR(20),
    country_code VARCHAR(2),
    is_sme BOOLEAN DEFAULT FALSE,
    fin_sector_cd VARCHAR(20),
    annual_sales NUMERIC(19,4),
    warning_level VARCHAR(20) DEFAULT 'NORMAL',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

CREATE TABLE cr_product_masters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(20) NOT NULL UNIQUE,
    product_name VARCHAR(200) NOT NULL,
    ccf_rate NUMERIC(10,6) NOT NULL DEFAULT 0,
    description VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

CREATE TABLE cr_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    account_no VARCHAR(50) NOT NULL UNIQUE,
    product_code VARCHAR(20) NOT NULL,
    outstanding_amt NUMERIC(19,4) NOT NULL DEFAULT 0,
    notional_amt NUMERIC(19,4) NOT NULL DEFAULT 0,
    prod_category VARCHAR(30),
    int_rate NUMERIC(19,6),
    repayment_method VARCHAR(30),
    grace_period INTEGER,
    repayment_freq INTEGER,
    branch_cd VARCHAR(20),
    biz_unit_cd VARCHAR(20),
    currency VARCHAR(3) NOT NULL DEFAULT 'KRW',
    open_date DATE NOT NULL,
    maturity_date DATE,
    delinquent_days INTEGER DEFAULT 0,
    original_rating VARCHAR(20),
    staging VARCHAR(20),
    internal_rating VARCHAR(10),
    is_debt_restructured BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    error_message VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_cr_accounts_customer
        FOREIGN KEY (customer_id) REFERENCES cr_customers(id)
);

CREATE TABLE cr_collaterals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    collateral_code VARCHAR(50) NOT NULL UNIQUE,
    collateral_type VARCHAR(30) NOT NULL,
    appraisal_amt NUMERIC(19,4) NOT NULL DEFAULT 0,
    base_haircut NUMERIC(10,6) NOT NULL DEFAULT 0,
    prior_lien_amt NUMERIC(19,4) DEFAULT 0,
    ltv_limit NUMERIC(10,6),
    kb_market_price NUMERIC(19,4),
    district_code VARCHAR(10),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_cr_collaterals_customer
        FOREIGN KEY (customer_id) REFERENCES cr_customers(id)
);

CREATE TABLE cr_account_collaterals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    collateral_id BIGINT NOT NULL,
    allocation_amount NUMERIC(19,4) NOT NULL DEFAULT 0,
    priority INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_cr_account_collaterals_account
        FOREIGN KEY (account_id) REFERENCES cr_accounts(id),
    CONSTRAINT fk_cr_account_collaterals_collateral
        FOREIGN KEY (collateral_id) REFERENCES cr_collaterals(id)
);

CREATE TABLE allowance_ecl_results (
    id BIGINT NOT NULL,
    base_date DATE NOT NULL,
    account_id BIGINT NOT NULL,
    staging VARCHAR(20) NOT NULL,
    ead NUMERIC(19,4),
    applied_ccf NUMERIC(10,6),
    pd NUMERIC(15,10),
    lgd NUMERIC(15,10),
    expected_loss NUMERIC(19,4),
    ecl_boom NUMERIC(19,4),
    ecl_base NUMERIC(19,4),
    ecl_recession NUMERIC(19,4),
    weighted_ecl NUMERIC(19,4),
    ead_star NUMERIC(19,4),
    crm_deduction NUMERIC(19,4),
    status VARCHAR(20) NOT NULL,
    error_message TEXT,
    calculation_completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    PRIMARY KEY (base_date, id),
    CONSTRAINT fk_allowance_ecl_results_account
        FOREIGN KEY (account_id) REFERENCES cr_accounts(id)
);

CREATE TABLE cr_grade_masters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_code VARCHAR(10) NOT NULL UNIQUE,
    pd_value NUMERIC(15,10) NOT NULL,
    notch_order INTEGER NOT NULL,
    description VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cr_lgd_segment_masters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    segment_name VARCHAR(100) NOT NULL,
    customer_type VARCHAR(30) NOT NULL,
    collateral_type VARCHAR(30) NOT NULL,
    lgd_value NUMERIC(15,10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_cr_lgd_segment_customer_collateral
        UNIQUE (customer_type, collateral_type)
);

CREATE TABLE allowance_model_parameters (
    param_key VARCHAR(50) PRIMARY KEY,
    param_value NUMERIC(19,10) NOT NULL,
    description VARCHAR(200),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cr_macro_scenario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apply_year INTEGER NOT NULL,
    scenario_type VARCHAR(20) NOT NULL,
    probability_weight NUMERIC(10,6) NOT NULL,
    pd_adjustment_factor NUMERIC(10,6) NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cr_cust_rating_hist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cust_id BIGINT NOT NULL,
    rating_cd VARCHAR(10) NOT NULL,
    base_dt DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cr_cust_rating_hist_customer
        FOREIGN KEY (cust_id) REFERENCES cr_customers(id)
);

CREATE TABLE transition_matrix (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_date DATE NOT NULL,
    from_rating VARCHAR(10) NOT NULL,
    to_rating VARCHAR(10) NOT NULL,
    probability NUMERIC(10,6) NOT NULL,
    time_horizon INTEGER DEFAULT 1,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT uq_transition_matrix_rating_path
        UNIQUE (base_date, from_rating, to_rating)
);

-- Account Mart-owned legacy read model used by the ECL persistence adapter.
CREATE TABLE allowance_input_positions (
    base_dt DATE NOT NULL,
    acc_no VARCHAR(50) NOT NULL,
    customer_code VARCHAR(50) NOT NULL,
    customer_name VARCHAR(200),
    cust_type VARCHAR(30),
    is_sme BOOLEAN DEFAULT FALSE,
    country_cd VARCHAR(10),
    prod_cd VARCHAR(20),
    prod_category VARCHAR(30),
    currency VARCHAR(3) NOT NULL,
    bs_class VARCHAR(10),
    cur_bal NUMERIC(19,4),
    limit_amt NUMERIC(19,4),
    outstd_amt NUMERIC(19,4),
    market_val NUMERIC(19,4),
    int_rate NUMERIC(10,6),
    coupon_rate NUMERIC(10,6),
    rate_type VARCHAR(10),
    base_rate_cd VARCHAR(20),
    spread NUMERIC(10,6),
    payment_freq INTEGER,
    next_reset_dt DATE,
    open_dt DATE,
    maturity_dt DATE,
    repayment_method VARCHAR(20),
    grace_period INTEGER,
    repayment_freq INTEGER,
    int_rate_floor NUMERIC(10,6),
    int_rate_cap NUMERIC(10,6),
    ref_index_cd VARCHAR(20),
    internal_rating VARCHAR(10),
    external_rating VARCHAR(10),
    industry_cd VARCHAR(20),
    warning_level VARCHAR(20),
    is_debt_restructured BOOLEAN DEFAULT FALSE,
    delinquent_days INTEGER DEFAULT 0,
    staging VARCHAR(20),
    coll_amt NUMERIC(19,4),
    recognized_coll_amt NUMERIC(19,4),
    coll_type VARCHAR(20),
    pd NUMERIC(10,8),
    lgd NUMERIC(10,8),
    expected_loss NUMERIC(19,4),
    branch_cd VARCHAR(10),
    biz_unit_cd VARCHAR(10),
    margin_rate NUMERIC(10,6),
    repricing_freq INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (base_dt, acc_no)
);

-- Current Account Mart -> ECL snapshot contract.
CREATE TABLE allowance_exposure_snapshots (
    base_date DATE NOT NULL,
    exposure_id VARCHAR(80) NOT NULL,
    source_system VARCHAR(30) NOT NULL,
    source_account_no VARCHAR(50) NOT NULL,
    customer_code VARCHAR(50) NOT NULL,
    customer_type VARCHAR(30),
    is_sme BOOLEAN DEFAULT FALSE,
    country_code VARCHAR(10),
    industry_code VARCHAR(20),
    product_code VARCHAR(20),
    product_category VARCHAR(30),
    legal_entity_code VARCHAR(20) NOT NULL,
    branch_code VARCHAR(20),
    currency_code VARCHAR(3) NOT NULL,
    outstanding_amount NUMERIC(19,4) NOT NULL DEFAULT 0,
    undrawn_amount NUMERIC(19,4) NOT NULL DEFAULT 0,
    interest_rate NUMERIC(10,6),
    effective_interest_rate NUMERIC(10,6),
    open_date DATE,
    maturity_date DATE,
    delinquent_days INTEGER DEFAULT 0,
    staging VARCHAR(20),
    original_rating VARCHAR(20),
    current_rating VARCHAR(20),
    warning_level VARCHAR(20),
    debt_restructured BOOLEAN NOT NULL DEFAULT FALSE,
    collateral_value NUMERIC(19,4) NOT NULL DEFAULT 0,
    collateral_type VARCHAR(20),
    accounting_account_code VARCHAR(20),
    allowance_account_code VARCHAR(20),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (base_date, exposure_id)
);

CREATE TABLE allowance_account_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(20) NOT NULL,
    biz_unit_code VARCHAR(20),
    currency_code VARCHAR(3),
    legal_entity_code VARCHAR(20) NOT NULL DEFAULT 'DEFAULT',
    exposure_account_code VARCHAR(20) NOT NULL,
    allowance_account_code VARCHAR(20) NOT NULL,
    bad_debt_expense_account_code VARCHAR(20) NOT NULL,
    reversal_income_account_code VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE allowance_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_date DATE NOT NULL,
    run_id VARCHAR(80) NOT NULL,
    model_version VARCHAR(80) NOT NULL,
    legal_entity_code VARCHAR(20) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    exposure_account_code VARCHAR(20) NOT NULL,
    allowance_account_code VARCHAR(20) NOT NULL,
    bad_debt_expense_account_code VARCHAR(20) NOT NULL,
    reversal_income_account_code VARCHAR(20) NOT NULL,
    target_allowance_amount NUMERIC(19,4) NOT NULL DEFAULT 0,
    source_exposure_amount NUMERIC(19,4) NOT NULL DEFAULT 0,
    stage1_allowance_amount NUMERIC(19,4) NOT NULL DEFAULT 0,
    stage2_allowance_amount NUMERIC(19,4) NOT NULL DEFAULT 0,
    stage3_allowance_amount NUMERIC(19,4) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_allowance_summary_run_key UNIQUE (
        base_date,
        run_id,
        legal_entity_code,
        currency_code,
        exposure_account_code,
        allowance_account_code
    )
);

CREATE INDEX idx_cr_accounts_customer_active
    ON cr_accounts(customer_id, is_active);
CREATE INDEX idx_cr_collaterals_customer_active
    ON cr_collaterals(customer_id, is_active);
CREATE INDEX idx_cr_account_collaterals_account
    ON cr_account_collaterals(account_id);
CREATE INDEX idx_cr_account_collaterals_collateral
    ON cr_account_collaterals(collateral_id);
CREATE INDEX idx_allowance_ecl_results_date_status
    ON allowance_ecl_results(base_date, status);
CREATE INDEX idx_cr_macro_scenario_apply_year
    ON cr_macro_scenario(apply_year);
CREATE INDEX idx_cr_cust_rating_hist_search
    ON cr_cust_rating_hist(cust_id, base_dt DESC);
CREATE INDEX idx_allowance_input_positions_base_dt
    ON allowance_input_positions(base_dt);
CREATE INDEX idx_allowance_exposure_base
    ON allowance_exposure_snapshots(base_date);
CREATE INDEX idx_allowance_exposure_customer
    ON allowance_exposure_snapshots(customer_code);
CREATE INDEX idx_allowance_exposure_product_currency
    ON allowance_exposure_snapshots(product_code, currency_code);
CREATE INDEX idx_allowance_account_mappings_lookup
    ON allowance_account_mappings(product_code, biz_unit_code, currency_code, active);
CREATE INDEX idx_allowance_summary_base_date
    ON allowance_summary(base_date);
CREATE INDEX idx_allowance_summary_run
    ON allowance_summary(base_date, run_id);
