-- P2P / Accounts Payable (AP) Schema

-- Table: purchase_invoices
CREATE TABLE purchase_invoices (
    invoice_no VARCHAR(50) NOT NULL,
    vendor_code VARCHAR(50) NOT NULL, -- FK to business_partners.businessPartnerCode
    issue_date DATE NOT NULL,
    due_date DATE NOT NULL,
    total_amount DECIMAL(19, 2) NOT NULL,
    tax_amount DECIMAL(19, 2) NOT NULL,
    net_amount DECIMAL(19, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    journal_entry_id BIGINT, -- FK to journal_entries.id
    description VARCHAR(500),
    created_by VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (invoice_no, vendor_code),
    FOREIGN KEY (vendor_code) REFERENCES business_partners(business_partner_code),
    FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id)
);

-- Table: payables
CREATE TABLE payables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_invoice_invoice_no VARCHAR(50) NOT NULL,
    purchase_invoice_vendor_code VARCHAR(50) NOT NULL,
    vendor_code VARCHAR(50) NOT NULL, -- FK to business_partners.businessPartnerCode
    original_amount DECIMAL(19, 2) NOT NULL,
    outstanding_amount DECIMAL(19, 2) NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    journal_entry_id BIGINT, -- FK to journal_entries.id (optional, for direct AP entries)
    created_at TIMESTAMP NOT NULL,
    FOREIGN KEY (purchase_invoice_invoice_no, purchase_invoice_vendor_code) REFERENCES purchase_invoices(invoice_no, vendor_code),
    FOREIGN KEY (vendor_code) REFERENCES business_partners(business_partner_code),
    FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id)
);

-- Table: payments
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_date DATE NOT NULL,
    vendor_code VARCHAR(50) NOT NULL, -- FK to business_partners.businessPartnerCode
    amount DECIMAL(19, 2) NOT NULL,
    bank_account VARCHAR(100),
    reference_no VARCHAR(100),
    status VARCHAR(20) NOT NULL,
    journal_entry_id BIGINT, -- FK to journal_entries.id
    payment_run_id BIGINT, -- FK to payment_runs.id
    created_at TIMESTAMP NOT NULL,
    FOREIGN KEY (vendor_code) REFERENCES business_partners(business_partner_code),
    FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id),
    FOREIGN KEY (payment_run_id) REFERENCES payment_runs(id)
);

-- Table: payment_runs
CREATE TABLE payment_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_date DATE NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    created_by VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

-- Table: advance_payments
CREATE TABLE advance_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_code VARCHAR(50) NOT NULL, -- FK to business_partners.businessPartnerCode
    payment_date DATE NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    outstanding_amount DECIMAL(19, 2) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    journal_entry_id BIGINT, -- FK to journal_entries.id
    created_at TIMESTAMP NOT NULL,
    FOREIGN KEY (vendor_code) REFERENCES business_partners(business_partner_code),
    FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id)
);
