package com.ho.account.migration;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

class PostgresqlMigrationResourceTest {

    @ParameterizedTest
    @ValueSource(strings = {
            "db/contexts/asset-lease/V20__init_asset_lease.sql",
            "db/contexts/deposit/V40__init_deposit_schema.sql",
            "db/contexts/loan/V30__init_loan_schema.sql"
    })
    void packagedPostgresqlVariantsContainNoH2OnlyIdentityOrTimestampSyntax(String resource)
            throws IOException {
        String sql = read(resource);

        assertThat(sql)
                .doesNotContain("AUTO_INCREMENT")
                .doesNotContain("DATETIME")
                .doesNotContain("ON UPDATE CURRENT_TIMESTAMP")
                .contains("GENERATED BY DEFAULT AS IDENTITY");
    }

    private String read(String resource) throws IOException {
        try (InputStream input = getClass().getClassLoader().getResourceAsStream(resource)) {
            assertThat(input).as(resource).isNotNull();
            return new String(input.readAllBytes(), StandardCharsets.UTF_8);
        }
    }
}
