package com.ho.account.migration;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.junit.jupiter.params.provider.ValueSource;

class PostgresqlMigrationResourceTest {

    @ParameterizedTest
    @ValueSource(strings = {
            "db/contexts/account-mart/V6__complete_account_mart_schema.sql",
            "db/contexts/asset-lease/V20__init_asset_lease.sql",
            "db/contexts/closing/V49__closing_clean_baseline.sql",
            "db/contexts/deposit/V40__init_deposit_schema.sql",
            "db/contexts/ecl/V4__complete_ecl_schema.sql",
            "db/contexts/expenditure-resolution/V1__expenditure_resolution_baseline.sql",
            "db/contexts/journal-ledger/V11__journal_ledger_postgresql_baseline.sql",
            "db/contexts/loan/V30__init_loan_schema.sql",
            "db/contexts/master-data/V6__master_data_postgresql_baseline.sql",
            "db/contexts/payable/V1__payable_baseline.sql",
            "db/contexts/receivable/V1__receivable_baseline.sql",
            "db/contexts/reconciliation/V1__reconciliation_baseline.sql",
            "db/contexts/tax/V1__tax_baseline.sql"
    })
    void packagedPostgresqlVariantsContainNoH2OnlyIdentityOrTimestampSyntax(String resource)
            throws IOException {
        String sql = read(resource);

        assertThat(sql)
                .doesNotContain("AUTO_INCREMENT")
                .doesNotContain("DATETIME")
                .doesNotContain("ON UPDATE CURRENT_TIMESTAMP")
                .contains("GENERATED BY DEFAULT AS IDENTITY");
    }

    @ParameterizedTest
    @CsvSource({
            "db/contexts/account-mart/V1__init_mart_schema.sql,54703772a4fdb0ef3cd9978bbb0f307c3ea3430526331b7fe2977c27b897b471",
            "db/contexts/account-mart/V2__add_allowance_exposure_snapshot.sql,8a5a56eadb2f0260b7643921e4ce55c8a26c2ba64847f47f8b993ae45d38a6de",
            "db/contexts/account-mart/V3__add_allowance_audit_logs.sql,8f07394b505f8db4d03a864adf8352f8505b8fe34635d04d1c5c143f4d80da93",
            "db/contexts/account-mart/V4__add_product_master_api_columns.sql,2b161eaba79f8b9904834db8a693f3d57962aeecef71b25a83bcfc294970c425",
            "db/contexts/account-mart/V5__add_ods_apart_coll_detail.sql,ba6410bbc4d8010b4c4e1e74b0ff19bcd4a3a1877fb19741a05a953368db057b",
            "db/contexts/ecl/V1__init_credit_schema.sql,9c9492649f2a28e48f494cb8cc6a0c946c0ae9d86749718f9a10b318f4ab5f85",
            "db/contexts/ecl/V2__align_credit_runtime_schema.sql,b337a883159f3ed0ea171c66037dc2f2175a687028c0a198c4a25bdd09763714",
            "db/contexts/ecl/V3__add_allowance_summary.sql,3f01102b735069a6e464ba84c59bf5a52f49fe06d4957e7687a118e9b1d927b8"
    })
    void publishedMigrationBytesRemainImmutable(String resource, String expectedSha256)
            throws IOException, NoSuchAlgorithmException {
        byte[] content;
        try (InputStream input = getClass().getClassLoader().getResourceAsStream(resource)) {
            assertThat(input).as(resource).isNotNull();
            content = input.readAllBytes();
        }

        String actualSha256 = HexFormat.of().formatHex(
                MessageDigest.getInstance("SHA-256").digest(content));
        assertThat(actualSha256).as(resource).isEqualTo(expectedSha256);
    }

    private String read(String resource) throws IOException {
        try (InputStream input = getClass().getClassLoader().getResourceAsStream(resource)) {
            assertThat(input).as(resource).isNotNull();
            return new String(input.readAllBytes(), StandardCharsets.UTF_8);
        }
    }
}
