package com.ho.account.migration;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.junit.jupiter.params.provider.ValueSource;

class PostgresqlMigrationResourceTest {

    @Test
    void packagedInternalAuditBaselineUsesPortablePostgresqlSyntax() throws IOException {
        String sql = read("db/contexts/internal-audit/V60__init_internal_audit_schema.sql");

        assertThat(sql)
                .doesNotContain("AUTO_INCREMENT")
                .doesNotContain("DATETIME")
                .doesNotContain("ON UPDATE CURRENT_TIMESTAMP")
                .contains("CREATE TABLE rcm_process")
                .contains("CREATE TABLE operating_evaluation_jpa_entity_evidence_file_paths");
    }

    @ParameterizedTest
    @ValueSource(strings = {
            "db/contexts/account-mart/V6__complete_account_mart_schema.sql",
            "db/contexts/asset-lease/V20__init_asset_lease.sql",
            "db/contexts/closing/V49__closing_clean_baseline.sql",
            "db/contexts/deposit/V40__init_deposit_schema.sql",
            "db/contexts/ecl/V4__complete_ecl_schema.sql",
            "db/contexts/expenditure-resolution/V1__expenditure_resolution_baseline.sql",
            "db/contexts/journal-ledger/V11__journal_ledger_postgresql_baseline.sql",
            "db/contexts/loan/V30__init_loan_schema.sql",
            "db/contexts/master-data/V6__master_data_postgresql_baseline.sql",
            "db/contexts/payable/V1__payable_baseline.sql",
            "db/contexts/receivable/V1__receivable_baseline.sql",
            "db/contexts/reconciliation/V1__reconciliation_baseline.sql",
            "db/contexts/tax/V1__tax_baseline.sql"
    })
    void packagedPostgresqlVariantsContainNoH2OnlyIdentityOrTimestampSyntax(String resource)
            throws IOException {
        String sql = read(resource);

        assertThat(sql)
                .doesNotContain("AUTO_INCREMENT")
                .doesNotContain("DATETIME")
                .doesNotContain("ON UPDATE CURRENT_TIMESTAMP")
                .contains("GENERATED BY DEFAULT AS IDENTITY");
    }

    /**
     * 게시된 마이그레이션 바이트가 바뀌지 않았는지 확인한다.
     *
     * <p>기대 해시는 <strong>LF 줄바꿈 기준</strong>이다. {@code .gitattributes}가
     * {@code *.sql text eol=lf}로 SQL을 고정하므로 Windows와 Linux 어디서 체크아웃해도
     * 동일한 바이트가 나온다. 이 고정이 없던 시절에는 {@code text=auto}가 Windows에서만
     * CRLF로 변환해, 같은 커밋인데 로컬은 통과하고 CI는 실패했다.</p>
     */
    @ParameterizedTest
    @CsvSource({
            "db/contexts/account-mart/V1__init_mart_schema.sql,f763b2afc3d9cc9ebe037e185a33781dd1df25bface572be17ec546150d83832",
            "db/contexts/account-mart/V2__add_allowance_exposure_snapshot.sql,360f552d2a56ba77302ed9578d52432280ef1e2211a8163ce1aabb887cbb7818",
            "db/contexts/account-mart/V3__add_allowance_audit_logs.sql,536953ba7b8b3386994c04bb72ab4cbd1bd2cae9627cceee4f52714be1d9b46d",
            "db/contexts/account-mart/V4__add_product_master_api_columns.sql,5c2e11dd8833cd13ec9bb331bb4f06e6d178ad542503f73fb58968a6d7f1c152",
            "db/contexts/account-mart/V5__add_ods_apart_coll_detail.sql,2f1b150d3238daa6ac0b0718003e64f48a562b448767d1e5330d6eca694783ca",
            "db/contexts/ecl/V1__init_credit_schema.sql,4064b758a1b8a7d911e3b9f13786dcbd48187f417cf5ecb95268019a112504c8",
            "db/contexts/ecl/V2__align_credit_runtime_schema.sql,7c869a5bc72313a59193b164ab9634c2ea9a452e873f6214e8d6bbbfbc1add07",
            "db/contexts/ecl/V3__add_allowance_summary.sql,0803615b000d99b28e7ed6706ea37c453d924a4d6817687749f11e0863f13322"
    })
    void publishedMigrationBytesRemainImmutable(String resource, String expectedSha256)
            throws IOException, NoSuchAlgorithmException {
        byte[] content;
        try (InputStream input = getClass().getClassLoader().getResourceAsStream(resource)) {
            assertThat(input).as(resource).isNotNull();
            content = input.readAllBytes();
        }

        String actualSha256 = HexFormat.of().formatHex(
                MessageDigest.getInstance("SHA-256").digest(content));
        assertThat(actualSha256).as(resource).isEqualTo(expectedSha256);
    }

    private String read(String resource) throws IOException {
        try (InputStream input = getClass().getClassLoader().getResourceAsStream(resource)) {
            assertThat(input).as(resource).isNotNull();
            return new String(input.readAllBytes(), StandardCharsets.UTF_8);
        }
    }
}
