plugins {
    id 'java-library'
    id 'io.spring.dependency-management'
}

description = 'account-reconciliation-core'
group = "${rootProject.group}.reconciliation"

base {
    archivesName = 'account-reconciliation-core'
}

dependencies {
    implementation platform('org.springframework.boot:spring-boot-dependencies:3.2.5')
    implementation platform('org.springframework.cloud:spring-cloud-dependencies:2023.0.1')
    testImplementation platform('org.springframework.boot:spring-boot-dependencies:3.2.5')
    testImplementation platform('org.springframework.cloud:spring-cloud-dependencies:2023.0.1')

    implementation project(':shared-kernel')
    implementation project(':contracts')
    implementation project(':master-data')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'


    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
