rootProject.name = 'account'
include 'app', 'contracts', 'shared-kernel', 'master-data', 'governance', 'journal-ledger:core', 'journal-ledger:api', 'journal-ledger:batch', 'closing:core', 'closing:api', 'closing:batch', 'loan:core', 'loan:api', 'loan:batch', 'deposit:core', 'deposit:api', 'deposit:batch', 'reconciliation', 'receivable', 'payable', 'asset-lease', 'tax', 'expenditure-resolution', 'reporting', 'reporting:core', 'reporting:api', 'reporting:batch', 'discovery', 'gateway', 'config-server', 'auth'
