-- H2 Compatible Schema for Credit Risk Service Integration Test

DROP TABLE IF EXISTS cr_risk_results CASCADE;
DROP TABLE IF EXISTS cr_account_collaterals CASCADE;
DROP TABLE IF EXISTS cr_accounts CASCADE;
DROP TABLE IF EXISTS cr_collaterals CASCADE;
DROP TABLE IF EXISTS cr_customers CASCADE;
DROP TABLE IF EXISTS cr_product_masters CASCADE;
DROP TABLE IF EXISTS cr_grade_masters CASCADE;
DROP TABLE IF EXISTS cr_lgd_segment_masters CASCADE;
DROP TABLE IF EXISTS cr_regulatory_parameters CASCADE;
DROP TABLE IF EXISTS cr_batch_audits CASCADE;
DROP TABLE IF EXISTS cr_macro_scenario CASCADE;
DROP TABLE IF EXISTS cr_cust_rating_hist CASCADE;
DROP TABLE IF EXISTS cr_sa_rw_masters CASCADE;
DROP TABLE IF EXISTS transition_matrix CASCADE;
DROP TABLE IF EXISTS cr_monthly_summaries CASCADE;

-- 1-1. 대손충당금(IFRS9) 차주 마스터 (CrCustomer)
CREATE TABLE cr_customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code VARCHAR(50) NOT NULL UNIQUE,
    customer_name VARCHAR(200) NOT NULL,
    customer_type VARCHAR(30) NOT NULL,
    internal_rating VARCHAR(10),
    external_rating VARCHAR(10),
    industry_code VARCHAR(20),
    country_code VARCHAR(2),
    is_sme BOOLEAN DEFAULT FALSE,
    annual_sales NUMERIC(19,4),
    warning_level VARCHAR(20) DEFAULT 'NORMAL',
    is_active BOOLEAN DEFAULT TRUE,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 1-2. 상품별 리스크 규제 파라미터 (CrProductMaster)
CREATE TABLE cr_product_masters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(20) NOT NULL UNIQUE,
    product_name VARCHAR(200) NOT NULL,
    ccf_rate NUMERIC(5,4) NOT NULL DEFAULT 0,
    standard_rw NUMERIC(5,4) NOT NULL DEFAULT 0,
    description VARCHAR(500),
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 1-3. 대손충당금(IFRS9) 익스포저 원장 (CrAccount)
CREATE TABLE cr_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    account_no VARCHAR(50) NOT NULL UNIQUE,
    product_code VARCHAR(20) NOT NULL,
    outstanding_amt NUMERIC(19,4) NOT NULL DEFAULT 0,
    notional_amt NUMERIC(19,4) NOT NULL DEFAULT 0,
    currency VARCHAR(3) NOT NULL DEFAULT 'KRW',
    open_date DATE NOT NULL,
    maturity_date DATE,
    delinquent_days INTEGER DEFAULT 0,
    original_rating VARCHAR(10),
    internal_rating VARCHAR(10),
    staging VARCHAR(20),
    is_debt_restructured BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    error_message VARCHAR(1000),
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES cr_customers(id)
);

-- 1-4. 대손충당금(IFRS9) 담보 마스터 (CrCollateral)
CREATE TABLE cr_collaterals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    collateral_code VARCHAR(50) NOT NULL UNIQUE,
    collateral_type VARCHAR(30) NOT NULL,
    appraisal_amt NUMERIC(19,4) NOT NULL DEFAULT 0,
    base_haircut NUMERIC(5,4) NOT NULL DEFAULT 0,
    prior_lien_amt NUMERIC(19,4) DEFAULT 0,
    ltv_limit NUMERIC(5,4),
    kb_market_price NUMERIC(19,4),
    district_code VARCHAR(10),
    is_active BOOLEAN DEFAULT TRUE,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES cr_customers(id)
);

-- 1-5. 계좌-담보 매핑 (CrAccountCollateral)
CREATE TABLE cr_account_collaterals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT,
    collateral_id BIGINT,
    allocation_amount NUMERIC(19,4) NOT NULL DEFAULT 0,
    priority INTEGER DEFAULT 1,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES cr_accounts(id),
    FOREIGN KEY (collateral_id) REFERENCES cr_collaterals(id)
);

-- 1-6. 대손충당금(IFRS9) 최종 산출 결과 (CrRiskResult)
CREATE TABLE cr_risk_results (
    id BIGINT NOT NULL,
    base_date DATE NOT NULL,
    account_id BIGINT,
    staging VARCHAR(20) NOT NULL,
    ead NUMERIC(19,4),
    applied_ccf NUMERIC(5,4),
    pd NUMERIC(10,8),
    lgd NUMERIC(10,8),
    expected_loss NUMERIC(19,4),
    unexpected_loss NUMERIC(19,4),
    ecl_boom NUMERIC(19,4),
    ecl_base NUMERIC(19,4),
    ecl_recession NUMERIC(19,4),
    weighted_ecl NUMERIC(19,4),
    k_value NUMERIC(10,8),
    r_value NUMERIC(10,8),
    maturity_adj NUMERIC(10,8),
    ead_star NUMERIC(19,4),
    crm_deduction NUMERIC(19,4),
    applied_rw NUMERIC(5,4),
    rwa_sa NUMERIC(19,4),
    rwa_irb NUMERIC(19,4),
    status VARCHAR(20) NOT NULL,
    error_message VARCHAR(2000),
    calculation_completed_at TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (base_date, id),
    FOREIGN KEY (account_id) REFERENCES cr_accounts(id)
);

-- 2-1. 신용등급 마스터 (CrGradeMaster)
CREATE TABLE cr_grade_masters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_code VARCHAR(10) NOT NULL UNIQUE,
    pd_value NUMERIC(10,8) NOT NULL,
    notch_order INTEGER NOT NULL,
    description VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2-2. LGD 세그먼트 마스터 (CrLgdSegmentMaster)
CREATE TABLE cr_lgd_segment_masters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    segment_name VARCHAR(100) NOT NULL,
    customer_type VARCHAR(30) NOT NULL,
    collateral_type VARCHAR(30) NOT NULL,
    lgd_value NUMERIC(10,8) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(customer_type, collateral_type)
);

-- 2-3. 규제 파라미터 컨피그 (CrRegulatoryParameter)
CREATE TABLE cr_regulatory_parameters (
    param_key VARCHAR(50) PRIMARY KEY,
    param_value NUMERIC(19,8) NOT NULL,
    description VARCHAR(200),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2-4. 배치 감사 원장 (CrBatchAudit)
CREATE TABLE cr_batch_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_date DATE NOT NULL,
    job_name VARCHAR(100) NOT NULL,
    total_count INTEGER DEFAULT 0,
    success_count INTEGER DEFAULT 0,
    fail_count INTEGER DEFAULT 0,
    total_ead NUMERIC(19,4) DEFAULT 0,
    total_rwa NUMERIC(19,4) DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    start_at TIMESTAMP,
    end_at TIMESTAMP
);

-- 2-5. 거시경제 시나리오 마스터 (CrMacroScenario)
CREATE TABLE cr_macro_scenario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apply_year INTEGER NOT NULL,
    scenario_type VARCHAR(20) NOT NULL,
    probability_weight NUMERIC(5,4) NOT NULL,
    pd_adjustment_factor NUMERIC(7,4) NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2-6. 고객 신용등급 변동 이력 (CrCustomerRatingHistory)
CREATE TABLE cr_cust_rating_hist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cust_id BIGINT,
    rating_cd VARCHAR(10) NOT NULL,
    base_dt DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cust_id) REFERENCES cr_customers(id)
);

-- 4-1. SA 위험가중치 마스터 (CrSaRwMaster)
CREATE TABLE cr_sa_rw_masters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_type VARCHAR(30) NOT NULL,
    rating_code VARCHAR(10) NOT NULL,
    risk_weight NUMERIC(5,4) NOT NULL,
    description VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(customer_type, rating_code)
);

-- 5-1. IFRS 9 전이행렬 (TransitionMatrix)
CREATE TABLE transition_matrix (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_date DATE NOT NULL,
    from_rating VARCHAR(10) NOT NULL,
    to_rating VARCHAR(10) NOT NULL,
    probability NUMERIC(10,8) NOT NULL,
    time_horizon INTEGER DEFAULT 1,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- IRB 및 SA 마스터 데이터 삽입
INSERT INTO cr_grade_masters (rating_code, pd_value, notch_order, description) VALUES
('AAA',  0.0001,  1, '최상위 투자등급 (가장 우수)'),
('AA+',  0.0002,  2, '상위 투자등급'),
('AA',   0.0003,  3, '상위 투자등급'),
('AA-',  0.0004,  4, '상위 투자등급'),
('A+',   0.0005,  5, '투자등급'),
('A',    0.0007,  6, '투자등급'),
('A-',   0.0010,  7, '투자등급'),
('BBB+', 0.0015,  8, '중위 투자등급'),
('BBB',  0.0020,  9, '중위 투자등급'),
('BBB-', 0.0030, 10, '중위 투자등급'),
('BB+',  0.0050, 11, '투기등급 (위험 증가)'),
('BB',   0.0100, 12, '투기등급'),
('BB-',  0.0150, 13, '투기등급'),
('B+',   0.0250, 14, '고위험등급'),
('B',    0.0500, 15, '고위험등급'),
('B-',   0.0750, 16, '고위험등급'),
('CCC',  0.1500, 17, '부도위험 (매우 취약)'),
('CC',   0.2500, 18, '부도위험'),
('C',    0.5000, 19, '부도위험 (회수가능성 희박)'),
('D',    1.0000, 20, '부도상태 (Default)');

INSERT INTO cr_lgd_segment_masters (segment_name, customer_type, collateral_type, lgd_value) VALUES
('기업_부동산담보',     'CORPORATE', 'REAL_ESTATE', 0.20),
('기업_무담보',         'CORPORATE', 'UNSECURED',   0.45),
('기업_예금담보',       'CORPORATE', 'CASH',        0.05),
('기업_보증',           'CORPORATE', 'GUARANTEE',   0.35),
('소매_주택담보',       'RETAIL',    'RESIDENTIAL', 0.15),
('소매_무담보',         'RETAIL',    'UNSECURED',   0.75),
('소매_예금담보',       'RETAIL',    'CASH',        0.05),
('중소기업_부동산담보', 'SME',       'REAL_ESTATE', 0.25),
('중소기업_무담보',     'SME',       'UNSECURED',   0.50),
('금융기관_무담보',     'FINANCIAL_INSTITUTION', 'UNSECURED', 0.45);

INSERT INTO cr_regulatory_parameters (param_key, param_value, description) VALUES
('PD_FLOOR',            0.0005,     '부도확률 하한선 (국제 금융 규제: 0.05%)'),
('ASSET_CORR_BASE',     0.12,       '기업 자산상관계수 하한 가중치 (12%)'),
('ASSET_CORR_HIGH',     0.24,       '기업 자산상관계수 상한 가중치 (24%)'),
('RETAIL_CORR_BASE',    0.03,       '소매 자산상관계수 하한 (3%)'),
('RETAIL_CORR_HIGH',    0.16,       '소매 자산상관계수 상한 (16%)'),
('MATURITY_ADJ_CONST',  0.11852,    '만기조정 산식 상수 1'),
('MATURITY_ADJ_CONST2', 0.05478,    '만기조정 산식 상수 2'),
('SME_SIZE_THRESHOLD',  50.0,       'SME 매출액 보정 상한 (50억)'),
('SECURED_LGD_FLOOR',   0.20,       '담보부 LGD 하한 (FIRB: 20%)'),
('UNSECURED_LGD_FLOOR', 0.45,       '무담보 LGD 기준값 (FIRB: 45%)'),
('FI_CORR_MULTIPLIER',  1.25,       '금융기관 상관계수 배수 (국제 금융 규제: 125%)');

INSERT INTO cr_sa_rw_masters (customer_type, rating_code, risk_weight, description) VALUES
('RETAIL', 'ALL', 0.7500, '소매 익스포저 일괄 75%'),
('SME', 'ALL', 0.8500, '중소기업 익스포저 일괄 85%'),
('CORPORATE', 'AAA',  0.2000, '기업 우량등급'),
('CORPORATE', 'AA+',  0.2000, '기업 우량등급'),
('CORPORATE', 'AA',   0.2000, '기업 우량등급'),
('CORPORATE', 'AA-',  0.2000, '기업 우량등급'),
('CORPORATE', 'A+',   0.5000, '기업 양호등급'),
('CORPORATE', 'A',    0.5000, '기업 양호등급'),
('CORPORATE', 'A-',   0.5000, '기업 양호등급'),
('CORPORATE', 'BBB+', 0.7500, '기업 보통등급'),
('CORPORATE', 'BBB',  0.7500, '기업 보통등급'),
('CORPORATE', 'BBB-', 0.7500, '기업 보통등급'),
('CORPORATE', 'BB+',  1.0000, '기업 취약등급'),
('CORPORATE', 'BB',   1.0000, '기업 취약등급'),
('CORPORATE', 'BB-',  1.0000, '기업 취약등급'),
('CORPORATE', 'B+',   1.0000, '기업 취약등급'),
('CORPORATE', 'B',    1.0000, '기업 취약등급'),
('CORPORATE', 'B-',   1.0000, '기업 취약등급'),
('CORPORATE', 'CCC',  1.5000, '기업 고위험등급'),
('CORPORATE', 'CC',   1.5000, '기업 고위험등급'),
('CORPORATE', 'C',    1.5000, '기업 고위험등급'),
('CORPORATE', 'D',    1.5000, '기업 부도등급'),
('CORPORATE', 'UNRATED', 1.0000, '기업 무등급(기본)'),
('FINANCIAL_INSTITUTION', 'AAA',  0.2000, '은행 우량등급'),
('FINANCIAL_INSTITUTION', 'AA+',  0.2000, '은행 우량등급'),
('FINANCIAL_INSTITUTION', 'AA',   0.2000, '은행 우량등급'),
('FINANCIAL_INSTITUTION', 'AA-',  0.2000, '은행 우량등급'),
('FINANCIAL_INSTITUTION', 'A+',   0.3000, '은행 양호등급'),
('FINANCIAL_INSTITUTION', 'A',    0.3000, '은행 양호등급'),
('FINANCIAL_INSTITUTION', 'A-',   0.3000, '은행 양호등급'),
('FINANCIAL_INSTITUTION', 'BBB+', 0.5000, '은행 보통등급'),
('FINANCIAL_INSTITUTION', 'BBB',  0.5000, '은행 보통등급'),
('FINANCIAL_INSTITUTION', 'BBB-', 0.5000, '은행 보통등급'),
('FINANCIAL_INSTITUTION', 'UNRATED', 0.5000, '은행 무등급(기본)'),
('PUBLIC_SECTOR', 'ALL', 0.0000, '공공기관/정부/국책은행 익스포저 무위험');

-- 전이행렬 샘플 데이터 (IFRS 9 ECL용)
INSERT INTO transition_matrix (base_date, from_rating, to_rating, probability, time_horizon) VALUES
('2026-04-15', 'AAA', 'AAA', 0.9500, 1),
('2026-04-15', 'AAA', 'AA+', 0.0400, 1),
('2026-04-15', 'AAA', 'D',   0.0001, 1),
('2026-04-15', 'A+',  'A+',  0.9000, 1),
('2026-04-15', 'A+',  'A',   0.0800, 1),
('2026-04-15', 'A+',  'D',   0.0005, 1);

-- 6-1. 월간 리스크 요약 마트 (Monthly Risk Summary Mart)
CREATE TABLE cr_monthly_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_date DATE NOT NULL,
    product_group VARCHAR(50),
    customer_type VARCHAR(30),
    staging VARCHAR(20),
    total_count INTEGER DEFAULT 0,
    total_ead NUMERIC(19,4) DEFAULT 0,
    total_ead_star NUMERIC(19,4) DEFAULT 0,
    total_rwa_sa NUMERIC(19,4) DEFAULT 0,
    total_rwa_irb NUMERIC(19,4) DEFAULT 0,
    total_expected_loss NUMERIC(19,4) DEFAULT 0,
    avg_pd NUMERIC(10,8),
    avg_lgd NUMERIC(10,8),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
