-- H2 Database Schema for Batch Testing

CREATE TABLE IF NOT EXISTS ods_base_rate (
    rate_cd VARCHAR(20) NOT NULL,
    base_dt DATE NOT NULL,
    rate_val DECIMAL(10,6) NOT NULL,
    PRIMARY KEY (rate_cd, base_dt)
);

CREATE TABLE IF NOT EXISTS ods_biz_day (
    base_dt DATE PRIMARY KEY,
    is_biz_day BOOLEAN DEFAULT TRUE,
    holiday_nm VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS ods_district_code (
    district_cd VARCHAR(10) PRIMARY KEY,
    province_nm VARCHAR(50),
    city_nm VARCHAR(50),
    district_nm VARCHAR(50),
    area_type VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS cr_grade_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade_code VARCHAR(20) NOT NULL UNIQUE,
    grade_name VARCHAR(100) NOT NULL,
    score_min DECIMAL(10,4),
    score_max DECIMAL(10,4),
    pd_value DECIMAL(10,8) NOT NULL,
    sort_order INTEGER NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    description VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

MERGE INTO cr_grade_master (grade_code, grade_name, score_min, score_max, pd_value, sort_order, is_active, description)
KEY (grade_code)
VALUES
('AAA', 'AAA', 95.0000, 100.0000, 0.00010000, 1, TRUE, '최상위 투자등급'),
('AA+', 'AA+', 90.0000, 94.9999, 0.00020000, 2, TRUE, '상위 투자등급'),
('AA', 'AA', 85.0000, 89.9999, 0.00030000, 3, TRUE, '상위 투자등급'),
('AA-', 'AA-', 80.0000, 84.9999, 0.00040000, 4, TRUE, '상위 투자등급'),
('A+', 'A+', 75.0000, 79.9999, 0.00050000, 5, TRUE, '투자등급'),
('A', 'A', 70.0000, 74.9999, 0.00070000, 6, TRUE, '투자등급'),
('A-', 'A-', 65.0000, 69.9999, 0.00100000, 7, TRUE, '투자등급'),
('BBB+', 'BBB+', 60.0000, 64.9999, 0.00150000, 8, TRUE, '중위 투자등급'),
('BBB', 'BBB', 55.0000, 59.9999, 0.00200000, 9, TRUE, '중위 투자등급'),
('BBB-', 'BBB-', 50.0000, 54.9999, 0.00300000, 10, TRUE, '중위 투자등급'),
('NR', '무등급', NULL, NULL, 0.10000000, 99, TRUE, '매핑 실패 또는 미평가');
