spring:
  application:
    name: account-mart-batch
  profiles:
    default: local
  main:
    web-application-type: none
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
    vault:
      enabled: false
  flyway:
    enabled: false
    locations: classpath:db/account-mart-local-migration
    clean-disabled: true
    baseline-on-migrate: false
  batch:
    job:
      enabled: false
  sql:
    init:
      mode: never

eureka:
  client:
    enabled: false

management:
  health:
    redis:
      enabled: false
    vault:
      enabled: false
  tracing:
    enabled: false

logging:
  level:
    com.ho.account.mart: DEBUG

mart:
  batch:
    cdm-load:
      parallel-enabled: false
    bootstrap:
      enabled: false
    demo-seed:
      enabled: false
