CREATE TABLE expenditure_resolutions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resolution_no VARCHAR(20) NOT NULL,
    title VARCHAR(200) NOT NULL,
    resolution_date DATE NOT NULL,
    payment_date DATE NOT NULL,
    dept_code VARCHAR(20),
    payment_account_code VARCHAR(20),
    total_amount NUMERIC(19, 2) NOT NULL,
    status VARCHAR(20),
    rejection_reason VARCHAR(500),
    journal_entry_id BIGINT,
    lease_contract_id BIGINT,
    tax_invoice_id BIGINT,
    created_at TIMESTAMP(6),
    created_by VARCHAR(50),
    CONSTRAINT uk_expenditure_resolution_no UNIQUE (resolution_no),
    CONSTRAINT ck_expenditure_resolution_amount CHECK (total_amount >= 0),
    CONSTRAINT ck_expenditure_resolution_dates CHECK (payment_date >= resolution_date),
    CONSTRAINT ck_expenditure_resolution_status CHECK (
        status IS NULL OR status IN ('DRAFT', 'REQUESTED', 'APPROVED', 'REJECTED'))
);

CREATE TABLE expenditure_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expenditure_resolution_id BIGINT NOT NULL,
    account_code VARCHAR(20) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    business_partner_code VARCHAR(20),
    description VARCHAR(200),
    CONSTRAINT fk_expenditure_detail_resolution
        FOREIGN KEY (expenditure_resolution_id) REFERENCES expenditure_resolutions(id),
    CONSTRAINT ck_expenditure_detail_amount CHECK (amount > 0)
);

CREATE TABLE budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year_month VARCHAR(6) NOT NULL,
    dept_code VARCHAR(50) NOT NULL,
    account_code VARCHAR(50) NOT NULL,
    assigned_amount NUMERIC(19, 2) NOT NULL,
    used_amount NUMERIC(19, 2) NOT NULL,
    CONSTRAINT uk_expenditure_budget_period UNIQUE (year_month, dept_code, account_code),
    CONSTRAINT ck_expenditure_budget_period CHECK (CHAR_LENGTH(year_month) = 6),
    CONSTRAINT ck_expenditure_budget_amounts CHECK (
        assigned_amount >= 0 AND used_amount >= 0 AND used_amount <= assigned_amount)
);

CREATE TABLE ap_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no VARCHAR(20) NOT NULL,
    vendor_code VARCHAR(50) NOT NULL,
    invoice_date DATE NOT NULL,
    due_date DATE NOT NULL,
    currency_code VARCHAR(10) NOT NULL,
    supply_amount NUMERIC(19, 2) NOT NULL,
    tax_amount NUMERIC(19, 2) NOT NULL,
    total_amount NUMERIC(19, 2) NOT NULL,
    remaining_amount NUMERIC(19, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    tax_invoice_id BIGINT,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    audit_user VARCHAR(50),
    CONSTRAINT uk_expenditure_ap_invoice_no UNIQUE (invoice_no),
    CONSTRAINT ck_expenditure_ap_invoice_dates CHECK (due_date >= invoice_date),
    CONSTRAINT ck_expenditure_ap_invoice_amounts CHECK (
        supply_amount >= 0 AND tax_amount >= 0 AND total_amount > 0
        AND total_amount = supply_amount + tax_amount
        AND remaining_amount >= 0 AND remaining_amount <= total_amount),
    CONSTRAINT ck_expenditure_ap_invoice_status CHECK (
        status IN ('OPEN', 'PARTIALLY_PAID', 'PAID', 'CANCELED'))
);

CREATE TABLE ap_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expenditure_resolution_id BIGINT NOT NULL,
    tax_invoice_id BIGINT,
    payment_date TIMESTAMP(6) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    unapplied_amount NUMERIC(19, 2) NOT NULL,
    payment_method VARCHAR(50),
    status VARCHAR(20),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    audit_user VARCHAR(50),
    CONSTRAINT uk_ap_payment_resolution UNIQUE (expenditure_resolution_id),
    CONSTRAINT fk_ap_payment_resolution
        FOREIGN KEY (expenditure_resolution_id) REFERENCES expenditure_resolutions(id),
    CONSTRAINT ck_ap_payment_amounts CHECK (
        amount > 0 AND unapplied_amount >= 0 AND unapplied_amount <= amount),
    CONSTRAINT ck_ap_payment_status CHECK (
        status IS NULL OR status IN ('PENDING', 'COMPLETED', 'FAILED', 'PARTIALLY_APPLIED'))
);

CREATE INDEX idx_expenditure_resolution_date_status
    ON expenditure_resolutions(resolution_date, status);
CREATE INDEX idx_expenditure_resolution_payment_date
    ON expenditure_resolutions(payment_date);
CREATE INDEX idx_expenditure_detail_resolution
    ON expenditure_details(expenditure_resolution_id);
CREATE INDEX idx_expenditure_ap_invoice_vendor_due
    ON ap_invoices(vendor_code, due_date, status);
CREATE INDEX idx_expenditure_ap_payment_date_status
    ON ap_payments(payment_date, status);
