-- H2/PostgreSQL-mode baseline for Account Mart local execution.
-- This creates the final 22-table JPA schema directly and deliberately omits PostgreSQL
-- partition syntax. Production upgrades continue to use mart-api V1-V6.

CREATE TABLE ods_acc_mst (
    subj_cd VARCHAR(20) PRIMARY KEY,
    subj_nm VARCHAR(100) NOT NULL,
    acc_type VARCHAR(20) NOT NULL,
    bs_class VARCHAR(10) NOT NULL,
    is_asset BOOLEAN NOT NULL,
    biz_unit_cd VARCHAR(10),
    created_at TIMESTAMP
);

CREATE TABLE ods_product_mst (
    prod_cd VARCHAR(20) PRIMARY KEY,
    prod_nm VARCHAR(100) NOT NULL,
    prod_category VARCHAR(30),
    asset_liability_type VARCHAR(20),
    is_active BOOLEAN DEFAULT TRUE,
    subj_cd VARCHAR(20),
    default_rate_type VARCHAR(10),
    rate_type VARCHAR(10),
    default_payment_freq INTEGER,
    payment_freq INTEGER,
    is_excluded BOOLEAN DEFAULT FALSE,
    is_off_balance BOOLEAN DEFAULT FALSE,
    default_ccf NUMERIC(5,4),
    created_at TIMESTAMP,
    CONSTRAINT fk_ods_product_subject FOREIGN KEY (subj_cd) REFERENCES ods_acc_mst(subj_cd)
);

CREATE TABLE ods_customer_mst (
    customer_code VARCHAR(50) PRIMARY KEY,
    biz_no VARCHAR(20),
    cust_nm VARCHAR(100) NOT NULL,
    cust_type VARCHAR(20) NOT NULL,
    country_cd VARCHAR(3),
    internal_rating VARCHAR(10),
    rating_cd VARCHAR(10),
    external_rating VARCHAR(10),
    industry_cd VARCHAR(20),
    industry_nm VARCHAR(100),
    is_sme BOOLEAN,
    branch_cd VARCHAR(10),
    credit_status_cd VARCHAR(10)
);

CREATE TABLE ods_acc_ledger (
    acc_no VARCHAR(50) PRIMARY KEY,
    customer_code VARCHAR(50),
    prod_cd VARCHAR(20),
    currency VARCHAR(3),
    outstd_amt NUMERIC(19,4),
    limit_amt NUMERIC(19,4),
    int_rate NUMERIC(10,6),
    base_rate_cd VARCHAR(20),
    spread NUMERIC(10,6),
    next_reset_dt DATE,
    open_dt DATE,
    maturity_dt DATE,
    delinquent_days INTEGER,
    repayment_method VARCHAR(20),
    grace_period INTEGER,
    repayment_freq INTEGER,
    branch_cd VARCHAR(10),
    biz_unit_cd VARCHAR(10),
    is_active BOOLEAN,
    CONSTRAINT fk_ods_acc_ledger_customer FOREIGN KEY (customer_code) REFERENCES ods_customer_mst(customer_code),
    CONSTRAINT fk_ods_acc_ledger_product FOREIGN KEY (prod_cd) REFERENCES ods_product_mst(prod_cd)
);

CREATE TABLE ods_balance_hist (
    base_dt DATE NOT NULL,
    account_no VARCHAR(50) NOT NULL,
    currency VARCHAR(3),
    balance NUMERIC(19,4) NOT NULL,
    CONSTRAINT pk_ods_balance_hist PRIMARY KEY (base_dt, account_no),
    CONSTRAINT fk_ods_balance_hist_account FOREIGN KEY (account_no) REFERENCES ods_acc_ledger(acc_no)
);

CREATE TABLE ods_rate_info (
    acc_no VARCHAR(50) PRIMARY KEY,
    rate_type VARCHAR(10) NOT NULL,
    base_rate_cd VARCHAR(20),
    spread NUMERIC(10,6),
    applied_rate NUMERIC(10,6),
    int_rate_cap NUMERIC(10,6),
    int_rate_floor NUMERIC(10,6),
    ref_index_cd VARCHAR(20),
    payment_freq INTEGER,
    rate_reset_cycle INTEGER,
    last_reset_dt DATE,
    next_reset_dt DATE,
    CONSTRAINT fk_ods_rate_info_account FOREIGN KEY (acc_no) REFERENCES ods_acc_ledger(acc_no)
);

CREATE TABLE ods_coll_mst (
    collateral_no VARCHAR(50) PRIMARY KEY,
    customer_code VARCHAR(50),
    collateral_type VARCHAR(20),
    currency VARCHAR(3),
    appraisal_amount NUMERIC(19,4),
    pledge_amount NUMERIC(19,4),
    appraisal_date DATE,
    is_active BOOLEAN,
    CONSTRAINT fk_ods_coll_mst_customer FOREIGN KEY (customer_code) REFERENCES ods_customer_mst(customer_code)
);

CREATE TABLE ods_apart_coll_detail (
    coll_id VARCHAR(50) PRIMARY KEY,
    district_cd VARCHAR(10),
    kb_market_price NUMERIC(19,4),
    house_type VARCHAR(20),
    exclusive_area NUMERIC(10,2),
    floor_no INTEGER,
    is_speculative_area BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_ods_apart_coll_detail_collateral FOREIGN KEY (coll_id) REFERENCES ods_coll_mst(collateral_no)
);

CREATE TABLE ods_behavioral_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_dt DATE NOT NULL,
    acc_no VARCHAR(50) NOT NULL,
    event_type VARCHAR(20) NOT NULL,
    balance_amt NUMERIC(19,4),
    event_amt NUMERIC(19,4),
    created_at TIMESTAMP
);

CREATE TABLE ods_dq_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_date DATE NOT NULL,
    account_no VARCHAR(50),
    audit_type VARCHAR(30),
    audit_message TEXT,
    severity VARCHAR(10),
    audit_timestamp TIMESTAMP
);

CREATE TABLE ods_early_warning (
    base_dt DATE NOT NULL,
    customer_code VARCHAR(50) NOT NULL,
    warning_level VARCHAR(10),
    warning_reason VARCHAR(255),
    warning_score INTEGER,
    CONSTRAINT pk_ods_early_warning PRIMARY KEY (base_dt, customer_code),
    CONSTRAINT fk_ods_early_warning_customer FOREIGN KEY (customer_code) REFERENCES ods_customer_mst(customer_code)
);

CREATE TABLE ods_general_ledger (
    base_dt DATE NOT NULL,
    gl_code VARCHAR(20) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    branch_cd VARCHAR(10) NOT NULL,
    balance NUMERIC(19,4),
    CONSTRAINT pk_ods_general_ledger PRIMARY KEY (base_dt, gl_code, currency, branch_cd)
);

CREATE TABLE ods_guarantee_mst (
    guarantee_no VARCHAR(50) PRIMARY KEY,
    acc_no VARCHAR(50),
    guarantor_id VARCHAR(50),
    guarantor_name VARCHAR(100),
    guarantee_amt NUMERIC(19,4),
    guarantee_ratio NUMERIC(5,2),
    start_dt DATE,
    end_dt DATE,
    guarantor_rating VARCHAR(10),
    CONSTRAINT fk_ods_guarantee_account FOREIGN KEY (acc_no) REFERENCES ods_acc_ledger(acc_no)
);

CREATE TABLE ods_reconcile_hist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_dt DATE NOT NULL,
    source_system VARCHAR(255),
    target_system VARCHAR(255),
    reconcile_item VARCHAR(255),
    source_amount NUMERIC(19,4),
    target_amount NUMERIC(19,4),
    diff_amount NUMERIC(19,4),
    status VARCHAR(255),
    audit_timestamp TIMESTAMP
);

CREATE TABLE allowance_input_positions (
    base_dt DATE NOT NULL,
    acc_no VARCHAR(50) NOT NULL,
    customer_code VARCHAR(50) NOT NULL,
    customer_name VARCHAR(200),
    cust_type VARCHAR(30),
    is_sme BOOLEAN,
    country_cd VARCHAR(10),
    prod_cd VARCHAR(20),
    prod_category VARCHAR(30),
    currency VARCHAR(3) NOT NULL,
    bs_class VARCHAR(10),
    cur_bal NUMERIC(19,4),
    outstd_amt NUMERIC(19,4),
    limit_amt NUMERIC(19,4),
    market_val NUMERIC(19,4),
    int_rate NUMERIC(10,6),
    coupon_rate NUMERIC(10,6),
    rate_type VARCHAR(10),
    base_rate_cd VARCHAR(20),
    spread NUMERIC(10,6),
    payment_freq INTEGER,
    next_reset_dt DATE,
    open_dt DATE,
    maturity_dt DATE,
    repayment_method VARCHAR(20),
    grace_period INTEGER,
    repayment_freq INTEGER,
    int_rate_floor NUMERIC(10,6),
    int_rate_cap NUMERIC(10,6),
    ref_index_cd VARCHAR(20),
    internal_rating VARCHAR(10),
    external_rating VARCHAR(10),
    industry_cd VARCHAR(20),
    warning_level VARCHAR(20),
    is_debt_restructured BOOLEAN,
    delinquent_days INTEGER,
    staging VARCHAR(20),
    coll_amt NUMERIC(19,4),
    recognized_coll_amt NUMERIC(19,4),
    coll_type VARCHAR(20),
    pd NUMERIC(10,8),
    lgd NUMERIC(10,8),
    expected_loss NUMERIC(19,4),
    branch_cd VARCHAR(10),
    biz_unit_cd VARCHAR(10),
    margin_rate NUMERIC(10,6),
    repricing_freq INTEGER,
    CONSTRAINT pk_allowance_input_positions PRIMARY KEY (base_dt, acc_no)
);

CREATE TABLE allowance_exposure_snapshots (
    base_date DATE NOT NULL,
    exposure_id VARCHAR(80) NOT NULL,
    source_system VARCHAR(30) NOT NULL,
    source_account_no VARCHAR(50) NOT NULL,
    customer_code VARCHAR(50) NOT NULL,
    customer_type VARCHAR(30),
    is_sme BOOLEAN,
    country_code VARCHAR(10),
    industry_code VARCHAR(20),
    product_code VARCHAR(20),
    product_category VARCHAR(30),
    legal_entity_code VARCHAR(20) NOT NULL,
    branch_code VARCHAR(20),
    currency_code VARCHAR(3) NOT NULL,
    outstanding_amount NUMERIC(19,4) NOT NULL,
    undrawn_amount NUMERIC(19,4) NOT NULL,
    interest_rate NUMERIC(10,6),
    effective_interest_rate NUMERIC(10,6),
    open_date DATE,
    maturity_date DATE,
    delinquent_days INTEGER,
    staging VARCHAR(20),
    original_rating VARCHAR(20),
    current_rating VARCHAR(20),
    warning_level VARCHAR(20),
    debt_restructured BOOLEAN NOT NULL,
    collateral_value NUMERIC(19,4) NOT NULL,
    collateral_type VARCHAR(20),
    accounting_account_code VARCHAR(20),
    allowance_account_code VARCHAR(20),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_allowance_exposure_snapshots PRIMARY KEY (base_date, exposure_id)
);

CREATE TABLE allowance_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(100) NOT NULL,
    action_type VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL,
    execution_param TEXT,
    executed_by VARCHAR(100),
    error_message TEXT,
    created_at TIMESTAMP NOT NULL,
    duration_ms BIGINT
);

CREATE TABLE kap_external_ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR(50) NOT NULL,
    eval_agency VARCHAR(50) NOT NULL,
    rating_grade VARCHAR(20) NOT NULL,
    base_date DATE NOT NULL
);

CREATE TABLE market_exchange_rate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_dt DATE NOT NULL,
    base_currency VARCHAR(3) NOT NULL,
    quote_currency VARCHAR(3) NOT NULL,
    base_rate NUMERIC(19,4) NOT NULL,
    bid_rate NUMERIC(19,4),
    ask_rate NUMERIC(19,4),
    change_amt NUMERIC(10,4),
    change_rate NUMERIC(10,4),
    source VARCHAR(50),
    created_at TIMESTAMP,
    CONSTRAINT uq_market_exchange_rate UNIQUE (base_currency, quote_currency, base_dt)
);

CREATE TABLE market_rate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_dt DATE NOT NULL,
    rate_name VARCHAR(50) NOT NULL,
    rate_type VARCHAR(20),
    currency VARCHAR(3),
    tenor_months INTEGER,
    tenor_label VARCHAR(10),
    rate NUMERIC(10,6) NOT NULL,
    change_bp NUMERIC(10,2),
    source VARCHAR(50),
    is_active BOOLEAN,
    created_at TIMESTAMP,
    CONSTRAINT uq_market_rate_repository_key
        UNIQUE NULLS NOT DISTINCT (base_dt, rate_name, tenor_months)
);

CREATE TABLE market_yield_curve (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_dt DATE NOT NULL,
    currency VARCHAR(3),
    curve_name VARCHAR(255),
    description VARCHAR(255),
    is_active BOOLEAN,
    created_at TIMESTAMP,
    CONSTRAINT uq_market_yield_curve_repository_key
        UNIQUE NULLS NOT DISTINCT (curve_name, base_dt)
);

CREATE TABLE market_yield_curve_point (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curve_id BIGINT,
    tenor_label VARCHAR(10),
    tenor_months INTEGER,
    rate NUMERIC(10,6),
    discount_factor NUMERIC(19,12),
    CONSTRAINT fk_market_yield_curve_point_curve FOREIGN KEY (curve_id) REFERENCES market_yield_curve(id),
    CONSTRAINT uq_market_yield_curve_point_repository_key
        UNIQUE NULLS NOT DISTINCT (curve_id, tenor_months)
);

CREATE INDEX idx_ods_product_subject ON ods_product_mst(subj_cd);
CREATE INDEX idx_ods_acc_ledger_customer ON ods_acc_ledger(customer_code);
CREATE INDEX idx_ods_acc_ledger_product ON ods_acc_ledger(prod_cd);
CREATE INDEX idx_ods_balance_account_date ON ods_balance_hist(account_no, base_dt);
CREATE INDEX idx_ods_behavioral_account_date ON ods_behavioral_history(acc_no, base_dt);
CREATE INDEX idx_ods_dq_base_date ON ods_dq_audit(base_date);
CREATE INDEX idx_ods_coll_customer ON ods_coll_mst(customer_code);
CREATE INDEX idx_ods_early_warning_customer_date ON ods_early_warning(customer_code, base_dt);
CREATE INDEX idx_ods_guarantee_account ON ods_guarantee_mst(acc_no);
CREATE INDEX idx_ods_reconcile_base_date ON ods_reconcile_hist(base_dt);
CREATE INDEX idx_allowance_input_acc_no ON allowance_input_positions(acc_no);
CREATE INDEX idx_allowance_exposure_base ON allowance_exposure_snapshots(base_date);
CREATE INDEX idx_allowance_exposure_customer ON allowance_exposure_snapshots(customer_code);
CREATE INDEX idx_allowance_exposure_product_currency ON allowance_exposure_snapshots(product_code, currency_code);
CREATE INDEX idx_allowance_audit_logs_created_at ON allowance_audit_logs(created_at);
CREATE INDEX idx_allowance_audit_logs_service_name ON allowance_audit_logs(service_name, created_at);
CREATE INDEX idx_kap_external_rating_customer_date ON kap_external_ratings(customer_id, base_date);
CREATE INDEX idx_market_exchange_rate_base_date ON market_exchange_rate(base_dt);
CREATE INDEX idx_market_rate_base_active ON market_rate(base_dt, is_active);
CREATE INDEX idx_market_rate_name_tenor_date ON market_rate(rate_name, tenor_months, base_dt);
CREATE INDEX idx_market_yield_curve_base_date ON market_yield_curve(base_dt);
CREATE INDEX idx_market_yield_curve_currency ON market_yield_curve(currency);
CREATE INDEX idx_market_yield_curve_point_curve ON market_yield_curve_point(curve_id);
