-- Converge the published V1-V5 schema to the 22 tables mapped by Account Mart.
-- Legacy columns whose meaning is not identical to a mapped attribute are retained.

-- Canonical table and unambiguous column names.
ALTER TABLE ods_account_mst RENAME TO ods_acc_mst;
ALTER TABLE ods_acc_mst RENAME COLUMN acct_type TO acc_type;

ALTER TABLE ods_collateral_mst RENAME TO ods_coll_mst;
ALTER TABLE ods_coll_mst RENAME COLUMN coll_id TO collateral_no;
ALTER TABLE ods_coll_mst RENAME COLUMN coll_type TO collateral_type;
ALTER TABLE ods_coll_mst RENAME COLUMN appraisal_dt TO appraisal_date;

ALTER TABLE ods_balance_hist RENAME COLUMN acc_no TO account_no;
ALTER TABLE ods_balance_hist RENAME COLUMN cur_bal TO balance;

ALTER TABLE ods_dq_audit RENAME COLUMN base_dt TO base_date;
ALTER TABLE ods_dq_audit RENAME COLUMN acc_no TO account_no;

-- Columns already mapped by JPA but absent from the published migrations.
ALTER TABLE ods_acc_mst
    ADD COLUMN created_at TIMESTAMP;

ALTER TABLE ods_product_mst
    ADD COLUMN rate_type VARCHAR(10),
    ADD COLUMN payment_freq INTEGER,
    ADD COLUMN is_excluded BOOLEAN DEFAULT FALSE,
    ADD COLUMN created_at TIMESTAMP;

ALTER TABLE ods_customer_mst
    ADD COLUMN rating_cd VARCHAR(10);

ALTER TABLE ods_balance_hist
    ADD COLUMN currency VARCHAR(3);

-- acc_no, coll_detail, coll_amt, pledge_rate, recognized_amt, and expiry_dt are retained because
-- they cannot be losslessly reinterpreted as the canonical customer/currency/amount flags.
ALTER TABLE ods_coll_mst
    ADD COLUMN customer_code VARCHAR(50),
    ADD COLUMN currency VARCHAR(3),
    ADD COLUMN appraisal_amount NUMERIC(19,4),
    ADD COLUMN pledge_amount NUMERIC(19,4),
    ADD COLUMN is_active BOOLEAN;

-- table_name/error_type/error_msg/created_at are retained as legacy audit evidence.
ALTER TABLE ods_dq_audit
    ADD COLUMN audit_type VARCHAR(30),
    ADD COLUMN audit_message TEXT,
    ADD COLUMN audit_timestamp TIMESTAMP;

ALTER TABLE allowance_input_positions
    ALTER COLUMN cust_type TYPE VARCHAR(30),
    ADD COLUMN margin_rate NUMERIC(10,6),
    ADD COLUMN repricing_freq INTEGER;

-- Catch every future date without requiring an emergency monthly DDL deployment.
CREATE TABLE ods_balance_hist_default
    PARTITION OF ods_balance_hist DEFAULT;

CREATE TABLE allowance_input_positions_default
    PARTITION OF allowance_input_positions DEFAULT;

-- ODS audit and reference tables missing from V1-V5.
CREATE TABLE ods_early_warning (
    base_dt DATE NOT NULL,
    customer_code VARCHAR(50) NOT NULL,
    warning_level VARCHAR(10),
    warning_reason VARCHAR(255),
    warning_score INTEGER,
    CONSTRAINT pk_ods_early_warning PRIMARY KEY (base_dt, customer_code),
    CONSTRAINT fk_ods_early_warning_customer
        FOREIGN KEY (customer_code) REFERENCES ods_customer_mst(customer_code)
);

CREATE TABLE ods_general_ledger (
    base_dt DATE NOT NULL,
    gl_code VARCHAR(20) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    branch_cd VARCHAR(10) NOT NULL,
    balance NUMERIC(19,4),
    CONSTRAINT pk_ods_general_ledger PRIMARY KEY (base_dt, gl_code, currency, branch_cd)
);

CREATE TABLE ods_guarantee_mst (
    guarantee_no VARCHAR(50) PRIMARY KEY,
    acc_no VARCHAR(50),
    guarantor_id VARCHAR(50),
    guarantor_name VARCHAR(100),
    guarantee_amt NUMERIC(19,4),
    guarantee_ratio NUMERIC(5,2),
    start_dt DATE,
    end_dt DATE,
    guarantor_rating VARCHAR(10),
    CONSTRAINT fk_ods_guarantee_account
        FOREIGN KEY (acc_no) REFERENCES ods_acc_ledger(acc_no)
);

CREATE TABLE ods_reconcile_hist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_dt DATE NOT NULL,
    source_system VARCHAR(255),
    target_system VARCHAR(255),
    reconcile_item VARCHAR(255),
    source_amount NUMERIC(19,4),
    target_amount NUMERIC(19,4),
    diff_amount NUMERIC(19,4),
    status VARCHAR(255),
    audit_timestamp TIMESTAMP
);

-- KAP external rating input.
CREATE TABLE kap_external_ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR(50) NOT NULL,
    eval_agency VARCHAR(50) NOT NULL,
    rating_grade VARCHAR(20) NOT NULL,
    base_date DATE NOT NULL
);

-- Market data tables. Natural keys used by Optional-returning repositories are unique.
CREATE TABLE market_exchange_rate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_dt DATE NOT NULL,
    base_currency VARCHAR(3) NOT NULL,
    quote_currency VARCHAR(3) NOT NULL,
    base_rate NUMERIC(19,4) NOT NULL,
    bid_rate NUMERIC(19,4),
    ask_rate NUMERIC(19,4),
    change_amt NUMERIC(10,4),
    change_rate NUMERIC(10,4),
    source VARCHAR(50),
    created_at TIMESTAMP,
    CONSTRAINT uq_market_exchange_rate
        UNIQUE (base_currency, quote_currency, base_dt)
);

CREATE TABLE market_rate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_dt DATE NOT NULL,
    rate_name VARCHAR(50) NOT NULL,
    rate_type VARCHAR(20),
    currency VARCHAR(3),
    tenor_months INTEGER,
    tenor_label VARCHAR(10),
    rate NUMERIC(10,6) NOT NULL,
    change_bp NUMERIC(10,2),
    source VARCHAR(50),
    is_active BOOLEAN,
    created_at TIMESTAMP,
    CONSTRAINT uq_market_rate_repository_key
        UNIQUE NULLS NOT DISTINCT (base_dt, rate_name, tenor_months)
);

CREATE TABLE market_yield_curve (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_dt DATE NOT NULL,
    currency VARCHAR(3),
    curve_name VARCHAR(255),
    description VARCHAR(255),
    is_active BOOLEAN,
    created_at TIMESTAMP,
    CONSTRAINT uq_market_yield_curve_repository_key
        UNIQUE NULLS NOT DISTINCT (curve_name, base_dt)
);

CREATE TABLE market_yield_curve_point (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curve_id BIGINT,
    tenor_label VARCHAR(10),
    tenor_months INTEGER,
    rate NUMERIC(10,6),
    discount_factor NUMERIC(19,12),
    CONSTRAINT fk_market_yield_curve_point_curve
        FOREIGN KEY (curve_id) REFERENCES market_yield_curve(id),
    CONSTRAINT uq_market_yield_curve_point_repository_key
        UNIQUE NULLS NOT DISTINCT (curve_id, tenor_months)
);

-- Relational integrity for canonical ODS identifiers. Existing rows are retained; the
-- partitioned balance history FK is validated because PostgreSQL does not support a
-- NOT VALID foreign key on a partitioned parent.
DO $$
DECLARE
    orphan_count BIGINT;
BEGIN
    SELECT COUNT(*)
      INTO orphan_count
      FROM ods_balance_hist history
      LEFT JOIN ods_acc_ledger ledger ON ledger.acc_no = history.account_no
     WHERE ledger.acc_no IS NULL;

    IF orphan_count > 0 THEN
        RAISE EXCEPTION
            'Cannot add ods_balance_hist account FK: % orphan history rows exist',
            orphan_count
            USING HINT =
                'Load the matching ods_acc_ledger accounts or remove invalid history through an approved data repair, then rerun Flyway.';
    END IF;
END
$$;

ALTER TABLE ods_balance_hist
    ADD CONSTRAINT fk_ods_balance_hist_account
    FOREIGN KEY (account_no) REFERENCES ods_acc_ledger(acc_no);

ALTER TABLE ods_rate_info
    ADD CONSTRAINT fk_ods_rate_info_account
    FOREIGN KEY (acc_no) REFERENCES ods_acc_ledger(acc_no) NOT VALID;

ALTER TABLE ods_coll_mst
    ADD CONSTRAINT fk_ods_coll_mst_customer
    FOREIGN KEY (customer_code) REFERENCES ods_customer_mst(customer_code) NOT VALID;

ALTER TABLE ods_apart_coll_detail
    ADD CONSTRAINT fk_ods_apart_coll_detail_collateral
    FOREIGN KEY (coll_id) REFERENCES ods_coll_mst(collateral_no) NOT VALID;

-- Repository access paths and foreign-key support indexes.
CREATE INDEX idx_ods_product_subject
    ON ods_product_mst(subj_cd);
CREATE INDEX idx_ods_acc_ledger_customer
    ON ods_acc_ledger(customer_code);
CREATE INDEX idx_ods_acc_ledger_product
    ON ods_acc_ledger(prod_cd);
CREATE INDEX idx_ods_balance_account_date
    ON ods_balance_hist(account_no, base_dt DESC);
CREATE INDEX idx_ods_behavioral_account_date
    ON ods_behavioral_history(acc_no, base_dt);
CREATE INDEX idx_ods_coll_customer
    ON ods_coll_mst(customer_code);
CREATE INDEX idx_ods_early_warning_customer_date
    ON ods_early_warning(customer_code, base_dt DESC);
CREATE INDEX idx_ods_guarantee_account
    ON ods_guarantee_mst(acc_no);
CREATE INDEX idx_ods_reconcile_base_date
    ON ods_reconcile_hist(base_dt);

CREATE INDEX idx_kap_external_rating_customer_date
    ON kap_external_ratings(customer_id, base_date DESC);

CREATE INDEX idx_market_exchange_rate_base_date
    ON market_exchange_rate(base_dt);
CREATE INDEX idx_market_rate_base_active
    ON market_rate(base_dt, is_active);
CREATE INDEX idx_market_rate_name_tenor_date
    ON market_rate(rate_name, tenor_months, base_dt);
CREATE INDEX idx_market_yield_curve_base_date
    ON market_yield_curve(base_dt);
CREATE INDEX idx_market_yield_curve_currency
    ON market_yield_curve(currency);
CREATE INDEX idx_market_yield_curve_point_curve
    ON market_yield_curve_point(curve_id);
