spring:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
    vault:
      enabled: false
  datasource:
    url: jdbc:h2:mem:master-data-api;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  batch:
    jdbc:
      initialize-schema: never
  sql:
    init:
      mode: always
      data-locations: classpath:data-local.sql

eureka:
  client:
    enabled: false
