server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: master-data
  profiles:
    default: local
  flyway:
    enabled: false
    locations: classpath:db/migration
    clean-disabled: true
    baseline-on-migrate: false

management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,db
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
