package com.ho.account.ecl.core.infrastructure.adapter.persistence;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.math.BigDecimal;
import java.sql.Date;
import java.time.LocalDate;

import static org.assertj.core.api.Assertions.assertThat;

class JdbcAllowanceExposureSyncAdapterTest {

    private static final LocalDate BASE_DATE = LocalDate.of(2026, 4, 30);

    private JdbcTemplate jdbcTemplate;
    private JdbcAllowanceExposureSyncAdapter adapter;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:allowance_sync_adapter;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                "sa",
                "");
        dataSource.setDriverClassName("org.h2.Driver");
        jdbcTemplate = new JdbcTemplate(dataSource);
        adapter = new JdbcAllowanceExposureSyncAdapter(jdbcTemplate);

        createSchema();
        insertSnapshot("EXP-1", "ACC-1", "CUST-1", "LOAN-A", new BigDecimal("1000.00"), new BigDecimal("200.00"));
        insertSnapshot("EXP-2", "ACC-2", "CUST-1", "LOAN-A", new BigDecimal("3000.00"), BigDecimal.ZERO);
    }

    @AfterEach
    void tearDown() {
        jdbcTemplate.execute("DROP ALL OBJECTS");
    }

    @Test
    void upsertCustomersAndAccountsFromSnapshot_supportsH2Merge() {
        assertThat(adapter.countSourceSnapshots(BASE_DATE)).isEqualTo(2);

        int customerRows = adapter.upsertCustomersFromSnapshot(BASE_DATE);
        int accountRows = adapter.upsertAccountsFromSnapshot(BASE_DATE);

        assertThat(customerRows).isEqualTo(1);
        assertThat(accountRows).isEqualTo(2);
        assertThat(countRows("cr_customers")).isEqualTo(1);
        assertThat(countRows("cr_accounts")).isEqualTo(2);

        BigDecimal notionalAmount = jdbcTemplate.queryForObject(
                "SELECT notional_amt FROM cr_accounts WHERE account_no = 'ACC-1'",
                BigDecimal.class);
        assertThat(notionalAmount).isEqualByComparingTo(new BigDecimal("1200.0000"));
    }

    @Test
    void upsertCustomersAndAccountsFromSnapshot_isIdempotentForSameBaseDate() {
        adapter.upsertCustomersFromSnapshot(BASE_DATE);
        adapter.upsertAccountsFromSnapshot(BASE_DATE);

        jdbcTemplate.update("""
                UPDATE allowance_exposure_snapshots
                   SET outstanding_amount = ?
                 WHERE base_date = ? AND exposure_id = ?
                """,
                new BigDecimal("1500.00"),
                Date.valueOf(BASE_DATE),
                "EXP-1");

        adapter.upsertCustomersFromSnapshot(BASE_DATE);
        adapter.upsertAccountsFromSnapshot(BASE_DATE);

        assertThat(countRows("cr_accounts")).isEqualTo(2);
        BigDecimal notionalAmount = jdbcTemplate.queryForObject(
                "SELECT notional_amt FROM cr_accounts WHERE account_no = 'ACC-1'",
                BigDecimal.class);
        assertThat(notionalAmount).isEqualByComparingTo(new BigDecimal("1700.0000"));
    }

    private void createSchema() {
        jdbcTemplate.execute("""
                CREATE TABLE allowance_exposure_snapshots (
                    base_date DATE NOT NULL,
                    exposure_id VARCHAR(80) NOT NULL,
                    source_account_no VARCHAR(50) NOT NULL,
                    customer_code VARCHAR(50) NOT NULL,
                    customer_type VARCHAR(30),
                    is_sme BOOLEAN,
                    country_code VARCHAR(10),
                    industry_code VARCHAR(20),
                    product_code VARCHAR(20),
                    product_category VARCHAR(30),
                    legal_entity_code VARCHAR(20),
                    branch_code VARCHAR(20),
                    currency_code VARCHAR(3),
                    outstanding_amount NUMERIC(19,4),
                    undrawn_amount NUMERIC(19,4),
                    interest_rate NUMERIC(10,6),
                    open_date DATE,
                    maturity_date DATE,
                    delinquent_days INTEGER,
                    staging VARCHAR(20),
                    original_rating VARCHAR(20),
                    current_rating VARCHAR(20),
                    warning_level VARCHAR(20),
                    debt_restructured BOOLEAN,
                    PRIMARY KEY (base_date, exposure_id)
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE cr_customers (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_code VARCHAR(50) NOT NULL UNIQUE,
                    customer_name VARCHAR(200) NOT NULL,
                    customer_type VARCHAR(30) NOT NULL,
                    internal_rating VARCHAR(20),
                    industry_code VARCHAR(20),
                    country_code VARCHAR(10),
                    is_sme BOOLEAN,
                    warning_level VARCHAR(20),
                    is_active BOOLEAN,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE cr_accounts (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    account_no VARCHAR(50) NOT NULL UNIQUE,
                    customer_id BIGINT NOT NULL,
                    product_code VARCHAR(20),
                    currency VARCHAR(3),
                    notional_amt NUMERIC(19,4),
                    outstanding_amt NUMERIC(19,4),
                    prod_category VARCHAR(30),
                    int_rate NUMERIC(10,6),
                    branch_cd VARCHAR(20),
                    biz_unit_cd VARCHAR(20),
                    staging VARCHAR(20),
                    delinquent_days INTEGER,
                    open_date DATE,
                    maturity_date DATE,
                    original_rating VARCHAR(20),
                    internal_rating VARCHAR(20),
                    is_debt_restructured BOOLEAN,
                    is_active BOOLEAN,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP
                )
                """);
    }

    private void insertSnapshot(
            String exposureId,
            String accountNo,
            String customerCode,
            String productCode,
            BigDecimal outstandingAmount,
            BigDecimal undrawnAmount) {

        jdbcTemplate.update("""
                INSERT INTO allowance_exposure_snapshots (
                    base_date, exposure_id, source_account_no, customer_code, customer_type,
                    is_sme, country_code, industry_code, product_code, product_category,
                    legal_entity_code, branch_code, currency_code, outstanding_amount,
                    undrawn_amount, interest_rate, open_date, maturity_date, delinquent_days,
                    staging, original_rating, current_rating, warning_level, debt_restructured
                ) VALUES (?, ?, ?, ?, 'CORPORATE', FALSE, 'KR', 'FIN', ?, 'LOAN',
                          'LE-1', 'BR-1', 'KRW', ?, ?, 0.045000, ?, ?, 0,
                          'STAGE1', 'A', 'A', 'NORMAL', FALSE)
                """,
                Date.valueOf(BASE_DATE),
                exposureId,
                accountNo,
                customerCode,
                productCode,
                outstandingAmount,
                undrawnAmount,
                Date.valueOf(LocalDate.of(2025, 1, 1)),
                Date.valueOf(LocalDate.of(2027, 1, 1)));
    }

    private Integer countRows(String tableName) {
        return jdbcTemplate.queryForObject("SELECT COUNT(*) FROM " + tableName, Integer.class);
    }
}
