CREATE TABLE tax_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id VARCHAR(30) NOT NULL,
    type VARCHAR(255) NOT NULL,
    issue_date DATE NOT NULL,
    business_partner_code VARCHAR(20) NOT NULL,
    supply_amount NUMERIC(19, 2) NOT NULL,
    tax_amount NUMERIC(19, 2) NOT NULL,
    total_amount NUMERIC(19, 2) NOT NULL,
    journal_entry_id BIGINT,
    status VARCHAR(20) NOT NULL,
    cancelled_by VARCHAR(50),
    cancellation_reason VARCHAR(500),
    cancelled_at TIMESTAMP(6),
    CONSTRAINT uk_tax_invoice_issue_id UNIQUE (issue_id),
    CONSTRAINT ck_tax_invoice_type CHECK (type IN ('SALES', 'PURCHASE')),
    CONSTRAINT ck_tax_invoice_amounts CHECK (
        supply_amount >= 0 AND tax_amount >= 0 AND total_amount >= 0
        AND total_amount = supply_amount + tax_amount),
    CONSTRAINT ck_tax_invoice_journal_id CHECK (
        journal_entry_id IS NULL OR journal_entry_id > 0),
    CONSTRAINT ck_tax_invoice_lifecycle CHECK (
        (status = 'ACTIVE'
            AND cancelled_by IS NULL
            AND cancellation_reason IS NULL
            AND cancelled_at IS NULL)
        OR (status = 'CANCELLED'
            AND cancelled_by IS NOT NULL
            AND CHAR_LENGTH(TRIM(cancelled_by)) > 0
            AND cancellation_reason IS NOT NULL
            AND CHAR_LENGTH(TRIM(cancellation_reason)) > 0
            AND cancelled_at IS NOT NULL))
);

CREATE INDEX idx_tax_invoice_issue_date
    ON tax_invoices(issue_date);
CREATE INDEX idx_tax_invoice_partner_date_status
    ON tax_invoices(business_partner_code, issue_date, status);

