global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'minimal-auth'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['minimal-auth:8084']

  - job_name: 'minimal-master-data'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['minimal-master-data:8082']

  - job_name: 'minimal-discovery'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['minimal-discovery:8761']

  - job_name: 'minimal-config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['minimal-config-server:8888']

  - job_name: 'minimal-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['minimal-gateway:8000']
