-- PostgreSQL variant of the published H2 V20 migration.

CREATE TABLE fixed_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_code VARCHAR(20) NOT NULL UNIQUE,
    asset_name VARCHAR(100) NOT NULL,
    account_code VARCHAR(20) NOT NULL,
    accumulated_account_code VARCHAR(20),
    expense_account_code VARCHAR(20),
    dept_code VARCHAR(20),
    acquisition_date DATE NOT NULL,
    acquisition_cost DECIMAL(19, 2) NOT NULL,
    useful_life INT NOT NULL,
    depreciation_method VARCHAR(20),
    residual_value DECIMAL(19, 2) DEFAULT 0,
    accumulated_depreciation DECIMAL(19, 2) DEFAULT 0,
    accumulated_impairment DECIMAL(19, 2) DEFAULT 0,
    revaluation_surplus DECIMAL(19, 2) DEFAULT 0,
    current_book_value DECIMAL(19, 2) NOT NULL,
    depreciation_amount_per_period DECIMAL(19, 2),
    last_depreciation_date DATE,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE asset_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    history_type VARCHAR(50) NOT NULL,
    old_dept_code VARCHAR(20),
    new_dept_code VARCHAR(20),
    old_status VARCHAR(20),
    new_status VARCHAR(20),
    description TEXT,
    event_at TIMESTAMP NOT NULL,
    audit_user VARCHAR(50) NOT NULL,
    FOREIGN KEY (asset_id) REFERENCES fixed_assets(id)
);

CREATE TABLE lease_contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_no VARCHAR(50) NOT NULL UNIQUE,
    contract_name VARCHAR(100) NOT NULL,
    lessor_code VARCHAR(20),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    monthly_payment DECIMAL(19, 2) NOT NULL,
    discount_rate DECIMAL(5, 2) NOT NULL,
    initial_rou_value DECIMAL(19, 2),
    initial_lease_liability_value DECIMAL(19, 2),
    status VARCHAR(20),
    dept_code VARCHAR(20),
    ifrs16_applicable BOOLEAN DEFAULT TRUE
);

CREATE TABLE lease_payment_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    payment_date DATE NOT NULL,
    scheduled_payment_amount DECIMAL(19, 2),
    interest_portion DECIMAL(19, 2),
    principal_portion DECIMAL(19, 2),
    remaining_lease_liability DECIMAL(19, 2),
    status VARCHAR(20),
    FOREIGN KEY (contract_id) REFERENCES lease_contracts(id)
);
