-- PostgreSQL clean baseline for the Asset Lease bounded context.
-- The published H2 V20 remains checksum-stable in db/migration.

CREATE TABLE fixed_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_code VARCHAR(255) NOT NULL UNIQUE,
    asset_name VARCHAR(255) NOT NULL,
    account_code VARCHAR(20) NOT NULL,
    accumulated_account_code VARCHAR(20),
    expense_account_code VARCHAR(20),
    dept_code VARCHAR(20),
    acquisition_date DATE NOT NULL,
    acquisition_cost DECIMAL(19, 2) NOT NULL,
    useful_life INTEGER NOT NULL,
    depreciation_method VARCHAR(255),
    residual_value DECIMAL(19, 2),
    accumulated_depreciation DECIMAL(19, 2),
    current_book_value DECIMAL(19, 2) NOT NULL,
    depreciation_amount_per_period DECIMAL(19, 2),
    last_depreciation_date DATE,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX idx_fixed_asset_status ON fixed_assets(status);

CREATE TABLE asset_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    history_type VARCHAR(50) NOT NULL,
    old_dept_code VARCHAR(20),
    new_dept_code VARCHAR(20),
    old_status VARCHAR(20),
    new_status VARCHAR(20),
    description VARCHAR(255),
    event_at TIMESTAMP NOT NULL,
    audit_user VARCHAR(50) NOT NULL,
    CONSTRAINT fk_asset_history_asset FOREIGN KEY (asset_id) REFERENCES fixed_assets(id)
);

CREATE INDEX idx_asset_history_asset ON asset_histories(asset_id);

CREATE TABLE lease_contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_no VARCHAR(255) NOT NULL UNIQUE,
    contract_name VARCHAR(255) NOT NULL,
    lessor_code VARCHAR(20),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    monthly_payment DECIMAL(19, 2) NOT NULL,
    payment_day INTEGER NOT NULL,
    discount_rate DECIMAL(7, 4) NOT NULL,
    initial_right_of_use_asset_value DECIMAL(19, 2),
    initial_lease_liability_value DECIMAL(19, 2),
    status VARCHAR(255),
    dept_code VARCHAR(20),
    expense_account_code VARCHAR(20),
    ifrs16_applicable BOOLEAN NOT NULL,
    short_term_lease BOOLEAN NOT NULL,
    low_value_lease BOOLEAN NOT NULL,
    CONSTRAINT ck_lease_contract_dates CHECK (start_date <= end_date),
    CONSTRAINT ck_lease_contract_payment_day CHECK (payment_day BETWEEN 1 AND 31)
);

CREATE TABLE right_of_use_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lease_contract_id BIGINT NOT NULL UNIQUE,
    asset_name VARCHAR(100) NOT NULL,
    recognition_date DATE NOT NULL,
    initial_value DECIMAL(19, 2) NOT NULL,
    current_book_value DECIMAL(19, 2) NOT NULL,
    accumulated_depreciation DECIMAL(19, 2) NOT NULL,
    depreciation_amount_per_period DECIMAL(19, 2) NOT NULL,
    status VARCHAR(20),
    created_at TIMESTAMP,
    CONSTRAINT fk_rou_asset_contract FOREIGN KEY (lease_contract_id) REFERENCES lease_contracts(id)
);

CREATE TABLE lease_liabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lease_contract_id BIGINT NOT NULL UNIQUE,
    recognition_date DATE NOT NULL,
    initial_value DECIMAL(19, 2) NOT NULL,
    current_value DECIMAL(19, 2) NOT NULL,
    accumulated_interest_expense DECIMAL(19, 2) NOT NULL,
    status VARCHAR(20),
    created_at TIMESTAMP,
    CONSTRAINT fk_lease_liability_contract FOREIGN KEY (lease_contract_id) REFERENCES lease_contracts(id)
);

CREATE TABLE lease_payment_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lease_contract_id BIGINT NOT NULL,
    payment_date DATE NOT NULL,
    scheduled_payment_amount DECIMAL(19, 2) NOT NULL,
    actual_payment_amount DECIMAL(19, 2),
    interest_portion DECIMAL(19, 2) NOT NULL,
    principal_portion DECIMAL(19, 2) NOT NULL,
    remaining_lease_liability DECIMAL(19, 2) NOT NULL,
    status VARCHAR(20),
    created_at TIMESTAMP,
    CONSTRAINT fk_lease_schedule_contract FOREIGN KEY (lease_contract_id) REFERENCES lease_contracts(id)
);

CREATE INDEX idx_lease_schedule_contract ON lease_payment_schedules(lease_contract_id);
