plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

description = 'account-tax-api'
group = "${rootProject.group}.tax"

base {
    archivesName = 'account-tax-api'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:2023.0.1"
    }
}

dependencies {
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    implementation project(':tax:core')
    implementation project(':shared-kernel')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.flywaydb:flyway-core'
    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

sourceSets.test.java.srcDir rootProject.file('test-support/runtime-contracts/src/test/java')

bootJar { enabled = true }
jar {
    enabled = true
    archiveClassifier = 'plain'
}

springBoot {
    mainClass = 'com.ho.account.tax.api.TaxApiApplication'
}

bootRun {
    systemProperty 'spring.profiles.active', System.getProperty('spring.profiles.active', 'local')
}
