CREATE TABLE IF NOT EXISTS auth_users (
    username VARCHAR(80) PRIMARY KEY,
    stored_password VARCHAR(255) NOT NULL,
    department_code VARCHAR(40),
    account_active BOOLEAN NOT NULL,
    account_locked BOOLEAN NOT NULL,
    role_version BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auth_role_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL,
    role_code VARCHAR(80) NOT NULL,
    data_scope VARCHAR(80) NOT NULL,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    approved BOOLEAN NOT NULL,
    approved_by VARCHAR(80),
    approved_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auth_role_assignments_user
        FOREIGN KEY (username) REFERENCES auth_users(username)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_auth_role_assignments_user_effective
    ON auth_role_assignments (username, approved, valid_from, valid_to);

CREATE INDEX IF NOT EXISTS idx_auth_role_assignments_role
    ON auth_role_assignments (role_code, username);
