ALTER TABLE transition_matrix ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE transition_matrix ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE cr_product_masters ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE cr_product_masters ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE cr_accounts ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE cr_accounts ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE cr_customers ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE cr_customers ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE cr_account_collaterals ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE cr_account_collaterals ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE cr_collaterals ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE cr_collaterals ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE cr_risk_results ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE cr_risk_results ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE cr_monthly_summaries ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE cr_monthly_summaries ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);