"""Relational guard tests, with no PostgreSQL connection or filesystem database.

Use the actual migration/seed SQL and rollback predicates/deletes in SQLite.
Only identity declarations and typed literals are adapted. This checks data
preservation and guard ordering, not PostgreSQL DO syntax or lock semantics.
"""
from pathlib import Path
import re
import sqlite3
import unittest


ROOT = Path(__file__).resolve().parents[3]
SEEDS = ROOT / "tools/seeds"
PACKAGES = {
    "accounting/expenditure": ["expenditure-resolution/core/src/main/resources/db/expenditure-resolution-migration/V1__expenditure_resolution_baseline.sql"],
    "accounting/payable": ["payable/core/src/main/resources/db/payable-migration/V1__payable_baseline.sql"],
    "accounting/receivable": ["receivable/core/src/main/resources/db/receivable-migration/V1__receivable_baseline.sql"],
    "products/deposit": [
        "deposit/core/src/main/resources/db/postgresql-migration/V40__init_deposit_schema.sql",
        "deposit/core/src/main/resources/db/postgresql-migration/V42__create_deposit_outbox_table.sql"],
    "products/loan": ["loan/core/src/main/resources/db/postgresql-migration/V30__init_loan_schema.sql"],
    "products/asset-lease": ["asset-lease/core/src/main/resources/db/postgresql-migration/V20__init_asset_lease.sql"],
}


def sqlite_sql(sql):
    sql = re.sub(r"--[^\n]*", "", sql)
    sql = sql.replace("BIGINT GENERATED BY DEFAULT AS IDENTITY", "INTEGER")
    sql = sql.replace("BIGSERIAL", "INTEGER")
    return re.sub(r"\b(?:DATE|TIMESTAMP)\s+('[^']*')", r"\1", sql)


class RollbackRefused(Exception):
    pass


def execute_guarded_rollback(connection, package, deletes):
    # Require one atomic statement and every guard before every delete. Reject
    # unsupported SQL rather than silently skip newly added preflight logic.
    sql = re.sub(r"--[^\n]*", "", (SEEDS / package / "rollback.sql").read_text()).strip()
    block = re.fullmatch(r"DO \$gh690\$ BEGIN\s+LOCK TABLE [\w, ]+ IN SHARE ROW EXCLUSIVE MODE;\s+"
                         r"IF (.*?) THEN RAISE EXCEPTION '[^']+'; END IF;\s+"
                         r"(DELETE FROM .*?)\s+END \$gh690\$;", sql, re.S)
    if not block:
        raise AssertionError("rollback must lock/check before deleting in one DO statement")
    predicate, delete_sql = block.groups()
    with connection:
        if connection.execute("SELECT " + sqlite_sql(predicate)).fetchone()[0]:
            raise RollbackRefused(package)
        for statement in delete_sql.split(";"):
            statement = statement.strip()
            if statement:
                if not statement.startswith("DELETE FROM "):
                    raise AssertionError("unexpected mutation")
                deletes.append(statement)
                connection.execute(sqlite_sql(statement))


class RollbackGuardTest(unittest.TestCase):
    def fixture(self, package):
        connection = sqlite3.connect(":memory:")
        self.addCleanup(connection.close)
        connection.execute("PRAGMA foreign_keys=ON")
        connection.create_function("CHAR_LENGTH", 1, len)
        for migration in PACKAGES[package]:
            connection.executescript(sqlite_sql((ROOT / migration).read_text()))
        if package == "products/loan":
            # V32 forward migration adds the second remote journal reference.
            connection.execute("ALTER TABLE eir_amortization_schedules ADD COLUMN amortization_journal_entry_slip_no VARCHAR(50)")
        connection.executescript(sqlite_sql((SEEDS / package / "seed.sql").read_text()))
        return connection

    def assert_refused_without_mutation(self, package, mutation):
        connection = self.fixture(package)
        connection.executescript(mutation)
        before = list(connection.iterdump())
        deletes = []
        with self.assertRaises(RollbackRefused):
            execute_guarded_rollback(connection, package, deletes)
        self.assertEqual([], deletes, "refusal must precede even the first DELETE")
        self.assertEqual(before, list(connection.iterdump()), "all source/lineage rows must survive")

    def test_pristine_cleanup_and_repeat_are_safe_for_all_six_packages(self):
        for package in PACKAGES:
            with self.subTest(package=package):
                connection = self.fixture(package)
                execute_guarded_rollback(connection, package, [])
                tables = connection.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()
                self.assertTrue(all(connection.execute(f'SELECT count(*) FROM {name}').fetchone()[0] == 0
                                    for (name,) in tables))
                execute_guarded_rollback(connection, package, [])

    def test_parent_collision_preserves_children(self):
        collisions = {
            "accounting/expenditure": "UPDATE expenditure_resolutions SET created_by='OTHER'",
            "accounting/payable": "UPDATE purchase_invoices SET created_by='OTHER'",
            "accounting/receivable": "UPDATE sales_invoices SET created_by='OTHER'",
            "products/deposit": "UPDATE deposit_accounts SET created_by='OTHER'",
            "products/loan": "UPDATE loans SET audit_user='OTHER'",
            "products/asset-lease": "UPDATE lease_contracts SET contract_no='OTHER'",
        }
        for package, mutation in collisions.items():
            with self.subTest(package=package):
                self.assert_refused_without_mutation(package, mutation)

    def test_business_key_parent_at_another_id_preserves_children(self):
        # Payable references an invoice business key, and Deposit has no FK.
        # A reserved business key alone never proves ownership of its parent.
        self.assert_refused_without_mutation("accounting/payable", "UPDATE purchase_invoices SET id=999")
        self.assert_refused_without_mutation("products/deposit", "UPDATE deposit_accounts SET id=999")

    def test_expenditure_journal_payment_and_other_external_refs_are_preserved(self):
        mutations = [
            "UPDATE expenditure_resolutions SET journal_entry_id=999",
            "UPDATE expenditure_resolutions SET tax_invoice_id=999",
            "UPDATE expenditure_resolutions SET lease_contract_id=999",
            "UPDATE expenditure_resolutions SET status='REQUESTED'",
            "UPDATE expenditure_resolutions SET created_by=NULL",
            "UPDATE budgets SET used_amount=4000",
            "UPDATE expenditure_details SET description='OTHER' WHERE id=6900001",
            "INSERT INTO ap_payments (id,expenditure_resolution_id,payment_date,amount,unapplied_amount) VALUES (999,6900001,'2090-01-15',3000,3000)",
        ]
        for mutation in mutations:
            with self.subTest(mutation=mutation):
                self.assert_refused_without_mutation("accounting/expenditure", mutation)

    def test_payable_journal_and_payment_references_are_preserved(self):
        mutations = [
            "UPDATE purchase_invoices SET journal_entry_id=999",
            "UPDATE payables SET journal_entry_id=999",
            "UPDATE payables SET status='PARTIAL_PAID', outstanding_amount=1000",
            "INSERT INTO payments (id,payment_date,vendor_code,payable_id,amount,execution_attempts,status,created_at) VALUES (999,'2090-01-15','GH690-VENDOR',6900001,100,0,'INITIATED','2090-01-15')",
        ]
        for mutation in mutations:
            with self.subTest(mutation=mutation):
                self.assert_refused_without_mutation("accounting/payable", mutation)

    def test_receivable_allocation_is_preserved(self):
        self.assert_refused_without_mutation("accounting/receivable", """
            INSERT INTO collections (id,collection_date,customer_code,amount,matched_amount,status,created_at)
            VALUES (999,'2090-01-15','GH690-CUSTOMER',100,100,'MATCHED','2090-01-15');
            INSERT INTO collection_allocations (id,collection_id,receivable_id,matched_amount,residual_collection_amount,residual_receivable_amount,created_at)
            VALUES (999,999,6900001,100,0,2100,'2090-01-15');
        """)

    def test_deposit_unconstrained_dependencies_are_preserved(self):
        mutations = [
            "UPDATE deposit_transactions SET journal_entry_id=999",
            "UPDATE deposit_transactions SET id=999",
            "DELETE FROM deposit_accounts",
            "INSERT INTO deposit_interest_schedules (id,account_number,accrual_date,accrued_interest,status) VALUES (999,'GH690-DEPOSIT','2090-01-15',100,'PENDING')",
            "INSERT INTO deposit_outbox (id,event_id,source_module,lineage_source_type,lineage_source_id,event_type,payload,status,created_at,idempotency_key) VALUES (999,'GH690-EVENT','deposit','ACCOUNT','GH690-DEPOSIT','OPEN','{}','PENDING','2090-01-15','GH690-EVENT')",
        ]
        for mutation in mutations:
            with self.subTest(mutation=mutation):
                self.assert_refused_without_mutation("products/deposit", mutation)

    def test_loan_completed_pending_and_accrual_lineage_are_preserved(self):
        mutations = [
            "INSERT INTO loan_events (id,loan_id,event_type,event_date,journal_entry_id) VALUES (999,6900001,'SCHEDULED_REPAYMENT','2090-01-15',999)",
            "INSERT INTO loan_events (id,loan_id,event_type,event_date) VALUES (999,6900001,'SCHEDULED_REPAYMENT_PENDING','2090-01-15')",
            "INSERT INTO loan_accrual_log (id,loan_id,accrual_date,accrued_amount,status,journal_no) VALUES (999,6900001,'2090-01-15',60000,'SUCCESS','GH690-JOURNAL')",
            "UPDATE eir_amortization_schedules SET amortization_journal_entry_id=999",
            "UPDATE eir_amortization_schedules SET amortization_journal_entry_slip_no='GH690-JOURNAL'",
            "UPDATE loans SET current_principal_balance=11000000,total_principal_paid=1000000",
            "INSERT INTO loan_disbursals (id,loan_id,disbursal_date,disbursed_amount,journal_entry_id) VALUES (999,6900001,'2090-01-15',12000000,999)",
        ]
        for mutation in mutations:
            with self.subTest(mutation=mutation):
                self.assert_refused_without_mutation("products/loan", mutation)

    def test_asset_lease_payment_and_lifecycle_history_are_preserved(self):
        mutations = [
            "UPDATE lease_payment_schedules SET status='PAID',actual_payment_amount=1060000",
            "INSERT INTO asset_histories (id,asset_id,history_type,event_at,audit_user) VALUES (999,6900001,'DISPOSED','2090-01-15','GH690')",
            "UPDATE fixed_assets SET asset_code='OTHER'",
        ]
        for mutation in mutations:
            with self.subTest(mutation=mutation):
                self.assert_refused_without_mutation("products/asset-lease", mutation)

    def test_asset_batch_depreciation_result_can_be_cleaned(self):
        connection = self.fixture("products/asset-lease")
        connection.execute("UPDATE fixed_assets SET accumulated_depreciation=200000,current_book_value=11800000,last_depreciation_date='2090-01-15'")
        connection.commit()
        execute_guarded_rollback(connection, "products/asset-lease", [])
        self.assertEqual(0, connection.execute("SELECT count(*) FROM fixed_assets").fetchone()[0])


if __name__ == "__main__":
    unittest.main()
