plugins {
    id 'java-library'
    id 'io.spring.dependency-management'
}

description = 'account-reconciliation-compat'

dependencies {
    api project(':reconciliation:core')
}



tasks.named('test') {
    dependsOn ':reconciliation:core:test'
}

tasks.named('check') {
    dependsOn ':reconciliation:core:check'
}

