CREATE TABLE IF NOT EXISTS master_data_change_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type VARCHAR(40) NOT NULL,
    target_key VARCHAR(100) NOT NULL,
    change_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    effective_date DATE NOT NULL,
    requested_version INTEGER NOT NULL,
    requested_by VARCHAR(80) NOT NULL,
    approved_by VARCHAR(80),
    requested_at TIMESTAMP NOT NULL,
    approved_at TIMESTAMP,
    reason VARCHAR(500),
    payload_json TEXT

);

CREATE INDEX IF NOT EXISTS idx_mdc_status_requested_at
    ON master_data_change_requests (status, requested_at);

CREATE INDEX IF NOT EXISTS idx_mdc_target_key
    ON master_data_change_requests (target_type, target_key, requested_version);
