spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:8888/"

auth:
  persistence:
    mode: ${AUTH_PERSISTENCE_MODE:jpa}
  master-data:
    base-url: ${AUTH_MASTER_DATA_BASE_URL:http://localhost:8082}
  jwt:
    secret: ${AUTH_JWT_SECRET:kbank-account-system-super-secret-key-1234567890}
    issuer: ${AUTH_JWT_ISSUER:auth-service}
    expiration-seconds: ${AUTH_JWT_EXPIRATION_SECONDS:3600}
  users:
    - username: ${AUTH_DEFAULT_USERNAME:admin}
      password: ${AUTH_DEFAULT_PASSWORD:1234}
      department-code: ${AUTH_DEFAULT_DEPARTMENT_CODE:FIN}
      active: true
      locked: false
      roles:
        - ROLE_ADMIN
