plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

description = 'account-reconciliation-batch'
group = "${rootProject.group}.reconciliation"

base {
    archivesName = 'account-reconciliation-batch'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:2023.0.1"
    }
}

dependencies {
    implementation project(':reconciliation:core')

    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'com.h2database:h2'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

bootRun {
    systemProperty 'spring.profiles.active', System.getProperty('spring.profiles.active', 'local')
}
