server:
  port: ${SERVER_PORT:8092}

spring:
  application:
    name: receivable-api
  profiles:
    default: local
  flyway:
    enabled: false
    locations: classpath:db/receivable-migration
    clean-disabled: true
    baseline-on-migrate: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
