CREATE TABLE reconciliation_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    frequency VARCHAR(20) NOT NULL,
    reconciliation_type VARCHAR(50) NOT NULL,
    criteria_json TEXT,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    audit_user VARCHAR(50),
    CONSTRAINT uk_reconciliation_unit_name UNIQUE (name),
    CONSTRAINT ck_reconciliation_unit_frequency CHECK (
        frequency IN ('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY', 'ADHOC')),
    CONSTRAINT ck_reconciliation_unit_type CHECK (
        reconciliation_type IN (
            'BANK_BOOK', 'GL_SUBLEDGER', 'SOURCE_GL', 'INTERCOMPANY', 'AR_AP_RECEIPT'))
);

CREATE TABLE difference_reason_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    is_adjustable BOOLEAN NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    audit_user VARCHAR(50),
    CONSTRAINT uk_difference_reason_code UNIQUE (code)
);

CREATE TABLE bank_statements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_code VARCHAR(20) NOT NULL,
    account_no VARCHAR(50) NOT NULL,
    transaction_date DATE NOT NULL,
    value_date DATE,
    description VARCHAR(500),
    withdrawal_amount NUMERIC(19, 2) NOT NULL,
    deposit_amount NUMERIC(19, 2) NOT NULL,
    balance NUMERIC(19, 2),
    branch_name VARCHAR(100),
    transaction_time TIMESTAMP(6),
    reconciliation_status VARCHAR(20) NOT NULL,
    create_date TIMESTAMP(6) NOT NULL,
    update_date TIMESTAMP(6) NOT NULL,
    audit_user VARCHAR(50) NOT NULL,
    CONSTRAINT ck_bank_statement_amounts CHECK (
        withdrawal_amount >= 0 AND deposit_amount >= 0
        AND NOT (withdrawal_amount > 0 AND deposit_amount > 0)),
    CONSTRAINT ck_bank_statement_value_date CHECK (
        value_date IS NULL OR value_date >= transaction_date),
    CONSTRAINT ck_bank_statement_status CHECK (
        reconciliation_status IN ('UNMATCHED', 'MATCHED', 'EXCLUDED'))
);

CREATE TABLE recon_external_stage_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id VARCHAR(50) NOT NULL,
    stage_code VARCHAR(20) NOT NULL,
    reconciliation_date DATE NOT NULL,
    source_system_code VARCHAR(50),
    item_reference VARCHAR(100),
    product_code VARCHAR(20),
    currency_code VARCHAR(3),
    legal_entity_code VARCHAR(20),
    amount NUMERIC(19, 2) NOT NULL,
    create_date TIMESTAMP(6) NOT NULL,
    update_date TIMESTAMP(6) NOT NULL,
    audit_user VARCHAR(50) NOT NULL,
    CONSTRAINT uk_recon_external_stage_item
        UNIQUE (unit_id, stage_code, reconciliation_date, item_reference),
    CONSTRAINT uk_recon_external_stage_aggregate
        UNIQUE NULLS NOT DISTINCT (
            unit_id, stage_code, reconciliation_date, item_reference,
            source_system_code, product_code, currency_code, legal_entity_code),
    CONSTRAINT ck_recon_external_stage_code CHECK (
        stage_code IN ('SOURCE', 'INTERFACE'))
);

CREATE TABLE reconciliation_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reconciliation_unit_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    rule_definition_json TEXT,
    tolerance_type VARCHAR(20),
    tolerance_value NUMERIC(19, 8),
    priority INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    audit_user VARCHAR(50),
    CONSTRAINT fk_reconciliation_rule_unit
        FOREIGN KEY (reconciliation_unit_id) REFERENCES reconciliation_units(id),
    CONSTRAINT ck_reconciliation_rule_tolerance_type CHECK (
        tolerance_type IS NULL OR tolerance_type IN ('NONE', 'ABSOLUTE', 'PERCENTAGE')),
    CONSTRAINT ck_reconciliation_rule_tolerance_value CHECK (
        tolerance_value IS NULL OR tolerance_value >= 0),
    CONSTRAINT ck_reconciliation_rule_priority CHECK (priority >= 0)
);

CREATE TABLE reconciliation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reconciliation_unit_id BIGINT NOT NULL,
    reconciliation_date DATE NOT NULL,
    run_start_time TIMESTAMP(6) NOT NULL,
    run_end_time TIMESTAMP(6),
    status VARCHAR(20) NOT NULL,
    total_items_source BIGINT NOT NULL,
    total_amount_source NUMERIC(19, 2) NOT NULL,
    total_items_target BIGINT NOT NULL,
    total_amount_target NUMERIC(19, 2) NOT NULL,
    matched_items_count BIGINT NOT NULL,
    matched_amount NUMERIC(19, 2) NOT NULL,
    unmatched_items_count BIGINT NOT NULL,
    unmatched_amount NUMERIC(19, 2) NOT NULL,
    run_by VARCHAR(50),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    audit_user VARCHAR(50),
    CONSTRAINT fk_reconciliation_run_unit
        FOREIGN KEY (reconciliation_unit_id) REFERENCES reconciliation_units(id),
    CONSTRAINT ck_reconciliation_run_counts CHECK (
        total_items_source >= 0 AND total_items_target >= 0
        AND matched_items_count >= 0 AND unmatched_items_count >= 0),
    CONSTRAINT ck_reconciliation_run_unmatched_amount CHECK (unmatched_amount >= 0),
    CONSTRAINT ck_reconciliation_run_lifecycle CHECK (
        (status = 'RUNNING' AND run_end_time IS NULL)
        OR (status IN ('SUCCESS', 'FAILED', 'PARTIAL')
            AND run_end_time IS NOT NULL AND run_end_time >= run_start_time))
);

CREATE TABLE reconciliation_differences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reconciliation_run_id BIGINT NOT NULL,
    difference_type VARCHAR(50) NOT NULL,
    amount_expected NUMERIC(19, 2),
    amount_actual NUMERIC(19, 2),
    difference_amount NUMERIC(19, 2) NOT NULL,
    description VARCHAR(1000),
    source_item_ref VARCHAR(255),
    target_item_ref VARCHAR(255),
    reason_code_id BIGINT,
    adjustment_journal_entry_id BIGINT,
    status VARCHAR(20) NOT NULL,
    assigned_to_user VARCHAR(50),
    sla_due_date TIMESTAMP(6),
    resolved_at TIMESTAMP(6),
    resolved_by VARCHAR(50),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    audit_user VARCHAR(50),
    CONSTRAINT fk_reconciliation_difference_run
        FOREIGN KEY (reconciliation_run_id) REFERENCES reconciliation_runs(id),
    CONSTRAINT fk_reconciliation_difference_reason
        FOREIGN KEY (reason_code_id) REFERENCES difference_reason_codes(id),
    CONSTRAINT uk_reconciliation_adjustment_journal UNIQUE (adjustment_journal_entry_id),
    CONSTRAINT uk_reconciliation_difference_lineage
        UNIQUE NULLS NOT DISTINCT (
            reconciliation_run_id, difference_type, source_item_ref, target_item_ref),
    CONSTRAINT ck_reconciliation_difference_type CHECK (
        difference_type IN (
            'AMOUNT_MISMATCH', 'MISSING_SOURCE', 'MISSING_TARGET', 'DATE_MISMATCH', 'OTHER')),
    CONSTRAINT ck_reconciliation_difference_amount CHECK (difference_amount >= 0),
    CONSTRAINT ck_reconciliation_adjustment_id CHECK (
        adjustment_journal_entry_id IS NULL OR adjustment_journal_entry_id > 0),
    CONSTRAINT ck_reconciliation_difference_lifecycle CHECK (
        (status IN ('PENDING', 'ASSIGNED', 'IN_REVIEW')
            AND resolved_at IS NULL AND resolved_by IS NULL)
        OR (status IN ('RESOLVED', 'IGNORED')
            AND reason_code_id IS NOT NULL
            AND resolved_at IS NOT NULL
            AND resolved_by IS NOT NULL)),
    CONSTRAINT ck_reconciliation_difference_assignment CHECK (
        status <> 'ASSIGNED'
        OR (assigned_to_user IS NOT NULL AND sla_due_date IS NOT NULL))
);

CREATE TABLE reconciliation_stage_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reconciliation_run_id BIGINT NOT NULL,
    stage_code VARCHAR(20) NOT NULL,
    total_count BIGINT NOT NULL,
    total_amount NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    audit_user VARCHAR(50) NOT NULL,
    CONSTRAINT fk_reconciliation_stage_result_run
        FOREIGN KEY (reconciliation_run_id) REFERENCES reconciliation_runs(id),
    CONSTRAINT uk_reconciliation_stage_per_run UNIQUE (reconciliation_run_id, stage_code),
    CONSTRAINT ck_reconciliation_stage_code CHECK (
        stage_code IN ('SOURCE', 'INTERFACE', 'JOURNAL', 'LEDGER')),
    CONSTRAINT ck_reconciliation_stage_count CHECK (total_count >= 0)
);

CREATE INDEX idx_reconciliation_rule_unit_priority
    ON reconciliation_rules(reconciliation_unit_id, priority);
CREATE INDEX idx_reconciliation_run_unit_date
    ON reconciliation_runs(reconciliation_unit_id, reconciliation_date);
CREATE INDEX idx_reconciliation_run_date_status
    ON reconciliation_runs(reconciliation_date, status);
CREATE INDEX idx_reconciliation_difference_run_status
    ON reconciliation_differences(reconciliation_run_id, status);
CREATE INDEX idx_reconciliation_difference_reason_status
    ON reconciliation_differences(reason_code_id, status);
CREATE INDEX idx_reconciliation_difference_assignee_status
    ON reconciliation_differences(assigned_to_user, status);
CREATE INDEX idx_bank_statement_date_account
    ON bank_statements(transaction_date, account_no);
CREATE INDEX idx_bank_statement_status
    ON bank_statements(reconciliation_status);
CREATE INDEX idx_recon_external_stage_summary
    ON recon_external_stage_record(
        unit_id, stage_code, reconciliation_date,
        product_code, currency_code, legal_entity_code);
