server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: account-mart-api
  profiles:
    default: local
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
    vault:
      enabled: false
  flyway:
    enabled: false
    locations: classpath:db/account-mart-local-migration
    clean-disabled: true
    baseline-on-migrate: false
  batch:
    jdbc:
      initialize-schema: never
  sql:
    init:
      mode: never

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    redis:
      enabled: false
    vault:
      enabled: false
  tracing:
    enabled: false

logging:
  level:
    com.ho.account.mart: DEBUG
