-- Forward-only PostgreSQL baseline. Published V1-V5 checksums remain unchanged.
-- V2-V5 already own master_data_change_requests; this migration supplies every other JPA table.

CREATE TABLE IF NOT EXISTS account_subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixed_asset BOOLEAN NOT NULL,
    unsettled BOOLEAN NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    parent_id BIGINT,
    balance_type VARCHAR(10) NOT NULL CHECK (balance_type IN ('DEBIT', 'CREDIT')),
    code VARCHAR(20) NOT NULL,
    account_type VARCHAR(30) CHECK (account_type IN (
        'ASSETS', 'LIABILITIES', 'EQUITY', 'REVENUE', 'EXPENSES',
        'NON_OPERATING_INCOME', 'NON_OPERATING_EXPENSES'
    )),
    category VARCHAR(30) CHECK (category IN ('ASSETS', 'LIABILITIES', 'EQUITY', 'REVENUE', 'EXPENSES')),
    audit_user VARCHAR(50),
    name VARCHAR(100) NOT NULL,
    regulatory_mapping_code VARCHAR(100),
    report_line VARCHAR(100),
    CONSTRAINT fk_account_subjects_parent
        FOREIGN KEY (parent_id) REFERENCES account_subjects (id)
);

CREATE TABLE IF NOT EXISTS business_partners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    use_yn BOOLEAN NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    business_partner_code VARCHAR(20) NOT NULL,
    partner_type VARCHAR(20) NOT NULL CHECK (partner_type IN ('CUSTOMER', 'VENDOR', 'BANK', 'OTHER_BP')),
    registration_number VARCHAR(20),
    risk_rating VARCHAR(20) NOT NULL CHECK (risk_rating IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    kyc_status VARCHAR(30) NOT NULL CHECK (kyc_status IN ('PENDING', 'APPROVED', 'REJECTED', 'REVIEW_REQUIRED')),
    audit_user VARCHAR(50),
    business_item VARCHAR(50),
    business_type VARCHAR(50),
    ceo_name VARCHAR(50),
    business_partner_name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS business_partner_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_partner_id BIGINT NOT NULL,
    is_main_account BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    swift_code VARCHAR(20),
    account_holder VARCHAR(100) NOT NULL,
    account_number VARCHAR(100) NOT NULL,
    bank_name VARCHAR(100) NOT NULL,
    CONSTRAINT fk_business_partner_accounts_partner
        FOREIGN KEY (business_partner_id) REFERENCES business_partners (id)
);

CREATE TABLE IF NOT EXISTS currencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_code VARCHAR(3) NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    symbol VARCHAR(10),
    audit_user VARCHAR(50),
    currency_name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    valid_from DATE NOT NULL,
    valid_to DATE NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    code VARCHAR(20) NOT NULL,
    type VARCHAR(30) CHECK (type IN ('COST_CENTER', 'PROFIT_CENTER', 'SUPPORT', 'OTHER')),
    audit_user VARCHAR(50),
    name VARCHAR(100) NOT NULL,
    CONSTRAINT fk_departments_parent
        FOREIGN KEY (parent_id) REFERENCES departments (id)
);

CREATE TABLE IF NOT EXISTS exchange_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    effective_date DATE NOT NULL,
    from_currency_code VARCHAR(3) NOT NULL,
    to_currency_code VARCHAR(3) NOT NULL,
    rate NUMERIC(19, 8) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_exchange_rates_pair_date
        UNIQUE (from_currency_code, to_currency_code, effective_date)
);

CREATE TABLE IF NOT EXISTS fiscal_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    fiscal_period VARCHAR(2) NOT NULL,
    fiscal_year VARCHAR(4) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    closing_status VARCHAR(20) NOT NULL CHECK (closing_status IN ('OPEN', 'CLOSED', 'PERMANENTLY_CLOSED')),
    audit_user VARCHAR(50),
    CONSTRAINT uk_fiscal_periods_year_period
        UNIQUE (fiscal_year, fiscal_period)
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price NUMERIC(19, 4) NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    unit_of_measure VARCHAR(20),
    audit_user VARCHAR(50),
    product_code VARCHAR(50) NOT NULL,
    product_type VARCHAR(50) NOT NULL CHECK (product_type IN ('PHYSICAL', 'SERVICE', 'DIGITAL', 'LOAN', 'DEPOSIT')),
    name VARCHAR(200) NOT NULL,
    description VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS tax_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tax_rate NUMERIC(7, 4) NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    tax_account_code VARCHAR(20),
    tax_code VARCHAR(20) NOT NULL,
    tax_type VARCHAR(20) NOT NULL CHECK (tax_type IN ('VAT_INPUT', 'VAT_OUTPUT', 'WITHHOLDING', 'ZERO_RATE', 'EXEMPT')),
    audit_user VARCHAR(50),
    name VARCHAR(100) NOT NULL
);

-- V2 created this table before enum check constraints were represented in SQL.
ALTER TABLE master_data_change_requests
    ADD CONSTRAINT ck_mdc_change_type
        CHECK (change_type IN ('CREATE', 'UPDATE', 'DEACTIVATE'));
ALTER TABLE master_data_change_requests
    ADD CONSTRAINT ck_mdc_status
        CHECK (status IN ('REQUESTED', 'APPROVED', 'REJECTED', 'APPLIED'));
ALTER TABLE master_data_change_requests
    ADD CONSTRAINT ck_mdc_target_type
        CHECK (target_type IN (
            'ACCOUNT_SUBJECT', 'BUSINESS_PARTNER', 'DEPARTMENT', 'PRODUCT',
            'CURRENCY', 'EXCHANGE_RATE', 'FISCAL_PERIOD'
        ));

CREATE INDEX IF NOT EXISTS idx_account_code_valid
    ON account_subjects (code, valid_from, valid_to);
CREATE INDEX IF NOT EXISTS idx_bp_code_valid
    ON business_partners (business_partner_code, valid_from, valid_to);
CREATE INDEX IF NOT EXISTS idx_currency_code_valid
    ON currencies (currency_code, valid_from, valid_to);
CREATE INDEX IF NOT EXISTS idx_dept_code_valid
    ON departments (code, valid_from, valid_to);
CREATE INDEX IF NOT EXISTS idx_product_code_valid
    ON products (product_code, valid_from, valid_to);
CREATE INDEX IF NOT EXISTS idx_tax_code_valid
    ON tax_profiles (tax_code, valid_from, valid_to);
