spring:
  application:
    name: ifrs9-allowance-batch
  profiles:
    default: local
  main:
    web-application-type: none
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
    vault:
      enabled: false
  batch:
    job:
      enabled: false
  flyway:
    enabled: false
    locations: classpath:db/ecl-local-migration
    clean-disabled: true
    baseline-on-migrate: false
  sql:
    init:
      mode: never
  kafka:
    listener:
      auto-startup: false
  redisson:
    enabled: false

eureka:
  client:
    enabled: false

management:
  health:
    redis:
      enabled: false
    vault:
      enabled: false
  tracing:
    enabled: false
