server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: journal-ledger
  profiles:
    default: local
  flyway:
    enabled: false
    locations: classpath:db/journal-migration
    clean-disabled: true
    baseline-on-migrate: false
