plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

description = 'account-deposit-api'
group = 'com.ho.deposit'

base {
    archivesName = 'account-deposit-api'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:2023.0.1"
    }
}

dependencies {
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    implementation project(':deposit:core')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation 'com.github.ben-manes.caffeine:caffeine'
    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'org.postgresql:postgresql'

    compileOnly 'org.projectlombok:lombok:1.18.32'
    annotationProcessor 'org.projectlombok:lombok:1.18.32'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

sourceSets.test.java.srcDir rootProject.file('test-support/runtime-contracts/src/test/java')

bootJar {
    mainClass = 'com.ho.account.deposit.DepositApplication'
}
