version: '3.8'

services:
  # --- Vault: 스위스 은행 비밀 금고 (비밀번호, 토큰 키 전용 저장소) ---
  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      # 로컬 개발 환경의 편의성을 위해 개발 모드(dev)로 띄웁니다. (메모리 모드)
      - VAULT_DEV_ROOT_TOKEN_ID=my-root-token-123 # 이 마스터 키가 있어야 금고 문을 열 수 있습니다!
    cap_add:
      - IPC_LOCK # 메모리 스와핑을 방지하여 보안을 강화하는 권한
    networks:
      - account-network

networks:
  account-network:
    external: true
