plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

description = 'account-asset-lease-batch'
group = "${rootProject.group}.asset"

base {
    archivesName = 'account-asset-lease-batch'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:2023.0.1"
    }
}

sourceSets {
    main {
        resources {
            srcDirs += ["${projectDir}/../src/main/resources"]
        }
    }
}

dependencies {
    implementation project(':asset-lease:core')

    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    implementation 'com.github.ben-manes.caffeine:caffeine'

    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'org.postgresql:postgresql'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.batch:spring-batch-test'
    testImplementation 'org.flywaydb:flyway-core'
}

bootRun {
    systemProperty 'spring.profiles.active', System.getProperty('spring.profiles.active', 'local')
}

springBoot {
    mainClass = 'com.ho.account.asset.batch.AssetLeaseBatchApplication'
}

