CREATE TABLE IF NOT EXISTS rpt_line_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_type VARCHAR(40) NOT NULL,
    line_code VARCHAR(80) NOT NULL,
    label VARCHAR(200) NOT NULL,
    account_code VARCHAR(40) NOT NULL,
    note_number VARCHAR(40),
    line_level INTEGER NOT NULL,
    display_order INTEGER NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_rpt_line_mapping_effective
    ON rpt_line_mapping (statement_type, valid_from, valid_to, display_order);

CREATE INDEX idx_rpt_line_mapping_account
    ON rpt_line_mapping (account_code, statement_type);

CREATE TABLE IF NOT EXISTS rpt_snapshot_header (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_id VARCHAR(80) NOT NULL,
    statement_type VARCHAR(40) NOT NULL,
    base_date TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_rpt_snapshot_final
    ON rpt_snapshot_header (statement_type, base_date, status);

CREATE INDEX idx_rpt_snapshot_lookup
    ON rpt_snapshot_header (statement_type, base_date, status, created_at);

CREATE TABLE IF NOT EXISTS rpt_snapshot_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_header_id BIGINT NOT NULL,
    line_order INTEGER NOT NULL,
    line_code VARCHAR(80) NOT NULL,
    label VARCHAR(200) NOT NULL,
    current_amount DECIMAL(19, 4) NOT NULL,
    previous_amount DECIMAL(19, 4) NOT NULL,
    note_number VARCHAR(40),
    line_level INTEGER NOT NULL,
    CONSTRAINT fk_rpt_snapshot_detail_header
        FOREIGN KEY (snapshot_header_id) REFERENCES rpt_snapshot_header(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_rpt_snapshot_detail_header
    ON rpt_snapshot_detail (snapshot_header_id, line_order);

INSERT INTO rpt_line_mapping (
    statement_type, line_code, label, account_code, note_number, line_level, display_order, valid_from, valid_to
) VALUES
    ('BALANCE_SHEET', 'ASSET_CASH', '현금 및 현금성자산', '101', '3', 1, 10, DATE '2020-01-01', NULL),
    ('BALANCE_SHEET', 'ASSET_CASH', '현금 및 현금성자산', '102', '3', 1, 10, DATE '2020-01-01', NULL),
    ('BALANCE_SHEET', 'LIABILITY_DEPOSIT', '예수부채', '201', '8', 1, 20, DATE '2020-01-01', NULL),
    ('BALANCE_SHEET', 'LIABILITY_DEPOSIT', '예수부채', '202', '8', 1, 20, DATE '2020-01-01', NULL),
    ('INCOME_STATEMENT', 'INTEREST_INCOME', '이자수익', '401', '12', 1, 10, DATE '2020-01-01', NULL),
    ('INCOME_STATEMENT', 'INTEREST_EXPENSE', '이자비용', '501', '13', 1, 20, DATE '2020-01-01', NULL);
