CREATE TABLE IF NOT EXISTS rpt_regulatory_submission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id VARCHAR(80) NOT NULL UNIQUE,
    statement_id VARCHAR(80) NOT NULL,
    statement_type VARCHAR(40) NOT NULL,
    base_date TIMESTAMP NOT NULL,
    submission_version INTEGER NOT NULL,
    submitted_by VARCHAR(80) NOT NULL,
    submitted_at TIMESTAMP NOT NULL,
    correction_reason VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    validation_messages VARCHAR(2000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_rpt_regulatory_submission_version
        UNIQUE (statement_type, base_date, submission_version)
);

CREATE INDEX idx_rpt_regulatory_submission_lookup
    ON rpt_regulatory_submission (statement_type, base_date, submission_version);
