CREATE TABLE IF NOT EXISTS rpt_disclosure_note_mart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id VARCHAR(80) NOT NULL UNIQUE,
    mart_id VARCHAR(80) NOT NULL,
    statement_id VARCHAR(80) NOT NULL,
    statement_type VARCHAR(40) NOT NULL,
    base_date TIMESTAMP NOT NULL,
    note_number VARCHAR(40) NOT NULL,
    note_category VARCHAR(40) NOT NULL,
    source_line_code VARCHAR(80) NOT NULL,
    source_line_label VARCHAR(200) NOT NULL,
    maturity_bucket VARCHAR(40) NOT NULL,
    rate_type VARCHAR(40) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    risk_category VARCHAR(40) NOT NULL,
    current_amount DECIMAL(19, 4) NOT NULL,
    previous_amount DECIMAL(19, 4) NOT NULL,
    generated_by VARCHAR(80) NOT NULL,
    generated_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_rpt_disclosure_note_mart_lookup
    ON rpt_disclosure_note_mart (statement_type, base_date, note_number, source_line_code);

CREATE INDEX idx_rpt_disclosure_note_mart_category
    ON rpt_disclosure_note_mart (note_category, maturity_bucket, rate_type, currency_code, risk_category);
