CREATE TABLE IF NOT EXISTS rpt_regulatory_report_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement_type VARCHAR(40) NOT NULL,
    target_agency VARCHAR(40) NOT NULL,
    report_code VARCHAR(80) NOT NULL,
    field_code VARCHAR(80) NOT NULL,
    field_label VARCHAR(200) NOT NULL,
    source_note_category VARCHAR(40) NOT NULL,
    source_note_number VARCHAR(40),
    source_line_code VARCHAR(80),
    required BOOLEAN NOT NULL,
    display_order INTEGER NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_rpt_regulatory_mapping_effective
    ON rpt_regulatory_report_mapping (statement_type, target_agency, valid_from, valid_to, display_order);

CREATE TABLE IF NOT EXISTS rpt_regulatory_filing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filing_id VARCHAR(80) NOT NULL,
    submission_id VARCHAR(80) NOT NULL,
    statement_type VARCHAR(40) NOT NULL,
    base_date TIMESTAMP NOT NULL,
    submission_version INTEGER NOT NULL,
    target_agency VARCHAR(40) NOT NULL,
    submitted_by VARCHAR(80) NOT NULL,
    submitted_at TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL,
    regulator_receipt_id VARCHAR(120) NOT NULL,
    regulator_message VARCHAR(500),
    report_code VARCHAR(80) NOT NULL,
    field_code VARCHAR(80) NOT NULL,
    field_label VARCHAR(200) NOT NULL,
    source_note_number VARCHAR(40) NOT NULL,
    source_line_code VARCHAR(80) NOT NULL,
    source_line_label VARCHAR(200) NOT NULL,
    current_amount DECIMAL(19, 4) NOT NULL,
    previous_amount DECIMAL(19, 4) NOT NULL,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_rpt_regulatory_filing_lookup
    ON rpt_regulatory_filing (statement_type, base_date, submitted_at);

CREATE INDEX idx_rpt_regulatory_filing_id
    ON rpt_regulatory_filing (filing_id, display_order);

INSERT INTO rpt_regulatory_report_mapping (
    statement_type, target_agency, report_code, field_code, field_label,
    source_note_category, source_note_number, source_line_code, required, display_order, valid_from, valid_to
) VALUES
    ('BALANCE_SHEET', 'FSS', 'FSS_BS_DISCLOSURE', 'CASH_AND_CASH_EQUIVALENTS', '현금 및 현금성자산',
     'CURRENCY', '3', 'ASSET_CASH', TRUE, 10, DATE '2020-01-01', NULL),
    ('BALANCE_SHEET', 'FSS', 'FSS_BS_DISCLOSURE', 'DEPOSIT_LIABILITIES', '예수부채',
     'MATURITY', '8', 'LIABILITY_DEPOSIT', TRUE, 20, DATE '2020-01-01', NULL),
    ('INCOME_STATEMENT', 'FSS', 'FSS_IS_RATE', 'INTEREST_INCOME', '이자수익',
     'INTEREST_RATE', '12', 'INTEREST_INCOME', TRUE, 10, DATE '2020-01-01', NULL),
    ('INCOME_STATEMENT', 'FSS', 'FSS_IS_RATE', 'INTEREST_EXPENSE', '이자비용',
     'INTEREST_RATE', '13', 'INTEREST_EXPENSE', TRUE, 20, DATE '2020-01-01', NULL);
