-- PostgreSQL variant of the published H2 V40 migration.

CREATE TABLE deposit_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(20) NOT NULL UNIQUE,
    customer_code VARCHAR(20) NOT NULL,
    product_code VARCHAR(20) NOT NULL,
    balance DECIMAL(19, 4) NOT NULL DEFAULT 0.0000,
    currency_code VARCHAR(3) NOT NULL,
    interest_rate DECIMAL(19, 8) NOT NULL,
    status VARCHAR(20) NOT NULL,
    opened_at DATE NOT NULL,
    closed_at DATE,
    valid_from DATE NOT NULL,
    valid_to DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50)
);

CREATE TABLE deposit_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(20) NOT NULL,
    transaction_date TIMESTAMP NOT NULL,
    amount DECIMAL(19, 4) NOT NULL,
    type VARCHAR(20) NOT NULL,
    balance_after DECIMAL(19, 4) NOT NULL,
    description VARCHAR(200),
    journal_entry_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE deposit_interest_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(20) NOT NULL,
    accrual_date DATE NOT NULL,
    accrued_interest DECIMAL(19, 4) NOT NULL,
    status VARCHAR(20) NOT NULL,
    journal_entry_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_deposit_account_number ON deposit_accounts(account_number);
CREATE INDEX idx_deposit_account_customer ON deposit_accounts(customer_code);
CREATE INDEX idx_deposit_transaction_account ON deposit_transactions(account_number);
CREATE INDEX idx_deposit_interest_account ON deposit_interest_schedules(account_number);
