plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

description = 'account-deposit-batch'
group = 'com.ho.deposit'

base {
    archivesName = 'account-deposit-batch'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:3.2.5"
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:2023.0.1"
    }
}

dependencies {
    implementation project(':deposit:core')
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    runtimeOnly 'com.h2database:h2'

    compileOnly 'org.projectlombok:lombok:1.18.32'
    annotationProcessor 'org.projectlombok:lombok:1.18.32'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.batch:spring-batch-test'
}

bootJar {
    enabled = true
    mainClass = 'com.ho.account.deposit.batch.DepositBatchApplication'
}

jar { enabled = true }
