CREATE TABLE purchase_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no VARCHAR(50) NOT NULL,
    vendor_code VARCHAR(20) NOT NULL,
    issue_date DATE NOT NULL,
    due_date DATE NOT NULL,
    total_amount NUMERIC(19, 2) NOT NULL,
    tax_amount NUMERIC(19, 2) NOT NULL,
    net_amount NUMERIC(19, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    journal_entry_id BIGINT,
    description VARCHAR(500),
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_purchase_invoice_business_key UNIQUE (invoice_no, vendor_code),
    CONSTRAINT ck_purchase_invoice_dates CHECK (due_date >= issue_date),
    CONSTRAINT ck_purchase_invoice_amounts CHECK (
        net_amount > 0 AND tax_amount >= 0 AND total_amount > 0
        AND total_amount = net_amount + tax_amount),
    CONSTRAINT ck_purchase_invoice_status CHECK (
        status IN ('RECEIVED', 'APPROVED', 'PAID', 'PARTIAL_PAID', 'OVERDUE', 'CANCELLED'))
);

CREATE TABLE payables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_invoice_invoice_no VARCHAR(50) NOT NULL,
    purchase_invoice_vendor_code VARCHAR(20) NOT NULL,
    vendor_code VARCHAR(20) NOT NULL,
    original_amount NUMERIC(19, 2) NOT NULL,
    outstanding_amount NUMERIC(19, 2) NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    journal_entry_id BIGINT,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_payable_purchase_invoice
        UNIQUE (purchase_invoice_invoice_no, purchase_invoice_vendor_code),
    CONSTRAINT fk_payable_purchase_invoice
        FOREIGN KEY (purchase_invoice_invoice_no, purchase_invoice_vendor_code)
        REFERENCES purchase_invoices(invoice_no, vendor_code),
    CONSTRAINT ck_payable_vendor_lineage CHECK (
        vendor_code = purchase_invoice_vendor_code),
    CONSTRAINT ck_payable_amounts CHECK (
        original_amount > 0 AND outstanding_amount >= 0
        AND outstanding_amount <= original_amount),
    CONSTRAINT ck_payable_status CHECK (
        (status = 'OPEN' AND outstanding_amount = original_amount)
        OR (status = 'APPROVED' AND outstanding_amount > 0)
        OR (status = 'UNPAID' AND outstanding_amount > 0)
        OR (status = 'IN_PAYMENT' AND outstanding_amount > 0)
        OR (status = 'PARTIAL_PAID'
            AND outstanding_amount > 0 AND outstanding_amount < original_amount)
        OR (status = 'PAID' AND outstanding_amount = 0)
        OR (status = 'OVERDUE' AND outstanding_amount > 0)
        OR status = 'WRITTEN_OFF')
);

CREATE TABLE payment_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_date DATE NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_payment_run_status CHECK (
        status IN ('INITIATED', 'PROCESSING', 'COMPLETED', 'FAILED'))
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_date DATE NOT NULL,
    vendor_code VARCHAR(20) NOT NULL,
    payable_id BIGINT,
    amount NUMERIC(19, 2) NOT NULL,
    bank_account VARCHAR(100),
    reference_no VARCHAR(100),
    execution_attempts INTEGER NOT NULL,
    failure_reason VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    journal_entry_id BIGINT,
    payment_run_id BIGINT,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_payment_payable FOREIGN KEY (payable_id) REFERENCES payables(id),
    CONSTRAINT fk_payment_run FOREIGN KEY (payment_run_id) REFERENCES payment_runs(id),
    CONSTRAINT ck_payment_amount CHECK (amount > 0),
    CONSTRAINT ck_payment_execution_attempts CHECK (execution_attempts >= 0),
    CONSTRAINT ck_payment_status CHECK (
        status IN ('INITIATED', 'APPROVED', 'COMPLETED', 'FAILED', 'CANCELLED'))
);

CREATE TABLE advance_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_code VARCHAR(20) NOT NULL,
    payment_date DATE NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    outstanding_amount NUMERIC(19, 2) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    journal_entry_id BIGINT,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_advance_payment_amounts CHECK (
        amount > 0 AND outstanding_amount >= 0 AND outstanding_amount <= amount),
    CONSTRAINT ck_advance_payment_status CHECK (
        status IN ('ACTIVE', 'OFFSET', 'REFUNDED'))
);

CREATE INDEX idx_purchase_invoice_vendor_due
    ON purchase_invoices(vendor_code, due_date, status);
CREATE INDEX idx_payable_vendor_due_status
    ON payables(vendor_code, due_date, status);
CREATE INDEX idx_payable_due_status
    ON payables(due_date, status);
CREATE INDEX idx_payment_run_date_status
    ON payment_runs(run_date, status);
CREATE INDEX idx_payment_payable
    ON payments(payable_id);
CREATE INDEX idx_payment_run
    ON payments(payment_run_id);
CREATE INDEX idx_payment_vendor_date_status
    ON payments(vendor_code, payment_date, status);
CREATE INDEX idx_advance_payment_vendor_status
    ON advance_payments(vendor_code, status);
