server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: ifrs9-allowance-api
  profiles:
    default: local
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
    vault:
      enabled: false
  batch:
    job:
      enabled: false
  flyway:
    enabled: false
    locations: classpath:db/ecl-local-migration
    clean-disabled: true
    baseline-on-migrate: false
  sql:
    init:
      mode: never
  kafka:
    listener:
      auto-startup: false
  redisson:
    enabled: false

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    redis:
      enabled: false
    vault:
      enabled: false
  tracing:
    enabled: false
