server:
  port: 8083

spring:
  application:
    name: credit-risk-api
  
  # 🔑 [Centralized Config] 설정 서버 연동
  config:
    import: "optional:configserver:http://localhost:8888"

# 💡 최소한의 인프라 연결 설정만 유지
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# 로깅 설정
logging:
  level:
    com.ho.account.ecl: DEBUG
