-- Clean PostgreSQL baseline for the Closing bounded context.
--
-- Existing legacy databases are baselined at version 49 and therefore skip this file.
-- Clean databases apply this file and then V50, which upgrades daily_closing_status from
-- the legacy is_closed representation to the EOD/BOD state machine.

CREATE TABLE closing_calendars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiscal_year VARCHAR(4) NOT NULL,
    fiscal_period VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    close_initiated_by VARCHAR(50),
    close_initiated_at TIMESTAMP,
    closed_by VARCHAR(50),
    closed_at TIMESTAMP,
    reopened_by VARCHAR(50),
    reopened_at TIMESTAMP,
    is_current_period BOOLEAN NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    audit_user VARCHAR(50),
    CONSTRAINT uk_closing_calendar_period UNIQUE (fiscal_year, fiscal_period)
);

CREATE TABLE closing_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    category VARCHAR(50),
    due_date TIMESTAMP,
    assigned_to VARCHAR(50),
    status VARCHAR(30) NOT NULL,
    completion_condition_json TEXT,
    is_mandatory BOOLEAN NOT NULL,
    task_order INTEGER NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    audit_user VARCHAR(50),
    CONSTRAINT fk_closing_task_calendar
        FOREIGN KEY (calendar_id) REFERENCES closing_calendars(id)
);

CREATE INDEX idx_closing_task_calendar_order
    ON closing_tasks (calendar_id, task_order);

CREATE TABLE closing_gates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    status VARCHAR(30) NOT NULL,
    check_condition_json TEXT,
    passed_by VARCHAR(50),
    passed_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    audit_user VARCHAR(50),
    CONSTRAINT fk_closing_gate_calendar
        FOREIGN KEY (calendar_id) REFERENCES closing_calendars(id)
);

CREATE INDEX idx_closing_gate_calendar ON closing_gates (calendar_id);

CREATE TABLE closing_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_id BIGINT NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    previous_status VARCHAR(50),
    current_status VARCHAR(50) NOT NULL,
    action_reason VARCHAR(1000),
    action_user VARCHAR(50) NOT NULL,
    action_at TIMESTAMP NOT NULL,
    detail_info TEXT,
    CONSTRAINT fk_closing_audit_calendar
        FOREIGN KEY (calendar_id) REFERENCES closing_calendars(id)
);

CREATE INDEX idx_closing_audit_calendar_time
    ON closing_audit_logs (calendar_id, action_at);

CREATE TABLE period_locks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiscal_period_id BIGINT NOT NULL,
    lock_type VARCHAR(50) NOT NULL,
    locked_by VARCHAR(50),
    locked_at TIMESTAMP,
    reason VARCHAR(1000),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    audit_user VARCHAR(50)
);

CREATE INDEX idx_period_lock_fiscal_period ON period_locks (fiscal_period_id);

CREATE TABLE reopen_approvals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiscal_period_id BIGINT NOT NULL,
    requested_by VARCHAR(50),
    requested_at TIMESTAMP,
    reason VARCHAR(1000),
    status VARCHAR(30) NOT NULL,
    approved_by VARCHAR(50),
    approved_at TIMESTAMP,
    impact_analysis_report TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    audit_user VARCHAR(50)
);

CREATE INDEX idx_reopen_approval_period_requested
    ON reopen_approvals (fiscal_period_id, requested_at);

CREATE TABLE valuation_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiscal_period_id BIGINT NOT NULL,
    valuation_type VARCHAR(50) NOT NULL,
    run_date_time TIMESTAMP NOT NULL,
    status VARCHAR(30) NOT NULL,
    generated_journal_entry_id BIGINT,
    report_link VARCHAR(200),
    run_by VARCHAR(50),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    audit_user VARCHAR(50)
);

CREATE INDEX idx_valuation_batch_fiscal_period
    ON valuation_batches (fiscal_period_id);

CREATE TABLE provision_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiscal_period_id BIGINT NOT NULL,
    provision_type VARCHAR(50) NOT NULL,
    run_date_time TIMESTAMP NOT NULL,
    status VARCHAR(30) NOT NULL,
    generated_journal_entry_id BIGINT,
    report_link VARCHAR(200),
    run_by VARCHAR(50),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    audit_user VARCHAR(50)
);

CREATE INDEX idx_provision_batch_fiscal_period
    ON provision_batches (fiscal_period_id);

CREATE TABLE closing_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiscal_period_id BIGINT NOT NULL,
    journal_entry_id BIGINT NOT NULL,
    adjustment_type VARCHAR(50) NOT NULL,
    description VARCHAR(1000),
    approved_by VARCHAR(50),
    approved_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    audit_user VARCHAR(50)
);

CREATE INDEX idx_closing_adjustment_fiscal_period
    ON closing_adjustments (fiscal_period_id);
CREATE INDEX idx_closing_adjustment_journal_entry
    ON closing_adjustments (journal_entry_id);

CREATE TABLE daily_closing_status (
    date DATE PRIMARY KEY,
    is_closed BOOLEAN NOT NULL DEFAULT FALSE,
    closed_at TIMESTAMP,
    closed_by VARCHAR(80)
);
