-- Immutable provider snapshots used to authorize final close. The header's calendar_id is an
-- indexed identity value rather than a reverse FK: application code locks and validates the
-- calendar before append, and evidence must survive any later calendar lifecycle maintenance.
CREATE TABLE final_close_evidence_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evidence_set_id VARCHAR(100) NOT NULL,
    calendar_id BIGINT NOT NULL,
    fiscal_period_id BIGINT NOT NULL,
    fiscal_year VARCHAR(10) NOT NULL,
    fiscal_period VARCHAR(20) NOT NULL,
    ledger_cutoff DATE NOT NULL,
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    submitted_by VARCHAR(100) NOT NULL,
    content_digest VARCHAR(64) NOT NULL,
    CONSTRAINT uk_final_close_evidence_set_provider_id UNIQUE (evidence_set_id)
);

-- The leading calendar/time columns implement latest-observation selection; id is the append
-- sequence tie-breaker so an equally-timed newer FAIL cannot be hidden by an older PASS.
CREATE INDEX idx_final_close_evidence_set_latest
    ON final_close_evidence_sets (calendar_id, observed_at DESC, id DESC);
CREATE INDEX idx_final_close_evidence_set_fiscal_period
    ON final_close_evidence_sets (fiscal_period_id);

CREATE TABLE final_close_evidence_controls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evidence_set_db_id BIGINT NOT NULL,
    control_type VARCHAR(40) NOT NULL,
    source_system VARCHAR(100) NOT NULL,
    source_run_id VARCHAR(100) NOT NULL,
    outcome VARCHAR(10) NOT NULL,
    blocking_item_count INTEGER NOT NULL,
    CONSTRAINT chk_final_close_evidence_control_outcome CHECK (outcome IN ('PASS', 'FAIL')),
    CONSTRAINT chk_final_close_evidence_control_blocking_count CHECK (blocking_item_count >= 0),
    CONSTRAINT fk_final_close_evidence_control_set
        FOREIGN KEY (evidence_set_db_id) REFERENCES final_close_evidence_sets(id) ON DELETE CASCADE
);

CREATE INDEX idx_final_close_evidence_control_set
    ON final_close_evidence_controls (evidence_set_db_id, id);

CREATE TABLE final_close_evidence_totals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    control_id BIGINT NOT NULL,
    account_code VARCHAR(100) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    source_total DECIMAL(38, 18) NOT NULL,
    posted_total DECIMAL(38, 18) NOT NULL,
    CONSTRAINT fk_final_close_evidence_total_control
        FOREIGN KEY (control_id) REFERENCES final_close_evidence_controls(id) ON DELETE CASCADE
);

CREATE INDEX idx_final_close_evidence_total_control
    ON final_close_evidence_totals (control_id, id);

ALTER TABLE closing_calendars ADD COLUMN transition_evidence_set_id VARCHAR(100);

-- Provider evidence is immutable. A pending calendar may reference it, but neither calendar
-- deletion nor a rollback migration is allowed to cascade into financial evidence deletion.
ALTER TABLE closing_calendars ADD CONSTRAINT fk_closing_transition_evidence_set
    FOREIGN KEY (transition_evidence_set_id)
    REFERENCES final_close_evidence_sets(evidence_set_id) ON DELETE NO ACTION;

ALTER TABLE closing_calendars DROP CONSTRAINT chk_closing_transition_complete;

-- Legacy CLOSED-target transitions created by V52 have no evidence ID and must remain migratable.
-- Runtime recovery fences those rows; new application writes always bind evidence before dispatch.
ALTER TABLE closing_calendars ADD CONSTRAINT chk_closing_transition_complete CHECK (
    (transition_id IS NULL AND transition_target IS NULL AND transition_stage IS NULL
        AND transition_fiscal_period_id IS NULL AND transition_approval_id IS NULL
        AND transition_actor IS NULL AND transition_prepared_at IS NULL
        AND transition_evidence_set_id IS NULL)
    OR
    (transition_id IS NOT NULL AND transition_target IS NOT NULL AND transition_stage IS NOT NULL
        AND transition_fiscal_period_id IS NOT NULL AND transition_actor IS NOT NULL
        AND transition_prepared_at IS NOT NULL
        AND transition_stage IN ('PREPARED', 'DISPATCHED')
        AND ((transition_target = 'OPEN' AND status = 'CLOSED'
                AND transition_approval_id IS NOT NULL AND transition_evidence_set_id IS NULL)
            OR (transition_target = 'CLOSED' AND status = 'IN_PROGRESS'
                AND transition_approval_id IS NULL)))
);
