-- Existing history predates caller supplied keys. New API runs require a key, while legacy rows
-- remain nullable so the migration does not invent a business identity for old executions.
ALTER TABLE valuation_batches ADD COLUMN execution_key VARCHAR(100);
ALTER TABLE valuation_batches ADD COLUMN journal_count INTEGER;
CREATE UNIQUE INDEX uq_valuation_batches_execution_key ON valuation_batches (execution_key);

ALTER TABLE provision_batches ADD COLUMN execution_key VARCHAR(100);
ALTER TABLE provision_batches ADD COLUMN journal_count INTEGER;
CREATE UNIQUE INDEX uq_provision_batches_execution_key ON provision_batches (execution_key);

CREATE TABLE closing_financial_run_manifests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope VARCHAR(20) NOT NULL,
    batch_id BIGINT NOT NULL,
    commands_json TEXT NOT NULL,
    CONSTRAINT uq_closing_run_manifest UNIQUE (scope, batch_id)
);

CREATE TABLE closing_financial_run_locks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope VARCHAR(20) NOT NULL,
    execution_key VARCHAR(100) NOT NULL,
    CONSTRAINT uq_closing_run_lock UNIQUE (scope, execution_key)
);
