description = 'account-ecl-batch'

base {
    archivesName = 'account-ecl-batch'
}

dependencies {
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    implementation project(':ecl:ecl-core')
    implementation project(':shared-kernel')
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.flywaydb:flyway-core'
    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'org.postgresql:postgresql'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
    implementation 'com.github.ben-manes.caffeine:caffeine'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.batch:spring-batch-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // QueryDSL
    implementation "com.querydsl:querydsl-jpa:${querydslVersion}:jakarta"
}

bootJar { enabled = true }
jar {
    enabled = true
    archiveClassifier = 'plain'
}

springBoot {
    mainClass = 'com.ho.account.ecl.batch.AllowanceEclBatchApplication'
}

bootRun {
    systemProperty 'spring.profiles.active', System.getProperty('spring.profiles.active', 'local')
}

test {
    useJUnitPlatform()
    maxHeapSize = "128m" // 가상 메모리 부족 회피를 위한 극한 축소
    jvmArgs "-XX:+UseSerialGC", "-Xms32m" // Serial GC 적용으로 네이티브 메모리 절약
    testLogging {
        events "passed", "skipped", "failed", "standardOut", "standardError"
        showStandardStreams = true
        exceptionFormat = "full"
    }
}
