CREATE TABLE sales_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no VARCHAR(50) NOT NULL,
    customer_code VARCHAR(20) NOT NULL,
    issue_date DATE NOT NULL,
    due_date DATE NOT NULL,
    total_amount NUMERIC(19, 2) NOT NULL,
    tax_amount NUMERIC(19, 2) NOT NULL,
    net_amount NUMERIC(19, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    description VARCHAR(500),
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_sales_invoice_no UNIQUE (invoice_no),
    CONSTRAINT uk_sales_invoice_id_customer UNIQUE (id, customer_code),
    CONSTRAINT ck_sales_invoice_dates CHECK (due_date >= issue_date),
    CONSTRAINT ck_sales_invoice_amounts CHECK (
        net_amount > 0 AND tax_amount >= 0 AND total_amount > 0
        AND total_amount = net_amount + tax_amount),
    CONSTRAINT ck_sales_invoice_status CHECK (
        status IN ('ISSUED', 'PAID', 'PARTIAL_PAID', 'OVERDUE', 'CANCELLED'))
);

CREATE TABLE receivables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_invoice_id BIGINT NOT NULL,
    customer_code VARCHAR(50) NOT NULL,
    original_amount NUMERIC(19, 2) NOT NULL,
    outstanding_amount NUMERIC(19, 2) NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_receivable_sales_invoice
        FOREIGN KEY (sales_invoice_id, customer_code)
        REFERENCES sales_invoices(id, customer_code),
    CONSTRAINT uk_receivable_sales_invoice UNIQUE (sales_invoice_id),
    CONSTRAINT ck_receivable_amounts CHECK (
        original_amount > 0 AND outstanding_amount >= 0
        AND outstanding_amount <= original_amount),
    CONSTRAINT ck_receivable_status CHECK (
        (status = 'OPEN' AND outstanding_amount = original_amount)
        OR (status = 'PARTIAL_PAID'
            AND outstanding_amount > 0 AND outstanding_amount < original_amount)
        OR (status = 'PAID' AND outstanding_amount = 0)
        OR (status = 'OVERDUE' AND outstanding_amount > 0)
        OR status = 'WRITTEN_OFF')
);

CREATE TABLE collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_date DATE NOT NULL,
    customer_code VARCHAR(50) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    matched_amount NUMERIC(19, 2) NOT NULL,
    bank_account VARCHAR(100),
    virtual_account VARCHAR(100),
    reference_no VARCHAR(100),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_collection_amounts CHECK (
        amount > 0 AND matched_amount >= 0 AND matched_amount <= amount),
    CONSTRAINT ck_collection_status CHECK (
        (status = 'RECEIVED' AND matched_amount = 0)
        OR (status = 'UNMATCHED' AND matched_amount < amount)
        OR (status = 'PARTIAL_MATCHED'
            AND matched_amount > 0 AND matched_amount < amount)
        OR (status = 'MATCHED' AND matched_amount = amount)
        OR status = 'CANCELLED')
);

CREATE TABLE collection_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id BIGINT NOT NULL,
    receivable_id BIGINT NOT NULL,
    matched_amount NUMERIC(19, 2) NOT NULL,
    residual_collection_amount NUMERIC(19, 2) NOT NULL,
    residual_receivable_amount NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_collection_allocation_collection
        FOREIGN KEY (collection_id) REFERENCES collections(id),
    CONSTRAINT fk_collection_allocation_receivable
        FOREIGN KEY (receivable_id) REFERENCES receivables(id),
    CONSTRAINT ck_collection_allocation_amounts CHECK (
        matched_amount > 0 AND residual_collection_amount >= 0
        AND residual_receivable_amount >= 0)
);

CREATE TABLE matching_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name VARCHAR(100) NOT NULL,
    priority INTEGER NOT NULL,
    match_criteria VARCHAR(50) NOT NULL,
    tolerance_amount NUMERIC(19, 2),
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_matching_rule_name UNIQUE (rule_name),
    CONSTRAINT ck_matching_rule_priority CHECK (priority >= 0),
    CONSTRAINT ck_matching_rule_tolerance CHECK (
        tolerance_amount IS NULL OR tolerance_amount >= 0),
    CONSTRAINT ck_matching_rule_criteria CHECK (
        match_criteria IN ('REFERENCE_NO_EXACT', 'CUSTOMER_CODE', 'AMOUNT_EXACT',
                           'AMOUNT_FUZZY', 'VIRTUAL_ACCOUNT'))
);

CREATE TABLE unmatched_collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id BIGINT NOT NULL,
    reason VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    resolved_by VARCHAR(50),
    resolved_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_unmatched_collection UNIQUE (collection_id),
    CONSTRAINT fk_unmatched_collection
        FOREIGN KEY (collection_id) REFERENCES collections(id),
    CONSTRAINT ck_unmatched_collection_status CHECK (
        status IN ('PENDING', 'RESOLVED', 'IGNORED'))
);

CREATE INDEX idx_sales_invoice_customer_due
    ON sales_invoices(customer_code, due_date, status);
CREATE INDEX idx_sales_invoice_due_status
    ON sales_invoices(due_date, status);
CREATE INDEX idx_receivable_customer_due_status
    ON receivables(customer_code, due_date, status);
CREATE INDEX idx_receivable_due_status
    ON receivables(due_date, status);
CREATE INDEX idx_collection_customer_date_status
    ON collections(customer_code, collection_date, status);
CREATE INDEX idx_collection_status
    ON collections(status);
CREATE INDEX idx_collection_reference
    ON collections(reference_no);
CREATE INDEX idx_collection_allocation_collection
    ON collection_allocations(collection_id);
CREATE INDEX idx_collection_allocation_receivable
    ON collection_allocations(receivable_id);
CREATE INDEX idx_matching_rule_active_priority
    ON matching_rules(is_active, priority);
