-- Fixed Asset Schema

-- Table: fixed_assets
CREATE TABLE fixed_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_code VARCHAR(20) NOT NULL UNIQUE,
    asset_name VARCHAR(100) NOT NULL,
    account_code VARCHAR(50) NOT NULL, -- FK to account_subjects.code
    accumulated_account_code VARCHAR(50), -- FK to account_subjects.code
    expense_account_code VARCHAR(50), -- FK to account_subjects.code
    acquisition_date DATE NOT NULL,
    acquisition_cost DECIMAL(19, 2) NOT NULL,
    useful_life INTEGER NOT NULL,
    depreciation_method VARCHAR(20), -- STRAIGHT_LINE, DECLINING
    residual_value DECIMAL(19, 2),
    accumulated_depreciation DECIMAL(19, 2),
    current_book_value DECIMAL(19, 2) NOT NULL,
    depreciation_amount_per_period DECIMAL(19, 2),
    last_depreciation_date DATE,
    dept_code VARCHAR(50), -- FK to departments.code
    status VARCHAR(20), -- ACTIVE, DISPOSED, FULLY_DEPRECIATED
    created_at TIMESTAMP,
    FOREIGN KEY (account_code) REFERENCES account_subjects(code),
    FOREIGN KEY (accumulated_account_code) REFERENCES account_subjects(code),
    FOREIGN KEY (expense_account_code) REFERENCES account_subjects(code),
    FOREIGN KEY (dept_code) REFERENCES departments(code)
);
