-- IFRS 16 Lease Accounting Schema

-- Table: lease_contracts
CREATE TABLE lease_contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_no VARCHAR(20) NOT NULL UNIQUE,
    contract_name VARCHAR(100) NOT NULL,
    customer_code VARCHAR(50), -- Assuming BusinessPartner's businessPartnerCode is VARCHAR(50)
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    monthly_payment DECIMAL(19, 2) NOT NULL,
    payment_day INTEGER NOT NULL,
    dept_code VARCHAR(50), -- Assuming Department's code is VARCHAR(50)
    account_code VARCHAR(50), -- Assuming AccountSubject's code is VARCHAR(50)
    ifrs16_applicable BOOLEAN NOT NULL,
    short_term_lease BOOLEAN NOT NULL,
    low_value_lease BOOLEAN NOT NULL,
    discount_rate DECIMAL(5, 4),
    initial_right_of_use_asset_value DECIMAL(19, 2),
    initial_lease_liability_value DECIMAL(19, 2),
    status VARCHAR(20),
    created_at TIMESTAMP,
    FOREIGN KEY (customer_code) REFERENCES business_partners(business_partner_code),
    FOREIGN KEY (dept_code) REFERENCES departments(code),
    FOREIGN KEY (account_code) REFERENCES account_subjects(code)
);

-- Table: right_of_use_assets
CREATE TABLE right_of_use_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lease_contract_id BIGINT NOT NULL UNIQUE,
    asset_name VARCHAR(100) NOT NULL,
    recognition_date DATE NOT NULL,
    initial_value DECIMAL(19, 2) NOT NULL,
    current_book_value DECIMAL(19, 2) NOT NULL,
    accumulated_depreciation DECIMAL(19, 2) NOT NULL,
    depreciation_amount_per_period DECIMAL(19, 2) NOT NULL,
    status VARCHAR(20),
    created_at TIMESTAMP,
    FOREIGN KEY (lease_contract_id) REFERENCES lease_contracts(id)
);

-- Table: lease_liabilities
CREATE TABLE lease_liabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lease_contract_id BIGINT NOT NULL UNIQUE,
    recognition_date DATE NOT NULL,
    initial_value DECIMAL(19, 2) NOT NULL,
    current_value DECIMAL(19, 2) NOT NULL,
    accumulated_interest_expense DECIMAL(19, 2) NOT NULL,
    status VARCHAR(20),
    created_at TIMESTAMP,
    FOREIGN KEY (lease_contract_id) REFERENCES lease_contracts(id)
);

-- Table: lease_payment_schedules
CREATE TABLE lease_payment_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lease_contract_id BIGINT NOT NULL,
    payment_date DATE NOT NULL,
    scheduled_payment_amount DECIMAL(19, 2) NOT NULL,
    actual_payment_amount DECIMAL(19, 2),
    interest_portion DECIMAL(19, 2) NOT NULL,
    principal_portion DECIMAL(19, 2) NOT NULL,
    remaining_lease_liability DECIMAL(19, 2) NOT NULL,
    status VARCHAR(20),
    created_at TIMESTAMP,
    FOREIGN KEY (lease_contract_id) REFERENCES lease_contracts(id)
);
