-- O2C / Accounts Receivable Schema

-- Table: sales_invoices
CREATE TABLE sales_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no VARCHAR(50) NOT NULL UNIQUE,
    customer_code VARCHAR(50) NOT NULL, -- FK to business_partners.businessPartnerCode
    issue_date DATE NOT NULL,
    due_date DATE NOT NULL,
    total_amount DECIMAL(19, 2) NOT NULL,
    tax_amount DECIMAL(19, 2) NOT NULL,
    net_amount DECIMAL(19, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    journal_entry_id BIGINT, -- FK to journal_entries.id
    description VARCHAR(500),
    created_by VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    FOREIGN KEY (customer_code) REFERENCES business_partners(business_partner_code),
    FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id)
);

-- Table: receivables
CREATE TABLE receivables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_invoice_id BIGINT, -- FK to sales_invoices.id
    customer_code VARCHAR(50) NOT NULL, -- FK to business_partners.businessPartnerCode
    original_amount DECIMAL(19, 2) NOT NULL,
    outstanding_amount DECIMAL(19, 2) NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    journal_entry_id BIGINT, -- FK to journal_entries.id (optional, for direct AR entries)
    created_at TIMESTAMP NOT NULL,
    FOREIGN KEY (sales_invoice_id) REFERENCES sales_invoices(id),
    FOREIGN KEY (customer_code) REFERENCES business_partners(business_partner_code),
    FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id)
);

-- Table: collections
CREATE TABLE collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_date DATE NOT NULL,
    customer_code VARCHAR(50) NOT NULL, -- FK to business_partners.businessPartnerCode
    amount DECIMAL(19, 2) NOT NULL,
    bank_account VARCHAR(100),
    virtual_account VARCHAR(100),
    reference_no VARCHAR(100),
    status VARCHAR(20) NOT NULL,
    journal_entry_id BIGINT, -- FK to journal_entries.id
    created_at TIMESTAMP NOT NULL,
    FOREIGN KEY (customer_code) REFERENCES business_partners(business_partner_code),
    FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id)
);

-- Table: matching_rules
CREATE TABLE matching_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name VARCHAR(100) NOT NULL UNIQUE,
    priority INTEGER NOT NULL,
    match_criteria VARCHAR(50) NOT NULL,
    tolerance_amount DECIMAL(19, 2),
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL
);

-- Table: unmatched_collections
CREATE TABLE unmatched_collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id BIGINT NOT NULL UNIQUE, -- FK to collections.id
    reason VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    resolved_by VARCHAR(50),
    resolved_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    FOREIGN KEY (collection_id) REFERENCES collections(id)
);
