-- K-Bank 차세대 재무 시스템 스키마 설계 (Oracle/PostgreSQL 호환)

-- 1. ACCOUNT_SUBJECT (계정과목)
CREATE TABLE ACCOUNT_SUBJECT
(
    ACCOUNT_CODE VARCHAR2(20) NOT NULL PRIMARY KEY, -- 계정코드 (PK)
    ACCOUNT_NAME VARCHAR2(100) NOT NULL,            -- 계정명
    ACCOUNT_TYPE VARCHAR2(20) NOT NULL,            -- 계정유형 (자산, 부채, 자본, 수익, 비용)
    PARENT_ACCOUNT_CODE VARCHAR2(20),             -- 상위 계정코드 (FK)
    VALID_FROM_DATE DATE DEFAULT SYSDATE NOT NULL, -- 유효 시작일 (SCD2)
    VALID_TO_DATE DATE,                               -- 유효 종료일 (SCD2)
    IS_USED CHAR(1) DEFAULT 'Y' NOT NULL,        -- 사용여부 (Y/N)
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL   -- 감사 사용자
);

COMMENT ON TABLE ACCOUNT_SUBJECT IS '계정과목';
COMMENT ON COLUMN ACCOUNT_SUBJECT.ACCOUNT_CODE IS '계정코드';
COMMENT ON COLUMN ACCOUNT_SUBJECT.ACCOUNT_NAME IS '계정명';
COMMENT ON COLUMN ACCOUNT_SUBJECT.ACCOUNT_TYPE IS '계정유형';
COMMENT ON COLUMN ACCOUNT_SUBJECT.PARENT_ACCOUNT_CODE IS '상위 계정코드';
COMMENT ON COLUMN ACCOUNT_SUBJECT.VALID_FROM_DATE IS '유효 시작일 (SCD2)';
COMMENT ON COLUMN ACCOUNT_SUBJECT.VALID_TO_DATE IS '유효 종료일 (SCD2)';
COMMENT ON COLUMN ACCOUNT_SUBJECT.IS_USED IS '사용여부';
COMMENT ON COLUMN ACCOUNT_SUBJECT.CREATE_DATE IS '생성일';
COMMENT ON COLUMN ACCOUNT_SUBJECT.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN ACCOUNT_SUBJECT.AUDIT_USER IS '감사 사용자';

ALTER TABLE ACCOUNT_SUBJECT ADD CONSTRAINT FK_ACC_SUB_PARENT_ACC_CODE FOREIGN KEY (PARENT_ACCOUNT_CODE) REFERENCES ACCOUNT_SUBJECT (ACCOUNT_CODE);
CREATE INDEX IDX_ACC_SUB_PARENT_ACC_CODE ON ACCOUNT_SUBJECT (PARENT_ACCOUNT_CODE);
CREATE INDEX IDX_ACC_SUB_VALIDITY ON ACCOUNT_SUBJECT (VALID_FROM_DATE, VALID_TO_DATE);


-- 2. DEPARTMENT (부서)
CREATE TABLE DEPARTMENT
(
    DEPT_CODE VARCHAR2(20) NOT NULL PRIMARY KEY,   -- 부서코드 (PK)
    DEPT_NAME VARCHAR2(100) NOT NULL,              -- 부서명
    PARENT_DEPT_CODE VARCHAR2(20),                -- 상위 부서코드 (FK)
    VALID_FROM_DATE DATE DEFAULT SYSDATE NOT NULL, -- 유효 시작일 (SCD2)
    VALID_TO_DATE DATE,                               -- 유효 종료일 (SCD2)
    IS_USED CHAR(1) DEFAULT 'Y' NOT NULL,          -- 사용여부 (Y/N)
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL   -- 감사 사용자
);

COMMENT ON TABLE DEPARTMENT IS '부서';
COMMENT ON COLUMN DEPARTMENT.DEPT_CODE IS '부서코드';
COMMENT ON COLUMN DEPARTMENT.DEPT_NAME IS '부서명';
COMMENT ON COLUMN DEPARTMENT.PARENT_DEPT_CODE IS '상위 부서코드';
COMMENT ON COLUMN DEPARTMENT.VALID_FROM_DATE IS '유효 시작일 (SCD2)';
COMMENT ON COLUMN DEPARTMENT.VALID_TO_DATE IS '유효 종료일 (SCD2)';
COMMENT ON COLUMN DEPARTMENT.IS_USED IS '사용여부';
COMMENT ON COLUMN DEPARTMENT.CREATE_DATE IS '생성일';
COMMENT ON COLUMN DEPARTMENT.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN DEPARTMENT.AUDIT_USER IS '감사 사용자';

ALTER TABLE DEPARTMENT ADD CONSTRAINT FK_DEPT_PARENT_DEPT_CODE FOREIGN KEY (PARENT_DEPT_CODE) REFERENCES DEPARTMENT (DEPT_CODE);
CREATE INDEX IDX_DEPT_PARENT_DEPT_CODE ON DEPARTMENT (PARENT_DEPT_CODE);
CREATE INDEX IDX_DEPT_VALIDITY ON DEPARTMENT (VALID_FROM_DATE, VALID_TO_DATE);


-- 3. CUSTOMER (거래처)
CREATE TABLE CUSTOMER
(
    CUSTOMER_CODE VARCHAR2(20) NOT NULL PRIMARY KEY, -- 거래처코드 (PK)
    CUSTOMER_NAME VARCHAR2(100) NOT NULL,            -- 거래처명
    BUSINESS_REG_NO VARCHAR2(20),                 -- 사업자등록번호
    CONTACT_PERSON VARCHAR2(100),                 -- 담당자
    CONTACT_NO VARCHAR2(20),                      -- 연락처
    CUSTOMER_ACCOUNT_NO VARCHAR2(100),             -- 거래처 계좌번호 (암호화/토큰화/마스킹 필요)
    KYC_STATUS VARCHAR2(20) DEFAULT 'PENDING',     -- KYC 상태
    VALID_FROM_DATE DATE DEFAULT SYSDATE NOT NULL, -- 유효 시작일 (SCD2)
    VALID_TO_DATE DATE,                               -- 유효 종료일 (SCD2)
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL   -- 감사 사용자
);

COMMENT ON TABLE CUSTOMER IS '거래처';
COMMENT ON COLUMN CUSTOMER.CUSTOMER_CODE IS '거래처코드';
COMMENT ON COLUMN CUSTOMER.CUSTOMER_NAME IS '거래처명';
COMMENT ON COLUMN CUSTOMER.BUSINESS_REG_NO IS '사업자등록번호';
COMMENT ON COLUMN CUSTOMER.CONTACT_PERSON IS '담당자';
COMMENT ON COLUMN CUSTOMER.CONTACT_NO IS '연락처';
COMMENT ON COLUMN CUSTOMER.CUSTOMER_ACCOUNT_NO IS '거래처 계좌번호 (암호화/토큰화/마스킹 필요)';
COMMENT ON COLUMN CUSTOMER.KYC_STATUS IS 'KYC 상태';
COMMENT ON COLUMN CUSTOMER.VALID_FROM_DATE IS '유효 시작일 (SCD2)';
COMMENT ON COLUMN CUSTOMER.VALID_TO_DATE IS '유효 종료일 (SCD2)';
COMMENT ON COLUMN CUSTOMER.CREATE_DATE IS '생성일';
COMMENT ON COLUMN CUSTOMER.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN CUSTOMER.AUDIT_USER IS '감사 사용자';

CREATE UNIQUE INDEX UDX_CUSTOMER_BUSINESS_REG_NO ON CUSTOMER (BUSINESS_REG_NO);
CREATE INDEX IDX_CUSTOMER_VALIDITY ON CUSTOMER (VALID_FROM_DATE, VALID_TO_DATE);


-- 4. PRODUCT_MASTER (상품 마스터)
CREATE TABLE PRODUCT_MASTER
(
    PRODUCT_CODE VARCHAR2(20) NOT NULL PRIMARY KEY,              -- 상품 코드 (PK)
    PRODUCT_NAME VARCHAR2(100) NOT NULL,                         -- 상품명
    PRODUCT_GROUP VARCHAR2(50) NOT NULL,                         -- 상품군 (예: LOAN, DEPOSIT, DERIVATIVE)
    ACCOUNT_CLASS_CODE VARCHAR2(20) NOT NULL,                    -- 회계 분류 계정 (FK)
    VALID_FROM_DATE DATE DEFAULT SYSDATE NOT NULL,               -- 유효 시작일
    VALID_TO_DATE DATE,                                          -- 유효 종료일
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,         -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,         -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL,           -- 감사 사용자

    CONSTRAINT FK_PM_ACC_CLASS_CODE FOREIGN KEY (ACCOUNT_CLASS_CODE) REFERENCES ACCOUNT_SUBJECT (ACCOUNT_CODE)
);

COMMENT ON TABLE PRODUCT_MASTER IS '상품 마스터';
COMMENT ON COLUMN PRODUCT_MASTER.PRODUCT_CODE IS '상품 코드';
COMMENT ON COLUMN PRODUCT_MASTER.PRODUCT_NAME IS '상품명';
COMMENT ON COLUMN PRODUCT_MASTER.PRODUCT_GROUP IS '상품군';
COMMENT ON COLUMN PRODUCT_MASTER.ACCOUNT_CLASS_CODE IS '회계 분류 계정';
COMMENT ON COLUMN PRODUCT_MASTER.VALID_FROM_DATE IS '유효 시작일';
COMMENT ON COLUMN PRODUCT_MASTER.VALID_TO_DATE IS '유효 종료일';
COMMENT ON COLUMN PRODUCT_MASTER.CREATE_DATE IS '생성일';
COMMENT ON COLUMN PRODUCT_MASTER.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN PRODUCT_MASTER.AUDIT_USER IS '감사 사용자';

CREATE INDEX IDX_PM_PRODUCT_GROUP ON PRODUCT_MASTER (PRODUCT_GROUP);
CREATE INDEX IDX_PM_VALIDITY ON PRODUCT_MASTER (VALID_FROM_DATE, VALID_TO_DATE);

-- 5. CURRENCY (통화)
CREATE TABLE CURRENCY
(
    CURRENCY_CODE VARCHAR2(3) NOT NULL PRIMARY KEY,              -- 통화 코드 (ISO 4217) (PK)
    CURRENCY_NAME VARCHAR2(50) NOT NULL,                         -- 통화명
    SYMBOL VARCHAR2(10),                                         -- 통화 심볼 (예: ₩, $)
    VALID_FROM_DATE DATE DEFAULT SYSDATE NOT NULL,               -- 유효 시작일
    VALID_TO_DATE DATE,                                          -- 유효 종료일
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,         -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,         -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL            -- 감사 사용자
);

COMMENT ON TABLE CURRENCY IS '통화';
COMMENT ON COLUMN CURRENCY.CURRENCY_CODE IS '통화 코드';
COMMENT ON COLUMN CURRENCY.CURRENCY_NAME IS '통화명';
COMMENT ON COLUMN CURRENCY.SYMBOL IS '통화 심볼';
COMMENT ON COLUMN CURRENCY.VALID_FROM_DATE IS '유효 시작일';
COMMENT ON COLUMN CURRENCY.VALID_TO_DATE IS '유효 종료일';
COMMENT ON COLUMN CURRENCY.CREATE_DATE IS '생성일';
COMMENT ON COLUMN CURRENCY.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN CURRENCY.AUDIT_USER IS '감사 사용자';

CREATE INDEX IDX_CURRENCY_VALIDITY ON CURRENCY (VALID_FROM_DATE, VALID_TO_DATE);

-- 6. EXCHANGE_RATE (환율)
CREATE TABLE EXCHANGE_RATE
(
    BASE_CURRENCY_CODE VARCHAR2(3) NOT NULL,                     -- 기준 통화 코드 (PK, FK)
    TARGET_CURRENCY_CODE VARCHAR2(3) NOT NULL,                   -- 대상 통화 코드 (PK, FK)
    APPLY_DATE DATE NOT NULL,                                    -- 적용 일자 (PK)
    RATE NUMBER(19, 8) NOT NULL,                                 -- 환율 (소수점 8자리)
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,         -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,         -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL,           -- 감사 사용자

    CONSTRAINT PK_EXCHANGE_RATE PRIMARY KEY (BASE_CURRENCY_CODE, TARGET_CURRENCY_CODE, APPLY_DATE),
    CONSTRAINT FK_ER_BASE_CURRENCY_CODE FOREIGN KEY (BASE_CURRENCY_CODE) REFERENCES CURRENCY (CURRENCY_CODE),
    CONSTRAINT FK_ER_TARGET_CURRENCY_CODE FOREIGN KEY (TARGET_CURRENCY_CODE) REFERENCES CURRENCY (CURRENCY_CODE)
);

COMMENT ON TABLE EXCHANGE_RATE IS '환율';
COMMENT ON COLUMN EXCHANGE_RATE.BASE_CURRENCY_CODE IS '기준 통화 코드';
COMMENT ON COLUMN EXCHANGE_RATE.TARGET_CURRENCY_CODE IS '대상 통화 코드';
COMMENT ON COLUMN EXCHANGE_RATE.APPLY_DATE IS '적용 일자';
COMMENT ON COLUMN EXCHANGE_RATE.RATE IS '환율';
COMMENT ON COLUMN EXCHANGE_RATE.CREATE_DATE IS '생성일';
COMMENT ON COLUMN EXCHANGE_RATE.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN EXCHANGE_RATE.AUDIT_USER IS '감사 사용자';

CREATE UNIQUE INDEX UDX_EXCH_RATE_UNIQUE ON EXCHANGE_RATE (BASE_CURRENCY_CODE, TARGET_CURRENCY_CODE, APPLY_DATE);

-- 7. FISCAL_CALENDAR (회계 캘린더)
CREATE TABLE FISCAL_CALENDAR
(
    FISCAL_YEAR VARCHAR2(4) NOT NULL,                            -- 회계 연도 (PK)
    FISCAL_PERIOD VARCHAR2(2) NOT NULL,                          -- 회계 기간 (월) (PK)
    START_DATE DATE NOT NULL,                                    -- 기간 시작일
    END_DATE DATE NOT NULL,                                      -- 기간 종료일
    CLOSING_STATUS VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,         -- 마감 상태 (OPEN, CLOSED)
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,         -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,         -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL,           -- 감사 사용자

    CONSTRAINT PK_FISCAL_CALENDAR PRIMARY KEY (FISCAL_YEAR, FISCAL_PERIOD)
);

COMMENT ON TABLE FISCAL_CALENDAR IS '회계 캘린더';
COMMENT ON COLUMN FISCAL_CALENDAR.FISCAL_YEAR IS '회계 연도';
COMMENT ON COLUMN FISCAL_CALENDAR.FISCAL_PERIOD IS '회계 기간 (월)';
COMMENT ON COLUMN FISCAL_CALENDAR.START_DATE IS '기간 시작일';
COMMENT ON COLUMN FISCAL_CALENDAR.END_DATE IS '기간 종료일';
COMMENT ON COLUMN FISCAL_CALENDAR.CLOSING_STATUS IS '마감 상태';
COMMENT ON COLUMN FISCAL_CALENDAR.CREATE_DATE IS '생성일';
COMMENT ON COLUMN FISCAL_CALENDAR.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN FISCAL_CALENDAR.AUDIT_USER IS '감사 사용자';

CREATE UNIQUE INDEX UDX_FISCAL_CAL_UNIQUE ON FISCAL_CALENDAR (FISCAL_YEAR, FISCAL_PERIOD);

-- 8. TAX_MASTER (세무 마스터)
CREATE TABLE TAX_MASTER
(
    TAX_CODE VARCHAR2(20) NOT NULL PRIMARY KEY,                  -- 세목 코드 (PK)
    TAX_NAME VARCHAR2(100) NOT NULL,                             -- 세목명
    TAX_TYPE VARCHAR2(20) NOT NULL,                              -- 세금 유형 (예: VAT, WITHHOLDING)
    RATE NUMBER(5, 4) NOT NULL,                                  -- 세율 (소수점 4자리)
    APPLY_START_DATE DATE NOT NULL,                              -- 적용 시작일
    APPLY_END_DATE DATE,                                         -- 적용 종료일
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,         -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,         -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL            -- 감사 사용자
);

COMMENT ON TABLE TAX_MASTER IS '세무 마스터';
COMMENT ON COLUMN TAX_MASTER.TAX_CODE IS '세목 코드';
COMMENT ON COLUMN TAX_MASTER.TAX_NAME IS '세목명';
COMMENT ON COLUMN TAX_MASTER.TAX_TYPE IS '세금 유형';
COMMENT ON COLUMN TAX_MASTER.RATE IS '세율';
COMMENT ON COLUMN TAX_MASTER.APPLY_START_DATE IS '적용 시작일';
COMMENT ON COLUMN TAX_MASTER.APPLY_END_DATE IS '적용 종료일';
COMMENT ON COLUMN TAX_MASTER.CREATE_DATE IS '생성일';
COMMENT ON COLUMN TAX_MASTER.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN TAX_MASTER.AUDIT_USER IS '감사 사용자';

CREATE INDEX IDX_TAX_MASTER_APPLY_DATE ON TAX_MASTER (APPLY_START_DATE, APPLY_END_DATE);

-- 9. MASTER_APPROVAL (마스터 승인 이력)
CREATE TABLE MASTER_APPROVAL
(
    APPROVAL_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 승인 ID (PK)
    MASTER_TYPE VARCHAR2(50) NOT NULL,                                     -- 마스터 유형 (예: ACCOUNT_SUBJECT, PRODUCT_MASTER)
    MASTER_KEY VARCHAR2(100) NOT NULL,                                     -- 마스터 고유 키 (예: ACCOUNT_CODE)
    CHANGE_REQUEST_TYPE VARCHAR2(20) NOT NULL,                             -- 변경 요청 유형 (CREATE, UPDATE, DELETE)
    REQUEST_USER VARCHAR2(50) NOT NULL,                                    -- 요청 사용자
    REQUEST_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,                  -- 요청일
    APPROVER_USER VARCHAR2(50),                                            -- 승인 사용자
    APPROVAL_DATE TIMESTAMP,                                               -- 승인일
    APPROVAL_STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,               -- 승인 상태 (PENDING, APPROVED, REJECTED)
    REMARKS VARCHAR2(500),                                                 -- 비고
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,                   -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,                   -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL                      -- 감사 사용자
);

COMMENT ON TABLE MASTER_APPROVAL IS '마스터 승인 이력';
COMMENT ON COLUMN MASTER_APPROVAL.APPROVAL_ID IS '승인 ID';
COMMENT ON COLUMN MASTER_APPROVAL.MASTER_TYPE IS '마스터 유형';
COMMENT ON COLUMN MASTER_APPROVAL.MASTER_KEY IS '마스터 고유 키';
COMMENT ON COLUMN MASTER_APPROVAL.CHANGE_REQUEST_TYPE IS '변경 요청 유형';
COMMENT ON COLUMN MASTER_APPROVAL.REQUEST_USER IS '요청 사용자';
COMMENT ON COLUMN MASTER_APPROVAL.REQUEST_DATE IS '요청일';
COMMENT ON COLUMN MASTER_APPROVAL.APPROVER_USER IS '승인 사용자';
COMMENT ON COLUMN MASTER_APPROVAL.APPROVAL_DATE IS '승인일';
COMMENT ON COLUMN MASTER_APPROVAL.APPROVAL_STATUS IS '승인 상태';
COMMENT ON COLUMN MASTER_APPROVAL.REMARKS IS '비고';
COMMENT ON COLUMN MASTER_APPROVAL.CREATE_DATE IS '생성일';
COMMENT ON COLUMN MASTER_APPROVAL.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN MASTER_APPROVAL.AUDIT_USER IS '감사 사용자';

CREATE INDEX IDX_MA_MASTER_KEY ON MASTER_APPROVAL (MASTER_TYPE, MASTER_KEY);
CREATE INDEX IDX_MA_REQUEST_USER ON MASTER_APPROVAL (REQUEST_USER);

-- 10. FIXED_ASSETS (고정자산)
CREATE TABLE FIXED_ASSETS
(
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 고정자산 ID (PK)
    ASSET_CODE VARCHAR2(20) UNIQUE NOT NULL,                       -- 자산코드 (고유)
    ASSET_NAME VARCHAR2(100) NOT NULL,                             -- 자산명
    ACCOUNT_CODE VARCHAR2(20) NOT NULL,                           -- 자산 계정코드 (FK)
    ACCUMULATED_ACCOUNT_CODE VARCHAR2(20),                        -- 감가상각누계액 계정코드 (FK)
    EXPENSE_ACCOUNT_CODE VARCHAR2(20),                            -- 감가상각비 계정코드 (FK)
    ACQUISITION_DATE DATE NOT NULL,                               -- 취득일
    ACQUISITION_COST NUMBER(19, 2) NOT NULL,                      -- 취득원가
    USEFUL_LIFE NUMBER(3) NOT NULL,                               -- 내용연수 (년)
    DEPRECIATION_METHOD VARCHAR2(20),                             -- 감가상각방법 (STRAIGHT_LINE, DECLINING)
    RESIDUAL_VALUE NUMBER(19, 2) DEFAULT 0.00,                    -- 잔존가치
    ACCUMULATED_DEPRECIATION NUMBER(19, 2) DEFAULT 0.00,          -- 현재까지의 감가상각누계액
    DEPT_CODE VARCHAR2(20),                                       -- 관리 부서코드 (FK)
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,               -- 상태 (ACTIVE, DISPOSED, FULLY_DEPRECIATED)
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,          -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,          -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL,            -- 감사 사용자

    CONSTRAINT FK_FA_ACCOUNT_CODE FOREIGN KEY (ACCOUNT_CODE) REFERENCES ACCOUNT_SUBJECT (ACCOUNT_CODE),
    CONSTRAINT FK_FA_ACCUMULATED_CODE FOREIGN KEY (ACCUMULATED_ACCOUNT_CODE) REFERENCES ACCOUNT_SUBJECT (ACCOUNT_CODE),
    CONSTRAINT FK_FA_EXPENSE_CODE FOREIGN KEY (EXPENSE_ACCOUNT_CODE) REFERENCES ACCOUNT_SUBJECT (ACCOUNT_CODE),
    CONSTRAINT FK_FA_DEPT_CODE FOREIGN KEY (DEPT_CODE) REFERENCES DEPARTMENT (DEPT_CODE)
);

COMMENT ON TABLE FIXED_ASSETS IS '고정자산';
COMMENT ON COLUMN FIXED_ASSETS.ID IS '고정자산 ID';
COMMENT ON COLUMN FIXED_ASSETS.ASSET_CODE IS '자산코드';
COMMENT ON COLUMN FIXED_ASSETS.ASSET_NAME IS '자산명';
COMMENT ON COLUMN FIXED_ASSETS.ACCOUNT_CODE IS '자산 계정코드';
COMMENT ON COLUMN FIXED_ASSETS.ACCUMULATED_ACCOUNT_CODE IS '감가상각누계액 계정코드';
COMMENT ON COLUMN FIXED_ASSETS.EXPENSE_ACCOUNT_CODE IS '감가상각비 계정코드';
COMMENT ON COLUMN FIXED_ASSETS.ACQUISITION_DATE IS '취득일';
COMMENT ON COLUMN FIXED_ASSETS.ACQUISITION_COST IS '취득원가';
COMMENT ON COLUMN FIXED_ASSETS.USEFUL_LIFE IS '내용연수 (년)';
COMMENT ON COLUMN FIXED_ASSETS.DEPRECIATION_METHOD IS '감가상각방법';
COMMENT ON COLUMN FIXED_ASSETS.RESIDUAL_VALUE IS '잔존가치';
COMMENT ON COLUMN FIXED_ASSETS.ACCUMULATED_DEPRECIATION IS '현재까지의 감가상각누계액';
COMMENT ON COLUMN FIXED_ASSETS.DEPT_CODE IS '관리 부서코드';
COMMENT ON COLUMN FIXED_ASSETS.STATUS IS '상태';
COMMENT ON COLUMN FIXED_ASSETS.CREATE_DATE IS '생성일';
COMMENT ON COLUMN FIXED_ASSETS.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN FIXED_ASSETS.AUDIT_USER IS '감사 사용자';

CREATE INDEX IDX_FA_ASSET_CODE ON FIXED_ASSETS (ASSET_CODE);
CREATE INDEX IDX_FA_ACCOUNT_CODE ON FIXED_ASSETS (ACCOUNT_CODE);
CREATE INDEX IDX_FA_DEPT_CODE ON FIXED_ASSETS (DEPT_CODE);


-- 11. LEASE_CONTRACTS (리스 계약)
CREATE TABLE LEASE_CONTRACTS
(
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 리스 계약 ID (PK)
    CONTRACT_NO VARCHAR2(20) UNIQUE NOT NULL,                      -- 계약번호 (고유)
    CONTRACT_NAME VARCHAR2(100) NOT NULL,                          -- 계약명
    LESSOR_CUSTOMER_CODE VARCHAR2(20) NOT NULL,                    -- 리스 제공자 (거래처) 코드 (FK)
    START_DATE DATE NOT NULL,                                      -- 시작일
    END_DATE DATE NOT NULL,                                        -- 종료일
    MONTHLY_PAYMENT NUMBER(19, 2) NOT NULL,                        -- 월 리스료
    PAYMENT_DAY NUMBER(2) NOT NULL,                                -- 매월 지급일 (예: 25일)
    DEPT_CODE VARCHAR2(20),                                        -- 관리 부서코드 (FK)
    EXPENSE_ACCOUNT_CODE VARCHAR2(20),                             -- 리스료 비용 계정코드 (FK)
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,                -- 상태 (ACTIVE, TERMINATED, EXPIRED)
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL,             -- 감사 사용자

    CONSTRAINT FK_LC_LESSOR_CUSTOMER_CODE FOREIGN KEY (LESSOR_CUSTOMER_CODE) REFERENCES CUSTOMER (CUSTOMER_CODE),
    CONSTRAINT FK_LC_DEPT_CODE FOREIGN KEY (DEPT_CODE) REFERENCES DEPARTMENT (DEPT_CODE),
    CONSTRAINT FK_LC_EXPENSE_ACCOUNT_CODE FOREIGN KEY (EXPENSE_ACCOUNT_CODE) REFERENCES ACCOUNT_SUBJECT (ACCOUNT_CODE)
);

COMMENT ON TABLE LEASE_CONTRACTS IS '리스 계약';
COMMENT ON COLUMN LEASE_CONTRACTS.ID IS '리스 계약 ID';
COMMENT ON COLUMN LEASE_CONTRACTS.CONTRACT_NO IS '계약번호';
COMMENT ON COLUMN LEASE_CONTRACTS.CONTRACT_NAME IS '계약명';
COMMENT ON COLUMN LEASE_CONTRACTS.LESSOR_CUSTOMER_CODE IS '리스 제공자 (거래처) 코드';
COMMENT ON COLUMN LEASE_CONTRACTS.START_DATE IS '시작일';
COMMENT ON COLUMN LEASE_CONTRACTS.END_DATE IS '종료일';
COMMENT ON COLUMN LEASE_CONTRACTS.MONTHLY_PAYMENT IS '월 리스료';
COMMENT ON COLUMN LEASE_CONTRACTS.PAYMENT_DAY IS '매월 지급일';
COMMENT ON COLUMN LEASE_CONTRACTS.DEPT_CODE IS '관리 부서코드';
COMMENT ON COLUMN LEASE_CONTRACTS.EXPENSE_ACCOUNT_CODE IS '리스료 비용 계정코드';
COMMENT ON COLUMN LEASE_CONTRACTS.STATUS IS '상태';
COMMENT ON COLUMN LEASE_CONTRACTS.CREATE_DATE IS '생성일';
COMMENT ON COLUMN LEASE_CONTRACTS.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN LEASE_CONTRACTS.AUDIT_USER IS '감사 사용자';

CREATE INDEX IDX_LC_CONTRACT_NO ON LEASE_CONTRACTS (CONTRACT_NO);
CREATE INDEX IDX_LC_LESSOR_CUSTOMER_CODE ON LEASE_CONTRACTS (LESSOR_CUSTOMER_CODE);
CREATE INDEX IDX_LC_DEPT_CODE ON LEASE_CONTRACTS (DEPT_CODE);
CREATE INDEX IDX_LC_EXPENSE_ACCOUNT_CODE ON LEASE_CONTRACTS (EXPENSE_ACCOUNT_CODE);


-- 12. UNSETTLED_ITEMS (미지급금/미수금)
CREATE TABLE UNSETTLED_ITEMS
(
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 미지급/미수 항목 ID (PK)
    ITEM_NO VARCHAR2(20) UNIQUE NOT NULL,                          -- 항목번호 (고유)
    CUSTOMER_CODE VARCHAR2(20) NOT NULL,                           -- 거래처코드 (FK)
    AMOUNT NUMBER(19, 2) NOT NULL,                                 -- 미지급/미수 금액
    OCCURRENCE_DATE DATE NOT NULL,                                 -- 발생일
    DUE_DATE DATE NOT NULL,                                        -- 예정일
    STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,               -- 처리상태 (PENDING, COMPLETED, OVERDUE)
    RELATED_JOURNAL_NO VARCHAR2(20),                               -- 관련 전표번호 (FK)
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL,             -- 감사 사용자

    CONSTRAINT FK_UI_CUSTOMER_CODE FOREIGN KEY (CUSTOMER_CODE) REFERENCES CUSTOMER (CUSTOMER_CODE)
    -- CONSTRAINT FK_UI_RELATED_JOURNAL_NO FOREIGN KEY (RELATED_JOURNAL_NO) REFERENCES JOURNAL_ENTRY (JOURNAL_NO) -- JOURNAL_ENTRY 테이블 생성 후 추가
);

COMMENT ON TABLE UNSETTLED_ITEMS IS '미지급금/미수금';
COMMENT ON COLUMN UNSETTLED_ITEMS.ID IS '미지급/미수 항목 ID';
COMMENT ON COLUMN UNSETTLED_ITEMS.ITEM_NO IS '항목번호';
COMMENT ON COLUMN UNSETTLED_ITEMS.CUSTOMER_CODE IS '거래처코드';
COMMENT ON COLUMN UNSETTLED_ITEMS.AMOUNT IS '미지급/미수 금액';
COMMENT ON COLUMN UNSETTLED_ITEMS.OCCURRENCE_DATE IS '발생일';
COMMENT ON COLUMN UNSETTLED_ITEMS.DUE_DATE IS '예정일';
COMMENT ON COLUMN UNSETTLED_ITEMS.STATUS IS '처리상태';
COMMENT ON COLUMN UNSETTLED_ITEMS.RELATED_JOURNAL_NO IS '관련 전표번호';
COMMENT ON COLUMN UNSETTLED_ITEMS.CREATE_DATE IS '생성일';
COMMENT ON COLUMN UNSETTLED_ITEMS.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN UNSETTLED_ITEMS.AUDIT_USER IS '감사 사용자';

CREATE INDEX IDX_UI_ITEM_NO ON UNSETTLED_ITEMS (ITEM_NO);
CREATE INDEX IDX_UI_CUSTOMER_CODE ON UNSETTLED_ITEMS (CUSTOMER_CODE);


-- 13. JOURNAL_ENTRY (전표)
CREATE TABLE JOURNAL_ENTRY
(
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 전표 ID (PK)
    JOURNAL_NO VARCHAR2(20) UNIQUE NOT NULL,                       -- 전표번호 (고유)
    JOURNAL_DATE DATE NOT NULL,                                    -- 전표일자
    TYPE VARCHAR2(20) NOT NULL,                                    -- 유형 (GENERAL, CLOSING)
    DEPT_CODE VARCHAR2(20),                                       -- 생성 부서코드 (FK)
    CREATED_BY VARCHAR2(50) NOT NULL,                              -- 생성자
    STATUS VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,                 -- 상태 (DRAFT, POSTED, CANCELED)
    TOTAL_DEBIT NUMBER(19, 2) NOT NULL,                            -- 차변 총액
    TOTAL_CREDIT NUMBER(19, 2) NOT NULL,                           -- 대변 총액
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL,             -- 감사 사용자

    CONSTRAINT FK_JE_DEPT_CODE FOREIGN KEY (DEPT_CODE) REFERENCES DEPARTMENT (DEPT_CODE),
    CONSTRAINT CHK_JE_DEBIT_CREDIT CHECK (TOTAL_DEBIT = TOTAL_CREDIT) -- 차변과 대변은 항상 일치해야 함
);

COMMENT ON TABLE JOURNAL_ENTRY IS '전표';
COMMENT ON COLUMN JOURNAL_ENTRY.ID IS '전표 ID';
COMMENT ON COLUMN JOURNAL_ENTRY.JOURNAL_NO IS '전표번호';
COMMENT ON COLUMN JOURNAL_ENTRY.JOURNAL_DATE IS '전표일자';
COMMENT ON COLUMN JOURNAL_ENTRY.TYPE IS '유형';
COMMENT ON COLUMN JOURNAL_ENTRY.DEPT_CODE IS '생성 부서코드';
COMMENT ON COLUMN JOURNAL_ENTRY.CREATED_BY IS '생성자';
COMMENT ON COLUMN JOURNAL_ENTRY.STATUS IS '상태';
COMMENT ON COLUMN JOURNAL_ENTRY.TOTAL_DEBIT IS '차변 총액';
COMMENT ON COLUMN JOURNAL_ENTRY.TOTAL_CREDIT IS '대변 총액';
COMMENT ON COLUMN JOURNAL_ENTRY.CREATE_DATE IS '생성일';
COMMENT ON COLUMN JOURNAL_ENTRY.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN JOURNAL_ENTRY.AUDIT_USER IS '감사 사용자';

CREATE INDEX IDX_JE_JOURNAL_NO ON JOURNAL_ENTRY (JOURNAL_NO);
CREATE INDEX IDX_JE_JOURNAL_DATE ON JOURNAL_ENTRY (JOURNAL_DATE);
CREATE INDEX IDX_JE_DEPT_CODE ON JOURNAL_ENTRY (DEPT_CODE);


-- UNSETTLED_ITEMS 테이블에 JOURNAL_ENTRY FK 추가 (순환 참조 방지)
ALTER TABLE UNSETTLED_ITEMS ADD CONSTRAINT FK_UI_RELATED_JOURNAL_NO FOREIGN KEY (RELATED_JOURNAL_NO) REFERENCES JOURNAL_ENTRY (JOURNAL_NO);
CREATE INDEX IDX_UI_RELATED_JOURNAL_NO ON UNSETTLED_ITEMS (RELATED_JOURNAL_NO);


-- 14. JOURNAL_DETAIL (전표 상세)
CREATE TABLE JOURNAL_DETAIL
(
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 전표 상세 ID (PK)
    JOURNAL_NO VARCHAR2(20) NOT NULL,                              -- 전표번호 (FK)
    DETAIL_NO NUMBER(5) NOT NULL,                                  -- 상세번호 (전표 내 순번)
    ACCOUNT_CODE VARCHAR2(20) NOT NULL,                           -- 계정코드 (FK)
    DEBIT_AMOUNT NUMBER(19, 2) DEFAULT 0.00 NOT NULL,              -- 차변 금액
    CREDIT_AMOUNT NUMBER(19, 2) DEFAULT 0.00 NOT NULL,             -- 대변 금액
    DESCRIPTION VARCHAR2(500),                                     -- 적요
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL,             -- 감사 사용자

    CONSTRAINT FK_JD_JOURNAL_NO FOREIGN KEY (JOURNAL_NO) REFERENCES JOURNAL_ENTRY (JOURNAL_NO),
    CONSTRAINT FK_JD_ACCOUNT_CODE FOREIGN KEY (ACCOUNT_CODE) REFERENCES ACCOUNT_SUBJECT (ACCOUNT_CODE),
    CONSTRAINT UDX_JD_JOURNAL_DETAIL UNIQUE (JOURNAL_NO, DETAIL_NO) -- 전표 내 상세번호 고유성
);

COMMENT ON TABLE JOURNAL_DETAIL IS '전표 상세';
COMMENT ON COLUMN JOURNAL_DETAIL.ID IS '전표 상세 ID';
COMMENT ON COLUMN JOURNAL_DETAIL.JOURNAL_NO IS '전표번호';
COMMENT ON COLUMN JOURNAL_DETAIL.DETAIL_NO IS '상세번호';
COMMENT ON COLUMN JOURNAL_DETAIL.ACCOUNT_CODE IS '계정코드';
COMMENT ON COLUMN JOURNAL_DETAIL.DEBIT_AMOUNT IS '차변 금액';
COMMENT ON COLUMN JOURNAL_DETAIL.CREDIT_AMOUNT IS '대변 금액';
COMMENT ON COLUMN JOURNAL_DETAIL.DESCRIPTION IS '적요';
COMMENT ON COLUMN JOURNAL_DETAIL.CREATE_DATE IS '생성일';
COMMENT ON COLUMN JOURNAL_DETAIL.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN JOURNAL_DETAIL.AUDIT_USER IS '감사 사용자';

CREATE INDEX IDX_JD_JOURNAL_NO ON JOURNAL_DETAIL (JOURNAL_NO);
CREATE INDEX IDX_JD_ACCOUNT_CODE ON JOURNAL_DETAIL (ACCOUNT_CODE);


-- 15. BUDGET (예산)
CREATE TABLE BUDGET
(
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 예산 ID (PK)
    BUDGET_CODE VARCHAR2(20) UNIQUE NOT NULL,                      -- 예산코드 (고유)
    BUDGET_NAME VARCHAR2(100) NOT NULL,                            -- 예산명
    FISCAL_YEAR VARCHAR2(4) NOT NULL,                              -- 회계연도
    DEPT_CODE VARCHAR2(20) NOT NULL,                               -- 부서코드 (FK)
    ACCOUNT_CODE VARCHAR2(20) NOT NULL,                           -- 계정코드 (FK)
    ALLOCATED_AMOUNT NUMBER(19, 2) NOT NULL,                       -- 할당금액
    EXECUTED_AMOUNT NUMBER(19, 2) DEFAULT 0.00 NOT NULL,           -- 집행금액
    REMAINING_AMOUNT NUMBER(19, 2) NOT NULL,                       -- 잔여금액
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,                -- 상태 (ACTIVE, CLOSED)
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL,             -- 감사 사용자

    CONSTRAINT FK_BGT_DEPT_CODE FOREIGN KEY (DEPT_CODE) REFERENCES DEPARTMENT (DEPT_CODE),
    CONSTRAINT FK_BGT_ACCOUNT_CODE FOREIGN KEY (ACCOUNT_CODE) REFERENCES ACCOUNT_SUBJECT (ACCOUNT_CODE),
    CONSTRAINT UDX_BGT_FISCAL_DEPT_ACC UNIQUE (FISCAL_YEAR, DEPT_CODE, ACCOUNT_CODE) -- 회계연도, 부서, 계정과목별 예산 고유성
);

COMMENT ON TABLE BUDGET IS '예산';
COMMENT ON COLUMN BUDGET.ID IS '예산 ID';
COMMENT ON COLUMN BUDGET.BUDGET_CODE IS '예산코드';
COMMENT ON COLUMN BUDGET.BUDGET_NAME IS '예산명';
COMMENT ON COLUMN BUDGET.FISCAL_YEAR IS '회계연도';
COMMENT ON COLUMN BUDGET.DEPT_CODE IS '부서코드';
COMMENT ON COLUMN BUDGET.ACCOUNT_CODE IS '계정코드';
COMMENT ON COLUMN BUDGET.ALLOCATED_AMOUNT IS '할당금액';
COMMENT ON COLUMN BUDGET.EXECUTED_AMOUNT IS '집행금액';
COMMENT ON COLUMN BUDGET.REMAINING_AMOUNT IS '잔여금액';
COMMENT ON COLUMN BUDGET.STATUS IS '상태';
COMMENT ON COLUMN BUDGET.CREATE_DATE IS '생성일';
COMMENT ON COLUMN BUDGET.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN BUDGET.AUDIT_USER IS '감사 사용자';

CREATE INDEX IDX_BGT_BUDGET_CODE ON BUDGET (BUDGET_CODE);
CREATE INDEX IDX_BGT_FISCAL_YEAR ON BUDGET (FISCAL_YEAR);
CREATE INDEX IDX_BGT_DEPT_CODE ON BUDGET (DEPT_CODE);
CREATE INDEX IDX_BGT_ACCOUNT_CODE ON BUDGET (ACCOUNT_CODE);


-- 16. EXPENDITURE_RESOLUTION (지출결의)
CREATE TABLE EXPENDITURE_RESOLUTION
(
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 지출결의 ID (PK)
    RESOLUTION_NO VARCHAR2(20) UNIQUE NOT NULL,                    -- 결의번호 (고유)
    RESOLUTION_DATE DATE NOT NULL,                                 -- 결의일자
    REQUESTING_DEPT_CODE VARCHAR2(20),                            -- 신청 부서코드 (FK)
    REQUESTER VARCHAR2(50) NOT NULL,                               -- 신청자
    TOTAL_AMOUNT NUMBER(19, 2) NOT NULL,                           -- 총금액
    APPROVAL_STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,      -- 승인상태 (PENDING, APPROVED, REJECTED)
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL,             -- 감사 사용자

    CONSTRAINT FK_ER_REQUESTING_DEPT_CODE FOREIGN KEY (REQUESTING_DEPT_CODE) REFERENCES DEPARTMENT (DEPT_CODE)
);

COMMENT ON TABLE EXPENDITURE_RESOLUTION IS '지출결의';
COMMENT ON COLUMN EXPENDITURE_RESOLUTION.ID IS '지출결의 ID';
COMMENT ON COLUMN EXPENDITURE_RESOLUTION.RESOLUTION_NO IS '결의번호';
COMMENT ON COLUMN EXPENDITURE_RESOLUTION.RESOLUTION_DATE IS '결의일자';
COMMENT ON COLUMN EXPENDITURE_RESOLUTION.REQUESTING_DEPT_CODE IS '신청 부서코드';
COMMENT ON COLUMN EXPENDITURE_RESOLUTION.REQUESTER IS '신청자';
COMMENT ON COLUMN EXPENDITURE_RESOLUTION.TOTAL_AMOUNT IS '총금액';
COMMENT ON COLUMN EXPENDITURE_RESOLUTION.APPROVAL_STATUS IS '승인상태';
COMMENT ON COLUMN EXPENDITURE_RESOLUTION.CREATE_DATE IS '생성일';
COMMENT ON COLUMN EXPENDITURE_RESOLUTION.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN EXPENDITURE_RESOLUTION.AUDIT_USER IS '감사 사용자';

CREATE INDEX IDX_ER_RESOLUTION_NO ON EXPENDITURE_RESOLUTION (RESOLUTION_NO);
CREATE INDEX IDX_ER_REQUESTING_DEPT_CODE ON EXPENDITURE_RESOLUTION (REQUESTING_DEPT_CODE);


-- 17. EXPENDITURE_DETAIL (지출 상세)
CREATE TABLE EXPENDITURE_DETAIL
(
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 지출 상세 ID (PK)
    RESOLUTION_NO VARCHAR2(20) NOT NULL,                           -- 결의번호 (FK)
    DETAIL_NO NUMBER(5) NOT NULL,                                  -- 상세번호 (결의 내 순번)
    ACCOUNT_CODE VARCHAR2(20) NOT NULL,                           -- 계정코드 (FK)
    AMOUNT NUMBER(19, 2) NOT NULL,                                 -- 금액
    DESCRIPTION VARCHAR2(500),                                     -- 적요
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL,             -- 감사 사용자

    CONSTRAINT FK_ED_RESOLUTION_NO FOREIGN KEY (RESOLUTION_NO) REFERENCES EXPENDITURE_RESOLUTION (RESOLUTION_NO),
    CONSTRAINT FK_ED_ACCOUNT_CODE FOREIGN KEY (ACCOUNT_CODE) REFERENCES ACCOUNT_SUBJECT (ACCOUNT_CODE),
    CONSTRAINT UDX_ED_RESOLUTION_DETAIL UNIQUE (RESOLUTION_NO, DETAIL_NO) -- 결의 내 상세번호 고유성
);

COMMENT ON TABLE EXPENDITURE_DETAIL IS '지출 상세';
COMMENT ON COLUMN EXPENDITURE_DETAIL.ID IS '지출 상세 ID';
COMMENT ON COLUMN EXPENDITURE_DETAIL.RESOLUTION_NO IS '결의번호';
COMMENT ON COLUMN EXPENDITURE_DETAIL.DETAIL_NO IS '상세번호';
COMMENT ON COLUMN EXPENDITURE_DETAIL.ACCOUNT_CODE IS '계정코드';
COMMENT ON COLUMN EXPENDITURE_DETAIL.AMOUNT IS '금액';
COMMENT ON COLUMN EXPENDITURE_DETAIL.DESCRIPTION IS '적요';
COMMENT ON COLUMN EXPENDITURE_DETAIL.CREATE_DATE IS '생성일';
COMMENT ON COLUMN EXPENDITURE_DETAIL.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN EXPENDITURE_DETAIL.AUDIT_USER IS '감사 사용자';

CREATE INDEX IDX_ED_RESOLUTION_NO ON EXPENDITURE_DETAIL (RESOLUTION_NO);
CREATE INDEX IDX_ED_ACCOUNT_CODE ON EXPENDITURE_DETAIL (ACCOUNT_CODE);


-- 18. PAYMENT (지급)
CREATE TABLE PAYMENT
(
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 지급 ID (PK)
    PAYMENT_NO VARCHAR2(20) UNIQUE NOT NULL,                       -- 지급번호 (고유)
    PAYMENT_DATE DATE NOT NULL,                                    -- 지급일자
    CUSTOMER_CODE VARCHAR2(20) NOT NULL,                           -- 거래처코드 (FK)
    PAYMENT_AMOUNT NUMBER(19, 2) NOT NULL,                         -- 지급금액
    PAYMENT_METHOD VARCHAR2(50) NOT NULL,                          -- 지급수단
    RELATED_RESOLUTION_NO VARCHAR2(20),                            -- 관련 결의번호 (FK)
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL,             -- 감사 사용자

    CONSTRAINT FK_PMT_CUSTOMER_CODE FOREIGN KEY (CUSTOMER_CODE) REFERENCES CUSTOMER (CUSTOMER_CODE),
    CONSTRAINT FK_PMT_RESOLUTION_NO FOREIGN KEY (RELATED_RESOLUTION_NO) REFERENCES EXPENDITURE_RESOLUTION (RESOLUTION_NO)
);

COMMENT ON TABLE PAYMENT IS '지급';
COMMENT ON COLUMN PAYMENT.ID IS '지급 ID';
COMMENT ON COLUMN PAYMENT.PAYMENT_NO IS '지급번호';
COMMENT ON COLUMN PAYMENT.PAYMENT_DATE IS '지급일자';
COMMENT ON COLUMN PAYMENT.CUSTOMER_CODE IS '거래처코드';
COMMENT ON COLUMN PAYMENT.PAYMENT_AMOUNT IS '지급금액';
COMMENT ON COLUMN PAYMENT.PAYMENT_METHOD IS '지급수단';
COMMENT ON COLUMN PAYMENT.RELATED_RESOLUTION_NO IS '관련 결의번호';
COMMENT ON COLUMN PAYMENT.CREATE_DATE IS '생성일';
COMMENT ON COLUMN PAYMENT.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN PAYMENT.AUDIT_USER IS '감사 사용자';

CREATE INDEX IDX_PMT_PAYMENT_NO ON PAYMENT (PAYMENT_NO);
CREATE INDEX IDX_PMT_CUSTOMER_CODE ON PAYMENT (CUSTOMER_CODE);
CREATE INDEX IDX_PMT_RELATED_RESOLUTION_NO ON PAYMENT (RELATED_RESOLUTION_NO);


-- 19. DAILY_CLOSING_STATUS (일별 마감 상태)
CREATE TABLE DAILY_CLOSING_STATUS
(
    CLOSING_DATE DATE NOT NULL PRIMARY KEY,                        -- 마감일자 (PK)
    STATUS VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,                   -- 상태 (OPEN, CLOSED, REOPENED)
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL              -- 감사 사용자
);

COMMENT ON TABLE DAILY_CLOSING_STATUS IS '일별 마감 상태';
COMMENT ON COLUMN DAILY_CLOSING_STATUS.CLOSING_DATE IS '마감일자';
COMMENT ON COLUMN DAILY_CLOSING_STATUS.STATUS IS '상태';
COMMENT ON COLUMN DAILY_CLOSING_STATUS.CREATE_DATE IS '생성일';
COMMENT ON COLUMN DAILY_CLOSING_STATUS.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN DAILY_CLOSING_STATUS.AUDIT_USER IS '감사 사용자';


-- 20. CLOSING_STATUS (월별/연도별 마감 상태)
CREATE TABLE CLOSING_STATUS
(
    CLOSING_YEAR_MONTH VARCHAR2(6) NOT NULL PRIMARY KEY,           -- 마감연월 (YYYYMM) (PK)
    STATUS VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,                   -- 상태 (OPEN, CLOSED, REOPENED)
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL              -- 감사 사용자
);

COMMENT ON TABLE CLOSING_STATUS IS '월별/연도별 마감 상태';
COMMENT ON COLUMN CLOSING_STATUS.CLOSING_YEAR_MONTH IS '마감연월';
COMMENT ON COLUMN CLOSING_STATUS.STATUS IS '상태';
COMMENT ON COLUMN CLOSING_STATUS.CREATE_DATE IS '생성일';
COMMENT ON COLUMN CLOSING_STATUS.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN CLOSING_STATUS.AUDIT_USER IS '감사 사용자';


-- 21. LOAN_CONTRACTS (대출 계약)
CREATE TABLE LOAN_CONTRACTS
(
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 대출 계약 ID (PK)
    LOAN_CONTRACT_NO VARCHAR2(20) UNIQUE NOT NULL,                 -- 대출계약번호 (고유)
    CUSTOMER_CODE VARCHAR2(20) NOT NULL,                           -- 고객코드 (FK)
    LOAN_PRODUCT VARCHAR2(100) NOT NULL,                           -- 대출상품명
    PRINCIPAL_AMOUNT NUMBER(19, 2) NOT NULL,                       -- 대출원금
    DISBURSEMENT_DATE DATE NOT NULL,                               -- 실행일
    MATURITY_DATE DATE NOT NULL,                                   -- 만기일
    INTEREST_RATE NUMBER(5, 4) NOT NULL,                           -- 이자율
    REPAYMENT_METHOD VARCHAR2(50) NOT NULL,                        -- 상환방법 (원리금균등, 만기일시)
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,                -- 상태 (ACTIVE, PAID_OFF, DEFAULT)
    CURRENT_PRINCIPAL_BALANCE NUMBER(19, 2) NOT NULL,              -- 현재원금잔액
    DEFERRED_LOAN_FEE NUMBER(19, 2) DEFAULT 0.00 NOT NULL,         -- 이연대출부대손익
    EFFECTIVE_INTEREST_RATE NUMBER(5, 4) NOT NULL,                 -- 유효이자율 (EIR)
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL,             -- 감사 사용자

    CONSTRAINT FK_LCN_CUSTOMER_CODE FOREIGN KEY (CUSTOMER_CODE) REFERENCES CUSTOMER (CUSTOMER_CODE)
);

COMMENT ON TABLE LOAN_CONTRACTS IS '대출 계약';
COMMENT ON COLUMN LOAN_CONTRACTS.ID IS '대출 계약 ID';
COMMENT ON COLUMN LOAN_CONTRACTS.LOAN_CONTRACT_NO IS '대출계약번호';
COMMENT ON COLUMN LOAN_CONTRACTS.CUSTOMER_CODE IS '고객코드';
COMMENT ON COLUMN LOAN_CONTRACTS.LOAN_PRODUCT IS '대출상품명';
COMMENT ON COLUMN LOAN_CONTRACTS.PRINCIPAL_AMOUNT IS '대출원금';
COMMENT ON COLUMN LOAN_CONTRACTS.DISBURSEMENT_DATE IS '실행일';
COMMENT ON COLUMN LOAN_CONTRACTS.MATURITY_DATE IS '만기일';
COMMENT ON COLUMN LOAN_CONTRACTS.INTEREST_RATE IS '이자율';
COMMENT ON COLUMN LOAN_CONTRACTS.REPAYMENT_METHOD IS '상환방법';
COMMENT ON COLUMN LOAN_CONTRACTS.STATUS IS '상태';
COMMENT ON COLUMN LOAN_CONTRACTS.CURRENT_PRINCIPAL_BALANCE IS '현재원금잔액';
COMMENT ON COLUMN LOAN_CONTRACTS.DEFERRED_LOAN_FEE IS '이연대출부대손익';
COMMENT ON COLUMN LOAN_CONTRACTS.EFFECTIVE_INTEREST_RATE IS '유효이자율 (EIR)';
COMMENT ON COLUMN LOAN_CONTRACTS.CREATE_DATE IS '생성일';
COMMENT ON COLUMN LOAN_CONTRACTS.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN LOAN_CONTRACTS.AUDIT_USER IS '감사 사용자';

CREATE INDEX IDX_LCN_LOAN_CONTRACT_NO ON LOAN_CONTRACTS (LOAN_CONTRACT_NO);
CREATE INDEX IDX_LCN_CUSTOMER_CODE ON LOAN_CONTRACTS (CUSTOMER_CODE);


-- 22. TAX_INVOICE (세금계산서)
CREATE TABLE TAX_INVOICE
(
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 세금계산서 ID (PK)
    INVOICE_NO VARCHAR2(20) UNIQUE NOT NULL,                       -- 세금계산서번호 (고유)
    ISSUE_DATE DATE NOT NULL,                                      -- 발행일자
    SUPPLIER_CUSTOMER_CODE VARCHAR2(20) NOT NULL,                  -- 공급자 거래처코드 (FK)
    RECIPIENT_CUSTOMER_CODE VARCHAR2(20) NOT NULL,                 -- 공급받는자 거래처코드 (FK)
    SUPPLY_AMOUNT NUMBER(19, 2) NOT NULL,                          -- 공급가액
    TAX_AMOUNT NUMBER(19, 2) NOT NULL,                             -- 세액
    TOTAL_AMOUNT NUMBER(19, 2) NOT NULL,                           -- 총액 (공급가액 + 세액)
    TYPE VARCHAR2(20) NOT NULL,                                    -- 유형 (PURCHASE, SALES)
    STATUS VARCHAR2(20) DEFAULT 'ISSUED' NOT NULL,                -- 상태 (ISSUED, CANCELED)
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL,             -- 감사 사용자

    CONSTRAINT FK_TI_SUPPLIER_CUSTOMER_CODE FOREIGN KEY (SUPPLIER_CUSTOMER_CODE) REFERENCES CUSTOMER (CUSTOMER_CODE),
    CONSTRAINT FK_TI_RECIPIENT_CUSTOMER_CODE FOREIGN KEY (RECIPIENT_CUSTOMER_CODE) REFERENCES CUSTOMER (CUSTOMER_CODE)
);

COMMENT ON TABLE TAX_INVOICE IS '세금계산서';
COMMENT ON COLUMN TAX_INVOICE.ID IS '세금계산서 ID';
COMMENT ON COLUMN TAX_INVOICE.INVOICE_NO IS '세금계산서번호';
COMMENT ON COLUMN TAX_INVOICE.ISSUE_DATE IS '발행일자';
COMMENT ON COLUMN TAX_INVOICE.SUPPLIER_CUSTOMER_CODE IS '공급자 거래처코드';
COMMENT ON COLUMN TAX_INVOICE.RECIPIENT_CUSTOMER_CODE IS '공급받는자 거래처코드';
COMMENT ON COLUMN TAX_INVOICE.SUPPLY_AMOUNT IS '공급가액';
COMMENT ON COLUMN TAX_INVOICE.TAX_AMOUNT IS '세액';
COMMENT ON COLUMN TAX_INVOICE.TOTAL_AMOUNT IS '총액';
COMMENT ON COLUMN TAX_INVOICE.TYPE IS '유형';
COMMENT ON COLUMN TAX_INVOICE.STATUS IS '상태';
COMMENT ON COLUMN TAX_INVOICE.CREATE_DATE IS '생성일';
COMMENT ON COLUMN TAX_INVOICE.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN TAX_INVOICE.AUDIT_USER IS '감사 사용자';

CREATE INDEX IDX_TI_INVOICE_NO ON TAX_INVOICE (INVOICE_NO);
CREATE INDEX IDX_TI_ISSUE_DATE ON TAX_INVOICE (ISSUE_DATE);
CREATE INDEX IDX_TI_SUPPLIER_CUSTOMER_CODE ON TAX_INVOICE (SUPPLIER_CUSTOMER_CODE);
CREATE INDEX IDX_TI_RECIPIENT_CUSTOMER_CODE ON TAX_INVOICE (RECIPIENT_CUSTOMER_CODE);


-- 23. FINANCIAL_REPORT (재무보고서)
CREATE TABLE FINANCIAL_REPORT
(
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 재무보고서 ID (PK)
    REPORT_NO VARCHAR2(20) UNIQUE NOT NULL,                        -- 보고서번호 (고유)
    REPORT_NAME VARCHAR2(100) NOT NULL,                            -- 보고서명
    REPORT_TYPE VARCHAR2(50) NOT NULL,                             -- 보고서유형 (FS, IS, CFS)
    BASE_DATE DATE NOT NULL,                                       -- 기준일자
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL              -- 감사 사용자
);

COMMENT ON TABLE FINANCIAL_REPORT IS '재무보고서';
COMMENT ON COLUMN FINANCIAL_REPORT.ID IS '재무보고서 ID';
COMMENT ON COLUMN FINANCIAL_REPORT.REPORT_NO IS '보고서번호';
COMMENT ON COLUMN FINANCIAL_REPORT.REPORT_NAME IS '보고서명';
COMMENT ON COLUMN FINANCIAL_REPORT.REPORT_TYPE IS '보고서유형';
COMMENT ON COLUMN FINANCIAL_REPORT.BASE_DATE IS '기준일자';
COMMENT ON COLUMN FINANCIAL_REPORT.CREATE_DATE IS '생성일';
COMMENT ON COLUMN FINANCIAL_REPORT.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN FINANCIAL_REPORT.AUDIT_USER IS '감사 사용자';

CREATE INDEX IDX_FR_REPORT_NO ON FINANCIAL_REPORT (REPORT_NO);
CREATE INDEX IDX_FR_REPORT_TYPE ON FINANCIAL_REPORT (REPORT_TYPE);
CREATE INDEX IDX_FR_BASE_DATE ON FINANCIAL_REPORT (BASE_DATE);


-- 24. FINANCIAL_NOTE (재무보고서 주석)
CREATE TABLE FINANCIAL_NOTE
(
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- 주석 ID (PK)
    REPORT_NO VARCHAR2(20) NOT NULL,                               -- 보고서번호 (FK)
    NOTE_NO NUMBER(5) NOT NULL,                                    -- 주석번호 (보고서 내 순번)
    NOTE_CONTENT CLOB NOT NULL,                                    -- 주석내용
    CREATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 생성일
    UPDATE_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,           -- 수정일
    AUDIT_USER VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL,             -- 감사 사용자

    CONSTRAINT FK_FN_REPORT_NO FOREIGN KEY (REPORT_NO) REFERENCES FINANCIAL_REPORT (REPORT_NO),
    CONSTRAINT UDX_FN_REPORT_NOTE UNIQUE (REPORT_NO, NOTE_NO) -- 보고서 내 주석번호 고유성
);

COMMENT ON TABLE FINANCIAL_NOTE IS '재무보고서 주석';
COMMENT ON COLUMN FINANCIAL_NOTE.ID IS '주석 ID';
COMMENT ON COLUMN FINANCIAL_NOTE.REPORT_NO IS '보고서번호';
COMMENT ON COLUMN FINANCIAL_NOTE.NOTE_NO IS '주석번호';
COMMENT ON COLUMN FINANCIAL_NOTE.NOTE_CONTENT IS '주석내용';
COMMENT ON COLUMN FINANCIAL_NOTE.CREATE_DATE IS '생성일';
COMMENT ON COLUMN FINANCIAL_NOTE.UPDATE_DATE IS '수정일';
COMMENT ON COLUMN FINANCIAL_NOTE.AUDIT_USER IS '감사 사용자';

CREATE INDEX IDX_FN_REPORT_NO ON FINANCIAL_NOTE (REPORT_NO);