-- PostgreSQL과 H2 PostgreSQL mode가 함께 이해하는 표준 identity/DECIMAL 구문만 사용합니다.
CREATE TABLE budget_fiscal_year_controls (
    fiscal_year VARCHAR(4) PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(10) NOT NULL DEFAULT 'OPEN',
    closed_by VARCHAR(80),
    closed_at TIMESTAMP,
    CONSTRAINT ck_budget_fiscal_year_controls_year
        CHECK (CHAR_LENGTH(fiscal_year) = 4),
    CONSTRAINT ck_budget_fiscal_year_controls_status
        CHECK (status IN ('OPEN', 'CLOSED')),
    CONSTRAINT ck_budget_fiscal_year_controls_closed_audit CHECK (
        (status = 'OPEN' AND closed_by IS NULL AND closed_at IS NULL)
        OR (status = 'CLOSED' AND closed_by IS NOT NULL AND closed_at IS NOT NULL)
    )
);

-- 유효한 네 자리 연도를 모두 미리 만들어 SELECT ... FOR UPDATE의 "없는 행" 경쟁을 제거합니다.
INSERT INTO budget_fiscal_year_controls (fiscal_year, version, status)
SELECT thousands.digit || hundreds.digit || tens.digit || ones.digit, 0, 'OPEN'
FROM (VALUES ('0'), ('1'), ('2'), ('3'), ('4'), ('5'), ('6'), ('7'), ('8'), ('9'))
        AS thousands(digit)
CROSS JOIN (VALUES ('0'), ('1'), ('2'), ('3'), ('4'), ('5'), ('6'), ('7'), ('8'), ('9'))
        AS hundreds(digit)
CROSS JOIN (VALUES ('0'), ('1'), ('2'), ('3'), ('4'), ('5'), ('6'), ('7'), ('8'), ('9'))
        AS tens(digit)
CROSS JOIN (VALUES ('0'), ('1'), ('2'), ('3'), ('4'), ('5'), ('6'), ('7'), ('8'), ('9'))
        AS ones(digit);

CREATE TABLE budget_idempotency_shards (
    shard_id SMALLINT PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_budget_idempotency_shards_range CHECK (shard_id BETWEEN 0 AND 255)
);

-- 256개의 영구 lock row는 업무 행이 아직 없어도 동일 idempotency key를 같은 행에서 직렬화합니다.
INSERT INTO budget_idempotency_shards (shard_id, version)
SELECT high_digit.digit * 16 + low_digit.digit, 0
FROM (
    VALUES (0), (1), (2), (3), (4), (5), (6), (7),
           (8), (9), (10), (11), (12), (13), (14), (15)
) AS high_digit(digit)
CROSS JOIN (
    VALUES (0), (1), (2), (3), (4), (5), (6), (7),
           (8), (9), (10), (11), (12), (13), (14), (15)
) AS low_digit(digit);

CREATE TABLE budget_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    plan_code VARCHAR(50) NOT NULL,
    year_month VARCHAR(6) NOT NULL,
    department_code VARCHAR(50) NOT NULL,
    account_code VARCHAR(50) NOT NULL,
    allocated_amount DECIMAL(19, 2) NOT NULL,
    transferred_in_amount DECIMAL(19, 2) NOT NULL DEFAULT 0.00,
    transferred_out_amount DECIMAL(19, 2) NOT NULL DEFAULT 0.00,
    executed_amount DECIMAL(19, 2) NOT NULL DEFAULT 0.00,
    status VARCHAR(20) NOT NULL,
    created_by VARCHAR(80) NOT NULL,
    approved_by VARCHAR(80),
    closed_by VARCHAR(80),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    audit_user VARCHAR(80) NOT NULL,
    CONSTRAINT uq_budget_plans_plan_code UNIQUE (plan_code),
    CONSTRAINT uq_budget_plans_business_key
        UNIQUE (year_month, department_code, account_code),
    CONSTRAINT ck_budget_plans_year_month_length CHECK (CHAR_LENGTH(year_month) = 6),
    CONSTRAINT ck_budget_plans_allocated_positive CHECK (allocated_amount > 0),
    CONSTRAINT ck_budget_plans_transferred_in_nonnegative CHECK (transferred_in_amount >= 0),
    CONSTRAINT ck_budget_plans_transferred_out_nonnegative CHECK (transferred_out_amount >= 0),
    CONSTRAINT ck_budget_plans_executed_nonnegative CHECK (executed_amount >= 0),
    CONSTRAINT ck_budget_plans_available_nonnegative CHECK (
        allocated_amount + transferred_in_amount - transferred_out_amount - executed_amount >= 0
    ),
    CONSTRAINT ck_budget_plans_status CHECK (status IN ('DRAFT', 'APPROVED', 'CLOSED')),
    CONSTRAINT ck_budget_plans_actors CHECK (
        (status = 'DRAFT' AND approved_by IS NULL AND closed_by IS NULL)
        OR (status = 'APPROVED' AND approved_by IS NOT NULL AND closed_by IS NULL)
        OR (status = 'CLOSED' AND approved_by IS NOT NULL AND closed_by IS NOT NULL)
    )
);

-- 회계연도 LIKE 'YYYY%' + 상태 필터와 결정적 id 잠금 순서를 지원합니다.
CREATE INDEX idx_budget_plans_year_month_status_id
    ON budget_plans (year_month, status, id);

CREATE TABLE budget_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_key VARCHAR(100) NOT NULL,
    from_plan_id BIGINT NOT NULL,
    to_plan_id BIGINT NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    requested_by VARCHAR(80) NOT NULL,
    approved_by VARCHAR(80),
    requested_at TIMESTAMP NOT NULL,
    decided_at TIMESTAMP,
    CONSTRAINT uq_budget_transfers_request_key UNIQUE (request_key),
    CONSTRAINT fk_budget_transfers_from_plan
        FOREIGN KEY (from_plan_id) REFERENCES budget_plans (id),
    CONSTRAINT fk_budget_transfers_to_plan
        FOREIGN KEY (to_plan_id) REFERENCES budget_plans (id),
    CONSTRAINT ck_budget_transfers_distinct_plans CHECK (from_plan_id <> to_plan_id),
    CONSTRAINT ck_budget_transfers_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_budget_transfers_status CHECK (status IN ('REQUESTED', 'APPROVED')),
    CONSTRAINT ck_budget_transfers_approval CHECK (
        (status = 'REQUESTED' AND approved_by IS NULL AND decided_at IS NULL)
        OR (status = 'APPROVED' AND approved_by IS NOT NULL AND decided_at IS NOT NULL)
    )
);

CREATE INDEX idx_budget_transfers_from_plan_requested
    ON budget_transfers (from_plan_id, requested_at, id);
CREATE INDEX idx_budget_transfers_to_plan_requested
    ON budget_transfers (to_plan_id, requested_at, id);

CREATE TABLE budget_executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL,
    source_type VARCHAR(50) NOT NULL,
    source_id VARCHAR(100) NOT NULL,
    source_line_id VARCHAR(100) NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    execution_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    executed_by VARCHAR(80) NOT NULL,
    executed_at TIMESTAMP NOT NULL,
    cancelled_by VARCHAR(80),
    cancelled_at TIMESTAMP,
    CONSTRAINT uq_budget_executions_source
        UNIQUE (source_type, source_id, source_line_id),
    CONSTRAINT fk_budget_executions_plan
        FOREIGN KEY (plan_id) REFERENCES budget_plans (id),
    CONSTRAINT ck_budget_executions_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_budget_executions_status CHECK (status IN ('EXECUTED', 'CANCELLED')),
    CONSTRAINT ck_budget_executions_cancellation CHECK (
        (status = 'EXECUTED' AND cancelled_by IS NULL AND cancelled_at IS NULL)
        OR (status = 'CANCELLED' AND cancelled_by IS NOT NULL AND cancelled_at IS NOT NULL)
    )
);

CREATE INDEX idx_budget_executions_plan_date_status
    ON budget_executions (plan_id, execution_date, status, id);
