spring:
  application:
    name: payable-batch
  profiles:
    default: local
  main:
    web-application-type: none
  flyway:
    enabled: false
    locations: classpath:db/payable-migration
    clean-disabled: true
    baseline-on-migrate: false
  batch:
    job:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
