-- Forward-only PostgreSQL baseline. V1 and V10 are already published and must keep their checksums.
-- IF NOT EXISTS also supports databases whose tables were previously created by Hibernate.

CREATE TABLE IF NOT EXISTS journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accounting_date DATE NOT NULL,
    currency_code VARCHAR(3),
    exchange_rate NUMERIC(19, 8),
    slip_date DATE NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    slip_no VARCHAR(20) NOT NULL UNIQUE,
    status VARCHAR(20) CHECK (status IN ('DRAFT', 'REQUESTED', 'APPROVED', 'REJECTED', 'POSTED', 'REVERSED')),
    audit_user VARCHAR(50),
    created_by VARCHAR(50),
    entry_type VARCHAR(50),
    lineage_source_type VARCHAR(50),
    lineage_source_id VARCHAR(100),
    description VARCHAR(200),
    rejection_reason VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS journal_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id BIGINT NOT NULL,
    side VARCHAR(10) NOT NULL CHECK (side IN ('DEBIT', 'CREDIT')),
    account_code VARCHAR(50) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    base_amount NUMERIC(19, 2) NOT NULL,
    dept_code VARCHAR(50),
    business_partner_code VARCHAR(50),
    detail_description VARCHAR(200),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    audit_user VARCHAR(50),
    CONSTRAINT fk_journal_details_entry
        FOREIGN KEY (journal_entry_id) REFERENCES journal_entries (id)
);

CREATE TABLE IF NOT EXISTS journal_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code VARCHAR(50) NOT NULL,
    rule_name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    is_active BOOLEAN NOT NULL,
    priority INTEGER NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE,
    version INTEGER NOT NULL,
    created_by VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    audit_user VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS journal_rule_conditions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id BIGINT NOT NULL,
    field VARCHAR(50) NOT NULL,
    operator VARCHAR(20) NOT NULL CHECK (operator IN (
        'EQUALS', 'NOT_EQUALS', 'STARTS_WITH', 'ENDS_WITH', 'CONTAINS',
        'GREATER_THAN', 'GREATER_THAN_OR_EQUAL', 'LESS_THAN', 'LESS_THAN_OR_EQUAL'
    )),
    condition_value VARCHAR(255) NOT NULL,
    CONSTRAINT fk_journal_rule_conditions_rule
        FOREIGN KEY (rule_id) REFERENCES journal_rules (id)
);

CREATE TABLE IF NOT EXISTS journal_rule_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id BIGINT NOT NULL,
    drcr_type VARCHAR(10) NOT NULL CHECK (drcr_type IN ('DEBIT', 'CREDIT')),
    account_subject_code_expression VARCHAR(100) NOT NULL,
    amount_expression VARCHAR(100) NOT NULL,
    description_expression VARCHAR(255),
    department_code_expression VARCHAR(50),
    business_partner_code_expression VARCHAR(50),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    audit_user VARCHAR(50),
    CONSTRAINT fk_journal_rule_details_rule
        FOREIGN KEY (rule_id) REFERENCES journal_rules (id)
);

CREATE TABLE IF NOT EXISTS gl_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_detail_id BIGINT,
    account_code VARCHAR(50) NOT NULL,
    currency_code VARCHAR(3),
    dr_amount NUMERIC(19, 2) NOT NULL,
    cr_amount NUMERIC(19, 2) NOT NULL,
    base_dr_amount NUMERIC(19, 2) NOT NULL,
    base_cr_amount NUMERIC(19, 2) NOT NULL,
    posting_date DATE,
    fiscal_year VARCHAR(255),
    fiscal_period VARCHAR(255),
    summary VARCHAR(255),
    lineage_source_type VARCHAR(255),
    lineage_source_id VARCHAR(255),
    CONSTRAINT fk_gl_entries_journal_detail
        FOREIGN KEY (journal_detail_id) REFERENCES journal_details (id)
);

CREATE TABLE IF NOT EXISTS sl_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_detail_id BIGINT,
    account_code VARCHAR(50) NOT NULL,
    business_partner_code VARCHAR(50),
    dept_code VARCHAR(50),
    currency_code VARCHAR(3),
    dr_amount NUMERIC(19, 2) NOT NULL,
    cr_amount NUMERIC(19, 2) NOT NULL,
    base_dr_amount NUMERIC(19, 2) NOT NULL,
    base_cr_amount NUMERIC(19, 2) NOT NULL,
    posting_date DATE,
    fiscal_year VARCHAR(255),
    fiscal_period VARCHAR(255),
    summary VARCHAR(255),
    lineage_source_type VARCHAR(255),
    lineage_source_id VARCHAR(255),
    CONSTRAINT fk_sl_entries_journal_detail
        FOREIGN KEY (journal_detail_id) REFERENCES journal_details (id)
);

CREATE TABLE IF NOT EXISTS gl_balances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance_date DATE NOT NULL,
    beginning_balance NUMERIC(19, 2) NOT NULL,
    debit_amount NUMERIC(19, 2) NOT NULL,
    credit_amount NUMERIC(19, 2) NOT NULL,
    ending_balance NUMERIC(19, 2) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    account_code VARCHAR(50) NOT NULL,
    period VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT uk_gl_balance_key
        UNIQUE (account_code, currency_code, balance_date, period)
);

CREATE TABLE IF NOT EXISTS sl_balances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance_date DATE NOT NULL,
    beginning_balance NUMERIC(19, 2) NOT NULL,
    debit_amount NUMERIC(19, 2) NOT NULL,
    credit_amount NUMERIC(19, 2) NOT NULL,
    ending_balance NUMERIC(19, 2) NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    account_code VARCHAR(50) NOT NULL,
    bp_code VARCHAR(50),
    dept_code VARCHAR(50),
    period VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

-- Hibernate-created legacy schemas used a normal UNIQUE constraint, which treats NULL
-- business-partner/department keys as distinct in PostgreSQL. Replace it explicitly so
-- both clean and existing schemas preserve one authoritative SL balance per nullable key.
ALTER TABLE sl_balances DROP CONSTRAINT IF EXISTS uk_sl_balance_key;
ALTER TABLE sl_balances ADD CONSTRAINT uk_sl_balance_key
    UNIQUE NULLS NOT DISTINCT
        (account_code, bp_code, dept_code, currency_code, balance_date, period);

CREATE TABLE IF NOT EXISTS unsettled_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_detail_id BIGINT NOT NULL,
    occurrence_date DATE NOT NULL,
    original_amount NUMERIC(19, 2) NOT NULL,
    settled_amount NUMERIC(19, 2) NOT NULL,
    remaining_amount NUMERIC(19, 2) NOT NULL,
    resolved BOOLEAN NOT NULL,
    status VARCHAR(20),
    account_code VARCHAR(50) NOT NULL,
    bp_code VARCHAR(50),
    management_no VARCHAR(50) NOT NULL UNIQUE,
    last_settled_by VARCHAR(50),
    last_settlement_reference VARCHAR(100),
    last_settled_at TIMESTAMP(6),
    CONSTRAINT fk_unsettled_items_journal_detail
        FOREIGN KEY (journal_detail_id) REFERENCES journal_details (id)
);

CREATE INDEX IF NOT EXISTS idx_gl_balance_lookup
    ON gl_balances (account_code, currency_code, balance_date);
CREATE INDEX IF NOT EXISTS idx_gl_balance_period
    ON gl_balances (period, account_code);
CREATE INDEX IF NOT EXISTS idx_journal_detail_journal_entry_id
    ON journal_details (journal_entry_id);
CREATE INDEX IF NOT EXISTS idx_journal_detail_account_code
    ON journal_details (account_code);
CREATE INDEX IF NOT EXISTS idx_journal_detail_dept_code
    ON journal_details (dept_code);
CREATE INDEX IF NOT EXISTS idx_journal_detail_business_partner_code
    ON journal_details (business_partner_code);
CREATE INDEX IF NOT EXISTS idx_journal_detail_side
    ON journal_details (side);
CREATE INDEX IF NOT EXISTS idx_journal_entry_slip_no
    ON journal_entries (slip_no);
CREATE INDEX IF NOT EXISTS idx_journal_entry_posting_lookup
    ON journal_entries (status, accounting_date);
CREATE INDEX IF NOT EXISTS idx_journal_entry_lineage
    ON journal_entries (lineage_source_type, lineage_source_id);
CREATE INDEX IF NOT EXISTS idx_journal_rule_code_valid
    ON journal_rules (rule_code, valid_from, valid_to);
CREATE INDEX IF NOT EXISTS idx_sl_balance_lookup
    ON sl_balances (account_code, bp_code, dept_code, balance_date);
CREATE INDEX IF NOT EXISTS idx_sl_balance_period
    ON sl_balances (period, account_code);
