-- GL18: unmatched Kafka economic events must remain visible and replayable.
-- Broker topic/partition/offset is the narrow Kafka operation identity; journal lineage remains non-unique.
CREATE TABLE journal_event_quarantine (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_topic VARCHAR(249) NOT NULL,
    source_partition INTEGER NOT NULL,
    source_offset BIGINT NOT NULL,
    payload_json TEXT NOT NULL,
    accounting_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    reason_code VARCHAR(50) NOT NULL,
    journal_entry_id BIGINT,
    first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_replay_at TIMESTAMP WITH TIME ZONE,
    last_replay_actor VARCHAR(100),
    replay_attempts INTEGER NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_journal_event_quarantine_record
        UNIQUE (source_topic, source_partition, source_offset),
    CONSTRAINT ck_journal_event_quarantine_source
        CHECK (source_partition >= 0 AND source_offset >= 0),
    CONSTRAINT ck_journal_event_quarantine_status
        CHECK (status IN ('QUARANTINED', 'REPLAYED')),
    CONSTRAINT ck_journal_event_quarantine_reason
        CHECK (reason_code = 'NO_MATCHING_RULE'),
    CONSTRAINT ck_journal_event_quarantine_replay_attempts
        CHECK (replay_attempts >= 0),
    CONSTRAINT ck_journal_event_quarantine_resolution
        CHECK ((status = 'QUARANTINED' AND journal_entry_id IS NULL)
            OR (status = 'REPLAYED' AND journal_entry_id IS NOT NULL)),
    CONSTRAINT fk_journal_event_quarantine_journal
        FOREIGN KEY (journal_entry_id) REFERENCES journal_entries (id)
);

CREATE INDEX idx_journal_event_quarantine_completeness
    ON journal_event_quarantine (status, first_seen_at);
