spring:
  cloud:
    config:
      enabled: false
    vault:
      enabled: false
  datasource:
    url: jdbc:postgresql://${DEV_DB_HOST}:${DEV_DB_PORT:5432}/${DEV_DB_NAME}
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
  batch:
    jdbc:
      initialize-schema: never
  sql:
    init:
      mode: never

tax:
  master-data:
    base-url: ${MASTER_DATA_BASE_URL:http://master-data-api:8083}
    connect-timeout: ${MASTER_DATA_CONNECT_TIMEOUT:2s}
    read-timeout: ${MASTER_DATA_READ_TIMEOUT:5s}
    remote:
      enabled: true

