spring:
  application:
    name: loan-batch
  profiles:
    default: local
  main:
    web-application-type: none
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
    vault:
      enabled: false

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
