-- Complete the ECL persistence contract without modifying the published V1-V3 migrations.

-- The runtime entity already accepts 20 characters. Widening is non-lossy for existing rows.
ALTER TABLE cr_accounts
    ALTER COLUMN original_rating TYPE VARCHAR(20);

-- CrCollateral requires an owning customer. Refuse to hide legacy orphan rows so that an
-- operator can repair them explicitly before retrying this forward-only migration.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM cr_collaterals WHERE customer_id IS NULL) THEN
        RAISE EXCEPTION
            'Cannot enforce cr_collaterals.customer_id NOT NULL: orphan collateral rows exist'
            USING HINT = 'Assign every collateral to a valid cr_customers.id, then rerun Flyway.';
    END IF;
END
$$;

ALTER TABLE cr_collaterals
    ALTER COLUMN customer_id SET NOT NULL;

-- CrAccountCollateral inherits the shared auditing mapping, while the published V1 table
-- omitted the actor columns.
ALTER TABLE cr_account_collaterals
    ADD COLUMN IF NOT EXISTS created_by VARCHAR(255),
    ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

-- Lifetime-PD transition matrix used by JpaTransitionMatrixRepository.
CREATE TABLE transition_matrix (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_date DATE NOT NULL,
    from_rating VARCHAR(10) NOT NULL,
    to_rating VARCHAR(10) NOT NULL,
    probability NUMERIC(10,6) NOT NULL,
    time_horizon INTEGER DEFAULT 1,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT uq_transition_matrix_rating_path
        UNIQUE (base_date, from_rating, to_rating)
);

-- ECL can run against an isolated database. In that topology these two tables form the
-- inbound Account Mart contract. CREATE IF NOT EXISTS also keeps a shared-database topology
-- compatible with the Account Mart-owned tables.
CREATE TABLE IF NOT EXISTS allowance_exposure_snapshots (
    base_date DATE NOT NULL,
    exposure_id VARCHAR(80) NOT NULL,
    source_system VARCHAR(30) NOT NULL,
    source_account_no VARCHAR(50) NOT NULL,
    customer_code VARCHAR(50) NOT NULL,
    customer_type VARCHAR(30),
    is_sme BOOLEAN DEFAULT FALSE,
    country_code VARCHAR(10),
    industry_code VARCHAR(20),
    product_code VARCHAR(20),
    product_category VARCHAR(30),
    legal_entity_code VARCHAR(20) NOT NULL,
    branch_code VARCHAR(20),
    currency_code VARCHAR(3) NOT NULL,
    outstanding_amount NUMERIC(19,4) NOT NULL DEFAULT 0,
    undrawn_amount NUMERIC(19,4) NOT NULL DEFAULT 0,
    interest_rate NUMERIC(10,6),
    effective_interest_rate NUMERIC(10,6),
    open_date DATE,
    maturity_date DATE,
    delinquent_days INTEGER DEFAULT 0,
    staging VARCHAR(20),
    original_rating VARCHAR(20),
    current_rating VARCHAR(20),
    warning_level VARCHAR(20),
    debt_restructured BOOLEAN NOT NULL DEFAULT FALSE,
    collateral_value NUMERIC(19,4) NOT NULL DEFAULT 0,
    collateral_type VARCHAR(20),
    accounting_account_code VARCHAR(20),
    allowance_account_code VARCHAR(20),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (base_date, exposure_id)
);

CREATE TABLE IF NOT EXISTS allowance_input_positions (
    base_dt DATE NOT NULL,
    acc_no VARCHAR(50) NOT NULL,
    customer_code VARCHAR(50) NOT NULL,
    customer_name VARCHAR(200),
    cust_type VARCHAR(30),
    is_sme BOOLEAN DEFAULT FALSE,
    country_cd VARCHAR(10),
    prod_cd VARCHAR(20),
    prod_category VARCHAR(30),
    currency VARCHAR(3) NOT NULL,
    bs_class VARCHAR(10),
    cur_bal NUMERIC(19,4),
    limit_amt NUMERIC(19,4),
    outstd_amt NUMERIC(19,4),
    market_val NUMERIC(19,4),
    int_rate NUMERIC(10,6),
    coupon_rate NUMERIC(10,6),
    rate_type VARCHAR(10),
    base_rate_cd VARCHAR(20),
    spread NUMERIC(10,6),
    payment_freq INTEGER,
    next_reset_dt DATE,
    open_dt DATE,
    maturity_dt DATE,
    repayment_method VARCHAR(20),
    grace_period INTEGER,
    repayment_freq INTEGER,
    int_rate_floor NUMERIC(10,6),
    int_rate_cap NUMERIC(10,6),
    ref_index_cd VARCHAR(20),
    internal_rating VARCHAR(10),
    external_rating VARCHAR(10),
    industry_cd VARCHAR(20),
    warning_level VARCHAR(20),
    is_debt_restructured BOOLEAN DEFAULT FALSE,
    delinquent_days INTEGER DEFAULT 0,
    staging VARCHAR(20),
    coll_amt NUMERIC(19,4),
    recognized_coll_amt NUMERIC(19,4),
    coll_type VARCHAR(20),
    pd NUMERIC(10,8),
    lgd NUMERIC(10,8),
    expected_loss NUMERIC(19,4),
    branch_cd VARCHAR(10),
    biz_unit_cd VARCHAR(10),
    margin_rate NUMERIC(10,6),
    repricing_freq INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (base_dt, acc_no)
);

-- Bring a previously-created Account Mart V1 table up to the read-model contract.
ALTER TABLE allowance_input_positions
    ALTER COLUMN cust_type TYPE VARCHAR(30),
    ADD COLUMN IF NOT EXISTS margin_rate NUMERIC(10,6),
    ADD COLUMN IF NOT EXISTS repricing_freq INTEGER;

-- Absorb dates outside the initially published 2026-04 result partition. This keeps a fresh
-- install and later accounting periods writable without rewriting the immutable V1 baseline.
CREATE TABLE allowance_ecl_results_default
    PARTITION OF allowance_ecl_results DEFAULT;

-- Foreign-key and operational lookup indexes used by the current repositories and bulk SQL.
CREATE INDEX IF NOT EXISTS idx_cr_accounts_customer_active
    ON cr_accounts(customer_id, is_active);

CREATE INDEX IF NOT EXISTS idx_cr_collaterals_customer_active
    ON cr_collaterals(customer_id, is_active);

CREATE INDEX IF NOT EXISTS idx_cr_account_collaterals_account
    ON cr_account_collaterals(account_id);

CREATE INDEX IF NOT EXISTS idx_cr_account_collaterals_collateral
    ON cr_account_collaterals(collateral_id);

CREATE INDEX IF NOT EXISTS idx_allowance_ecl_results_date_status
    ON allowance_ecl_results(base_date, status);

CREATE INDEX IF NOT EXISTS idx_allowance_exposure_base
    ON allowance_exposure_snapshots(base_date);

CREATE INDEX IF NOT EXISTS idx_allowance_exposure_customer
    ON allowance_exposure_snapshots(customer_code);

CREATE INDEX IF NOT EXISTS idx_allowance_exposure_product_currency
    ON allowance_exposure_snapshots(product_code, currency_code);
